jemalloc/jemalloc

- configure.ac
It often happens that code changes introduce mixed declarations, that then
break building with Visual Studio. Since the code style is to not use
mixed declarations anyways, we might as well enforce it with -Werror.
> Make mixed declarations an error

- src/stats.c
2c5cb613dfbdf58f88152321b63e60c58cd23972 changed `opt.junk` to be a string instead of a bool, but that change wasn't reflected in `stats_print`. Thanks @glandium for reporting this.
> Use the correct type for opt.junk when printing stats.

- src/huge.c
in src/huge.c, after each call of huge_node_locked(), huge_mtx is
already unlocked. don't unlock it twice (it is a undefined behaviour).
under openbsd, the undefined behaviour is to call `abort()`.
> huge_node_locked don't have to unlock huge_mtx

- src/arena.c
The documentation for opt.lg_dirty_mult says:
Per-arena minimum ratio (log base 2) of active to dirty
pages.  Some dirty unused pages may be allowed to accumulate,
within the limit set by the ratio (or one chunk worth of dirty
pages, whichever is greater) (...)
The restriction in parentheses currently doesn't happen. This makes
jemalloc aggressively madvise(), which in turns increases the amount
of page faults significantly.
For instance, this resulted in several(!) hundred(!) milliseconds
startup regression on Firefox for Android.
This may require further tweaking, but starting with actually doing
what the documentation says is a good start.
> Make opt.lg_dirty_mult work as documented

- src/chunk.c
8ddc93293cd8370870f221225ef1e013fbff6d65 switched this to over using the
address tree in order to avoid false negatives, so it now needs to check
that the size of the free extent is large enough to satisfy the request.
> add missing check for new_addr chunk size

- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/jemalloc_macros.h.in
9906660 added a --without-export configure option to avoid exporting
jemalloc symbols, but the option didn't actually work.
> Make --without-export actually work

- configure.ac
under some compiler (gcc 4.8.4 in particular), the auto-detection of TLS
don't work properly.
force tls to be disabled for openbsd only (so split openbsd and bitrig).
the testsuite pass under gcc (4.8.4) and gcc (4.2.1)
this PR resolve issue #223
> OpenBSD don't support TLS

- include/jemalloc/jemalloc.sh
Fixes warning with newer GCCs:
include/jemalloc/jemalloc.h:229:2: warning: extra ';' [-Wpedantic]
};
^
> Remove extraneous ';' on closing 'extern "C"'

- include/jemalloc/internal/util.h
In builds with profiling disabled (default), the opt_prof_prefix array
has a one byte length as a micro-optimization. This will cause the usage
of write in the unused profiling code to be statically detected as a
buffer overflow by Bionic's _FORTIFY_SOURCE implementation as it tries
to detect read overflows in addition to write overflows.
> work around _FORTIFY_SOURCE false positive

- bin/jeprof.in
If jemalloc profiling is disabled, jeprof currently gives an incomprehensible error message
> Jeprof curl option fixes

- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
- msvc/projects/vc2015/test_threads/test_threads.vcxproj
Just realized MSVC debug build missed a couple of source files.
This also improves static lib naming (e.g jemalloc-vc140-release-static.lib)
> Fix MSVC project and improve MSVC lib naming (v140 -> vc140)

- include/jemalloc/internal/jemalloc_internal.h.in
The `arenas_extend()` function was renamed to `arenas_init()` in commit 8bb3198f72fc7587dc93527f9f19fb5be52fa553, but its function declaration was not removed from jemalloc_internal.h.in.
> Remove unused arenas_extend() function declaration.

- include/jemalloc/internal/jemalloc_internal.h.in
- test/unit/math.c
* Work around a weird pgi bug in test/unit/math.c
* Don't use compact red-black trees under pgi. I'm not sure if this is a
red-black tree bug a pgi bug, but since most of the red-black trees seem to
have been replaced with pairing-heaps I didn't investigate very hard.
* Note that this also relies on https://github.com/jemalloc/jemalloc/issues/390
because pgi doesn't have support for TLS.
Passes `make check` with pgi 15.10.0 and 16.4.0 (-O and -O3)
> Fix support for the PGI compiler

- .appveyor.yml
- include/jemalloc/internal/atomic.h
- include/jemalloc/internal/extent.h
This builds jemalloc and runs all checks with:
- MSVC 2015 64-bits
- MSVC 2015 32-bits
- MINGW64 (from msys2)
- MINGW32 (from msys2)
Normally, AppVeyor configs are named appveyor.yml, but it is possible to
configure the .yml file name in the AppVeyor project settings such that
the file stays "hidden", like typical travis configs.
Considering how many times MSVC builds have broken, I'd appreciate if you could setup AppVeyor such that it runs when you push to the canonical jemalloc repository (travis-ci would be useful too, FWIW).
> Add an AppVeyor config

- configure.ac
This adds support for the Cray compiler (versions 8.4.0 and newer). 8.4 was the
first version to add support for gnu style inline assembly, so there's not much
hope getting jemalloc to work with earlier versions.
There's an inlining bug in 8.4.X (that has been fixed for 8.5) so this patch
throws `-hnognu -hipa2` to work around the bug if 8.4.X is being used.
This also disables automatic dependency generation, because Cray doesn't
support the `-MM` or `-MT` dependency generation flags.
Additionally, Cray doesn't support `-Werror` so this adds the equivalent
`-herror_on_warning` everywhere that `-Werror` is thrown so that jemalloc
correctly detects when attributes don't actually work.
With this Cray 8.4.0 and 8.5.1 build cleanly and pass `make check`
> Add support for the Cray compiler

- include/jemalloc/jemalloc_macros.h.in
Trivial fix for clang/gcc -Wundef
> Fix -Wundef in _MSC_VER check.

- configure.ac
Cherry-pick aec0753, 3ef6793, 3dee73f, and 47b34dd to master
This adds support for the Cray compiler (versions 8.4.0 and newer). 8.4 was the
first version to add support for gnu style inline assembly, so there's not much
hope getting jemalloc to work with earlier versions.
There's an inlining bug in 8.4.X (that has been fixed for 8.5) so this patch
throws `-hnognu -hipa2` to work around the bug if 8.4.X is being used.
This also disables automatic dependency generation, because Cray doesn't
support the `-MM` or `-MT` dependency generation flags.
Additionally, Cray doesn't support `-Werror` so this adds the equivalent
`-herror_on_warning` everywhere that `-Werror` is thrown so that jemalloc
correctly detects when attributes don't actually work.
With this Cray 8.4.0 and 8.5.1 build cleanly …
> Cherry-pick support for the Cray compiler to master

- configure.ac
The core issue here is the weak linking of the symbol, and in certain
environments--for instance, using the latest Xcode (8.1) with the latest
SDK (10.12)--os_unfair_lock may resolve even though you're compiling on
a host that doesn't support it (10.11).
We can use the availability macros to circumvent this problem, and
detect that we're not compiling for a target that is going to support
them and error out at compile time.  The other alternative is to do a
runtime check, but that presents issues for cross-compiling.
> Implement a more reliable detection scheme for os_unfair_lock.

- src/tcache.c
The stats merging is already taken care of by tcache_flush.
> Remove redundent stats-merging logic when destroying tcache. 

- Makefile.in
- include/jemalloc/internal/private_symbols.txt
- include/jemalloc/internal/prof_externs.h
- include/jemalloc/internal/prof_inlines.h
- src/arena.c
- src/extent.c
- src/prof.c
- test/unit/prof_tctx.c
This fixes #499, and does some refactoring of ```prof_dump()``` in order to allow the ```test_prof_realloc``` test.
Ignore all but the last two commits; the others are for other existing pull requests, and it appears I can't omit them from this pull request without rebasing to dev.
> Prof realloc

- configure.ac
This will allow us to start moving declarations to first use, e.g. in #568.
> Remove -Werror=declaration-after-statement.

- include/jemalloc/internal/ctl_structs.h
- include/jemalloc/internal/ctl_types.h
- src/ctl.c
- src/extent.c
- test/unit/base.c
While testing #569, I tried ```--disable-stats``` and hit a huge set of regressions and new bugs.  This diff fixes all those revealed by the tests.
We definitely need to add some more travis-CI configurations (at least ```--enable-debug```, ```--disable-stats``` and ```--disable-tcache```).
> Fix lots of --disable-stats issues

- src/jemalloc.c
In the refactoring that unified the allocation paths, usize was substituted for
size. This worked fine under the default test configuration, but triggered
asserts when we started beefing up our CI testing.
This change fixes the issue, and clarifies the comment describing the argument
selection that it got wrong.
> Fix a bug in which a potentially invalid usize replaced size

- .travis.yml
- scripts/gen_travis.py
Introduces gen_travis.py, which generates .travis.yml, and updates .travis.yml
to be the generated version.
The travis build matrix approach doesn't play well with mixing and matching
various different environment settings, so we generate every build explicitly,
rather than letting them do it for us.
To avoid abusing travis resources (and save us time waiting for CI results), we
don't test every possible combination of options; we only check up to 2 unusual
settings at a time.
This will resolve https://github.com/jemalloc/jemalloc/issues/578 .
> Beef up travis CI integration testing

- run_tests.sh
- scripts/gen_run_tests.py
In 6e7d0890 we added better travis continuous integration tests. This is nice,
but has two problems:
- We run only a subset of interesting tests.
- The travis builds can take hours to give us back results (especially on OS X).
This adds scripts/gen_run_tests.py, and its output, run_tests.sh, which builds
and runs a larger portion of possible configurations on the local machine.
While a travis run takes several hours to complete , I can run these scripts on
my (OS X) latop and (Linux) devserve, and get a more exhaustive set of results
back in around 10 minutes.
> Introduce scripts to run many tests

- src/stats.c
When multiple threads calling stats_print, race could happen as we read the
counters in separate mallctl calls. The removed assertion could fail when there
are other operations happening at the same time. For simplicity, assume a safe
bound when race is detected instead of retrying.
This should resolve #591.
> Handle race in stats_arena_bins_print

- test/unit/decay.c
This avoids a run-time warning I noticed while looking through CI logs.
> Conditianalize lg_tcache_max use on JEMALLOC_TCACHE.

- include/jemalloc/internal/mutex_inlines.h
This fixes interactions with ```witness_assert_depth[_to_rank]()```, which was
added in d0e93ada51e20f4ae394ff4dbdcf96182767c89c (Add
```witness_assert_depth[_to_rank]()```.).
> Enable mutex witnesses even when !isthreaded.

- include/jemalloc/internal/rtree_inlines.h
Fix rtree_subkey() to use uintptr_t rather than unsigned for key
bitmasking.  This regression was introduced by
4a346f55939af4f200121cc4454089592d952f18 (Replace rtree path cache with
LRU cache.).
> Fix rtree_subkey() regression.

- include/jemalloc/internal/private_symbols.txt
- include/jemalloc/internal/tsd_inlines.h
- include/jemalloc/internal/tsd_structs.h
- src/tsd.c
This avoids a gcc diagnostic note:
note: The ABI for passing parameters with 64-byte alignment has
changed in GCC 4.6
This note related to the cacheline alignment of rtree_ctx_t, which was
introduced by 4a346f55939af4f200121cc4454089592d952f18 (Replace rtree
path cache with LRU cache.).
> Do not generate unused tsd_*_[gs]et() functions.

- include/jemalloc/internal/arena_externs.h
- include/jemalloc/internal/private_symbols.txt
- src/arena.c
- src/large.c
Ignore diffs that are part of #623; 956f395e301476d159ebc001a93f8889c35c17cd is the only relevant diff in this pull request.
> Fix arena->stats.mapped accounting

- include/jemalloc/internal/extent_externs.h
- include/jemalloc/internal/extent_structs.h
- src/arena.c
- src/extent.c
Ignore diffs that are part of #623 and #624; 177dfda080d1a1bc7bcac1d3bda937ec6503e451 (Optimize extent coalescing.) and d75d00b29615063dac3f103790b53ebe5966387f (Disable coalescing of cached extents.) are the only ones relevant here.
> Coalesce less

- src/arena.c
Remove a call to arena_maybe_purge() that was necessary for ratio-based
purging, but is obsolete in the context of decay-based purging.
> Remove obsolete arena_maybe_purge() call.

- configure.ac
This removes an unneeded library dependency when falling back to
intrinsics-based backtracing (or failing to enable heap profiling at
all).
> Avoid -lgcc for heap profiling if unwind.h is missing.

- Makefile.in
- include/jemalloc/internal/private_symbols.txt
- src/mb.c
This complements 94c5d22a4da7844d0bdc5b370e47b1ba14268af2 (Remove mb.h,
which is unused).
> Remove remainder of mb (memory barrier).

- Makefile.in
- include/jemalloc/internal/extent.h
- include/jemalloc/internal/private_symbols.txt
- src/chunk.c
- src/extent.c
- test/unit/extent_quantize.c
This regression was caused by
b9408d77a63a54fd331f9b81c884f68e6d57f2e5 (Fix/simplify chunk_recycle()
allocation size computations.).
This resolves #647.
> Fix huge-aligned allocation.

- include/jemalloc/internal/extent_externs.h
- src/extent.c
Remove obsolete unit test scaffolding for extent quantization.  Remove
redundant assertions.  Add an assertion to
extents_first_best_fit_locked() that should help prevent aligned
allocation regressions.
> Tidy up extent quantization.

- include/jemalloc/internal/stats_structs.h
- src/arena.c
This fixes a regression introduced by
d433471f581ca50583c7a99f9802f7388f81aa36 (Derive
{allocated,nmalloc,ndalloc,nrequests}_large stats.).
> Fix {allocated,nmalloc,ndalloc,nrequests}_large stats regression.

- src/arena.c
- src/jemalloc.c
Fix lg_chunk clamping to take into account cache-oblivious large
allocation.  This regression only resulted in incorrect behavior if
!config_fill (false unless --disable-fill specified) and
config_cache_oblivious (true unless --disable-cache-oblivious
specified).
This regression was introduced by
8a03cf039cd06f9fa6972711195055d865673966 (Implement cache index
randomization for large allocations.), which was first released in
4.0.0.
This resolves #555.
> Fix lg_chunk clamping for config_cache_oblivious.

- configure.ac
This regression was introduced by
194d6f9de8ff92841b67f38a2a6a06818e3240dd (Restructure *CFLAGS/*CXXFLAGS
configuration.).
> Put -D_REENTRANT in CPPFLAGS rather than CFLAGS.

- scripts/gen_run_tests.py
This disables run_tests.sh configurations that use the combination of
32-bit clang and heap profiling.
> Dodge 32-bit-clang-specific backtracing failure.

- INSTALL
- configure.ac
- doc/jemalloc.xml.in
- include/jemalloc/internal/arena.h
- include/jemalloc/internal/jemalloc_internal.h.in
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/private_symbols.txt
- src/arena.c
- src/ctl.c
- src/jemalloc.c
- src/pages.c
- src/stats.c
- test/unit/mallctl.c
Detect whether chunks start off as THP-capable by default (according to
the state of /sys/kernel/mm/transparent_hugepage/enabled), and use this
as the basis for whether to call pages_nohuge() once per chunk during
first purge of any of the chunk's page runs.
Add the --disable-thp configure option, as well as the the opt.thp
mallctl.
This resolves #541.
> Fix/enhance THP integration.

- src/jemalloc.c
This avoids signed/unsigned comparison warnings when specifying integer
constants as inputs.
Clean up whitespace and add clarifying parentheses for
CONF_HANDLE_SIZE_T(opt_lg_chunk, ...).
> Add casts to CONF_HANDLE_T_U().

- configure.ac
just simple typo patch in configure.ac 
Thanks. I always use jemalloc well :)
> fix typo sytem -> system

- include/jemalloc/internal/stats_structs.h
- src/arena.c
Convert the nrequests field to be partially derived, and the curlextents
to be fully derived, in order to reduce the number of stats updates
needed during common operations.
This change affects ndalloc stats during arena reset, because it is no
longer possible to cancel out ndalloc effects (curlextents would become
negative).
> Optimize malloc_large_stats_t maintenance.

- include/jemalloc/internal/extent_externs.h
- include/jemalloc/internal/extent_inlines.h
- include/jemalloc/internal/extent_structs.h
- include/jemalloc/internal/private_symbols.txt
- src/arena.c
- src/extent.c
- test/unit/decay.c
Rather than purging uncoalesced extents, perform just enough incremental
coalescing to purge only fully coalesced extents.  In the absence of
cached extent reuse, the immediate versus delayed incremental purging
algorithms result in the same purge order.
This resolves #655.
> Perform delayed coalescing prior to purging.

- include/jemalloc/internal/atomic.h
The C11 atomics backport removed this #define, which degraded atomic 64-bit
reads to require a lock even on platforms that support them.  This commit fixes
that.
> Reintroduce JEMALLOC_ATOMIC_U64

- include/jemalloc/internal/extent_structs.h
- src/extent.c
In the process, we can do some strength reduction, changing the fetch-adds and
fetch-subs to be simple loads followed by stores, since the modifications all
occur while holding the mutex.
> Convert extents_t's npages field to use C11-style atomics

- include/jemalloc/internal/arena_externs.h
- include/jemalloc/internal/private_symbols.txt
- src/arena.c
- src/jemalloc.c
- test/unit/fork.c
When witness is enabled, lock rank order needs to be preserved during
prefork, not only for each arena, but also across arenas. This change
breaks arena_prefork into further stages to ensure valid rank order
across arenas. Also changed test/unit/fork to use a manual arena to
catch this case.
> Fix arena_prefork lock rank order for witness.

- configure.ac
- doc/jemalloc.xml.in
- include/jemalloc/internal/arena_externs.h
- include/jemalloc/internal/arena_inlines_a.h
- include/jemalloc/internal/arena_structs_b.h
- include/jemalloc/internal/arena_types.h
- include/jemalloc/internal/jemalloc_internal.h.in
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/private_symbols.txt
- src/arena.c
- src/ctl.c
- src/jemalloc.c
- src/stats.c
- src/tcache.c
- test/integration/thread_arena.c
- test/unit/mallctl.c
- test/unit/stats.c
The new feature, opt.percpu_arena, determines thread-arena association
dynamically based CPU id. Three modes are supported: "percpu", "phycpu"
and disabled.
"percpu" uses the current core id (with help from sched_getcpu())
directly as the arena index, while "phycpu" will assign threads on the
same physical CPU to the same arena. In other words, "percpu" means # of
arenas == # of CPUs, while "phycpu" has # of arenas == 1/2 * (# of
CPUs). Note that no runtime check on whether hyper threading is enabled
is added yet.
When enabled, threads will be migrated between arenas when a CPU change
is detected. In the current design, to reduce overhead from reading CPU
id, each arena tracks the thread accessed most recently. When a new
thread comes in, we will read CPU id and update arena if necessary.
> Implement per-CPU arena

- include/jemalloc/internal/arena_structs_b.h
- src/arena.c
Now that boolean atomics are supported, make arena_t's purging field
bool rather than unsigned.
> Convert arena_t's purging field to bool.

- include/jemalloc/internal/rtree_inlines.h
- include/jemalloc/internal/rtree_structs.h
- src/rtree.c
In the process, I changed the implementation of rtree_elm_acquire so that it
won't even try to CAS if its initial read (getting the extent + lock bit)
indicates that the CAS is doomed to fail.  This can significantly improve
performance under contention.
We also remove a few unnecessary fences down the rtree_elm_write[_acquired]
paths.
> Convert rtree code to use C11 atomics

- include/jemalloc/internal/arena_inlines_a.h
- include/jemalloc/internal/stats_structs.h
- src/arena.c
- src/ctl.c
I expect this to be the trickiest conversion we will see, since we want atomics
on 64-bit platforms, but are also always able to piggyback on some sort of
external synchronization not under our control on non-64 bit platforms.
> Switch atomic uint64_ts in arena_stats_t to C11 atomics

- doc/jemalloc.xml.in
- include/jemalloc/internal/ctl_externs.h
- include/jemalloc/internal/ctl_structs.h
- include/jemalloc/internal/ctl_types.h
- include/jemalloc/internal/mutex_externs.h
- include/jemalloc/internal/mutex_inlines.h
- include/jemalloc/internal/mutex_structs.h
- include/jemalloc/internal/mutex_types.h
- include/jemalloc/internal/nstime_externs.h
- include/jemalloc/internal/nstime_types.h
- include/jemalloc/internal/private_symbols.txt
- include/jemalloc/internal/prof_externs.h
- include/jemalloc/internal/stats_structs.h
- src/arena.c
- src/ctl.c
- src/mutex.c
- src/nstime.c
- src/prof.c
- src/stats.c
- test/unit/stats_print.c
Add mutex profiling for a number of mutexes:
Global mtx: ```ctl``` and ```prof```
per arena mtx: 
```
"large",
"extent_freelist",
"extents_dirty",
"extents_muzzy",   
"extents_retained",
"decay_dirty",
"decay_muzzy",
"tcache_list",
"base" 
```
and  ```bin mtx```.
Also, added our own spinning with a fixed spin upper bound.
This resolves #574.
> Mutex profiling

- src/jemalloc.c
Without ALWAYS_INLINE, sometimes ifree() gets compiled into its own function,
which adds overhead on the fast path.
> Force inline ifree to avoid function call costs on fast path.

- include/jemalloc/internal/bitmap_inlines.h
- test/unit/bitmap.c
This fixes an extent searching regression on 32-bit systems, caused by
the initial bitmap_ffu() implementation in
c8021d01f6efe14dc1bd200021a815638063cb5f (Implement bitmap_ffu(), which
finds the first unset bit.), as first used in
5d33233a5e6601902df7cddd8cc8aa0b135c77b2 (Use a bitmap in extents_t to
speed up search.).
> Fix BITMAP_USE_TREE version of bitmap_ffu().

- include/jemalloc/internal/extent_inlines.h
- include/jemalloc/internal/extent_structs.h
- include/jemalloc/internal/jemalloc_internal.h.in
These changes relate to #461, and compact ```extent_t``` to 136 bytes.  I see a few options for reaching 128 bytes, but I'm not very excited about any of them:
- Remove the ```nfree``` field from ```arena_slab_data_t```, and use inherently slower bitmap operations to detect edge conditions.
- Move the ```nfree``` field from ```arena_slab_data_t``` into ```extent_t```'s ```e_bits``` (and reduce the serial number range to 31 bits).  This feels like a layering violation.
- Overlay ```extent_t```'s ```e_size``` field with ```e_slab_data```, and use the ```szind``` bits to track size when in the slab state.  I experimented with this, and it's tricky enough to get the state transitions right that we'd need to change the extent getter/setter API to make inconsistent transitions impossible.
> Extent layout

- include/jemalloc/internal/bitmap_inlines.h
- include/jemalloc/internal/bitmap_structs.h
- include/jemalloc/internal/bitmap_types.h
- src/bitmap.c
- test/unit/bitmap.c
These changes fix ```bitmap_ffu()``` for bitmaps with 3+ levels (latent bug), and with that done remove the tree-structured bitmap code altogether.  We have no current need for such complexity, and it is a serious maintenance burden, as witnessed by the ~2 days I spent making ```bitmap_ffu()``` work.
> Fix and remove tree-structured bitmap support

- include/jemalloc/internal/private_symbols.txt
- include/jemalloc/internal/rtree_inlines.h
This fixes a race that does not currently cause problems in practice, other than to cause intermittent assertion failures when clobbering the lock bit.
> Fix a race in rtree_szind_slab_update() for RTREE_LEAF_COMPACT.

- include/jemalloc/internal/rtree_inlines.h
To avoid memmove on free() fast path, simplify the cache replacement policy to
only bubble up the cache hit element by 1.
In a production benchmark, perf shows free() is ~5% slower on dev, with memmove contributing a fair portion. This should simply the cache and avoid memmove, while still maintain cache hit rate reasonably.
> Simplify rtree cache replacement policy.

- include/jemalloc/internal/arena_structs_a.h
- include/jemalloc/internal/extent_inlines.h
- include/jemalloc/internal/extent_structs.h
- include/jemalloc/internal/private_symbols.txt
- src/arena.c
- src/extent.c
Compact extent_t to 128 bytes on 64-bit systems by moving
arena_slab_data_t's nfree into extent_t's e_bits.
Cacheline-align extent_t structures so that they always cross the
minimum number of cacheline boundaries.
Re-order extent_t fields such that all fields except the slab bitmap
(and overlaid heap profiling context pointer) are in the first
cacheline.
This resolves #461.
> Move arena_slab_data_t's nfree into extent_t's e_bits.

- include/jemalloc/internal/private_symbols.txt
- include/jemalloc/internal/rtree_externs.h
- include/jemalloc/internal/rtree_types.h
- include/jemalloc/internal/tsd_externs.h
- include/jemalloc/internal/tsd_inlines.h
- include/jemalloc/internal/tsd_structs.h
- src/rtree.c
- src/tsd.c
- test/unit/rtree.c
This will facilitate embedding tcache into tsd, which will require proper
initialization cannot be done via the static initializer.  Make tsd->rtree_ctx
to be initialized via rtree_ctx_data_init().
> Add init function support to tsd members.

- include/jemalloc/internal/rtree_inlines.h
- include/jemalloc/internal/rtree_types.h
This gets rid of a branch on rcache lookup. u-benchmark shows a ~2% improvement.
> Remove the leafkey NULL check in leaf_elm_lookup.

- include/jemalloc/internal/jemalloc_internal.h.in
- include/jemalloc/internal/tcache_inlines.h
- include/jemalloc/internal/tcache_structs.h
- include/jemalloc/internal/tcache_types.h
- include/jemalloc/internal/tsd_structs.h
- src/tcache.c
This removes tcache_enabled_t, which was used to initialize tsd->tcache_enabled to opt_tcache.  Since now we have init function support for tsd members, we can get rid of this type.
> Get rid of tcache_enabled_t as we have runtime init support.

- include/jemalloc/internal/arena_externs.h
- include/jemalloc/internal/jemalloc_internal.h.in
- include/jemalloc/internal/rtree_structs.h
- include/jemalloc/internal/tcache_inlines.h
- include/jemalloc/internal/tcache_structs.h
- include/jemalloc/internal/tcache_types.h
- include/jemalloc/internal/tsd_structs.h
- include/jemalloc/internal/tsd_types.h
- src/arena.c
- src/tcache.c
- src/witness.c
1) Re-organize TSD so that frequently accessed fields are closer to the
beginning and more compact.  Assuming 64-bit, the first 3.5 cachelines now
contains everything needed on tcache fast path, expect the tcache struct itself.
2) Re-organize tcache and tbins.  Take lg_fill_div out of tbin, and reduce tbin
to 24 bytes (down from 32). Split tbins into tbins_small and tbins_large, and
place tbins_small close to the beginning.
> Optimizing TSD and thread cache layout.

- Makefile.in
- include/jemalloc/internal/hooks.h
- include/jemalloc/internal/jemalloc_internal.h.in
- include/jemalloc/internal/malloc_io.h
- include/jemalloc/internal/private_symbols.txt
- include/jemalloc/internal/stats_externs.h
- include/jemalloc/internal/tsd_structs.h
- src/arena.c
- src/hooks.c
- src/jemalloc.c
- src/prof.c
- src/tsd.c
- test/include/test/jemalloc_test.h.in
- test/include/test/test.h
- test/src/test.c
- test/stress/microbench.c
- test/unit/hooks.c
- test/unit/prof_accum.c
- test/unit/prof_active.c
- test/unit/prof_gdump.c
- test/unit/prof_reset.c
- test/unit/prof_tctx.c
- test/unit/stats.c
- test/unit/tsd.c
This tests that we don't get into any libc- or arena_new- related reentrancy that we can't handle. If we detect reentrancy (using tsd), we'll force ourselves into arena 0, which we hope has already been initialized.
> Basic reentrancy support

- configure.ac
Hyper-threaded CPUs may need a special instruction inside spin loops in
order to yield to another virtual CPU. The 'pause' instruction that is
available for x86 is not supported on Power.
Apparently the extended mnemonics like yield, mdoio, and mdoom are not
actually implemented on POWER8, although mentioned in the ISA 2.07
document. The recommended magic bits are an 'or 31,31,31'.
> Port CPU_SPINWAIT to __powerpc64__

- include/jemalloc/internal/arena_inlines_b.h
- include/jemalloc/internal/arena_structs_b.h
- include/jemalloc/internal/arena_types.h
- include/jemalloc/internal/jemalloc_internal.h.in
- src/ckh.c
- src/jemalloc.c
- src/prof.c
- src/tcache.c
This gets rid of the redundent rtree lookup down fast path.
This solves #737.
> Pass dealloc_ctx down free() fast path.

- include/jemalloc/internal/arena_inlines_b.h
- include/jemalloc/internal/arena_structs_b.h
- include/jemalloc/internal/arena_types.h
- include/jemalloc/internal/jemalloc_internal_inlines_c.h
- include/jemalloc/internal/prof_inlines_b.h
- src/arena.c
- src/jemalloc.c
- src/large.c
- src/prof.c
- test/unit/prof_tctx.c
This is to avoid redundant rtree lookups on these path, namely sdalloc and when opt_prof == true.
> Refactor sdalloc and profiling paths w/ alloc_ctx.

- include/jemalloc/internal/jemalloc_internal_inlines_a.h
- include/jemalloc/internal/jemalloc_internal_inlines_b.h
- include/jemalloc/internal/jemalloc_internal_inlines_c.h
- include/jemalloc/internal/tsd_inlines.h
- include/jemalloc/internal/tsd_structs.h
- src/arena.c
- src/jemalloc.c
- src/tsd.c
Previously we had a general detection and support of reentrancy, at the cost of
having branches and inc / dec operations on fast paths.  To avoid taxing fast
paths, we move the reentrancy operations onto tsd slow state, and only modify
reentrancy level around external calls (that might trigger reentrancy).
This resolves #753.
> Switch to fine-grained reentrancy support

- include/jemalloc/internal/jemalloc_internal_inlines_b.h
This fixs an intermittent test failure (test/unit/decay).
> Skip percpu arena when choosing iarena.

- include/jemalloc/internal/rtree_inlines.h
- include/jemalloc/internal/rtree_structs.h
- include/jemalloc/internal/rtree_types.h
- src/prof.c
- src/rtree.c
Two levels of rcache is implemented: a direct mapped cache as L1, combined with
a LRU cache as L2.  The L1 cache offers low cost on cache hit, but could suffer
collision under circumstances.  This is complemented by the L2 LRU cache, which
is slower on cache access (overhead from linear search + reordering), but solves
collison of L1 rather well.
The current config is set to 16 L1 entries, and 8 L2 entires. Production benchmark shows favorable results comparing to LRU cache only (>10% cost reduction for free()). Comparing to a 8 L1+ 8 L2 setting, this showed a better cost in free() and tcache_bin_flush(). /test/stress/microbench is slightly slower with this (~2%), as comparing best case this needs a "&" operation (compute cache index).
> Improve rtree cache with a two-level cache design.

- doc/jemalloc.xml.in
- include/jemalloc/internal/arena_structs_b.h
- include/jemalloc/internal/base_externs.h
- include/jemalloc/internal/base_structs.h
- include/jemalloc/internal/ctl_types.h
- include/jemalloc/internal/extent_externs.h
- include/jemalloc/internal/extent_inlines.h
- include/jemalloc/internal/extent_structs.h
- include/jemalloc/internal/private_symbols.txt
- src/arena.c
- src/base.c
- src/ctl.c
- src/extent.c
- test/unit/base.c
The first two diffs are worthwhile on their own; the second reduces the number of base blocks, and therefore extent structure serial numbers, which makes it feasible to encode the extent serial number in the low bits of the extent size field, under the assumption that the extent size is a multiple of ```PAGE```.  Unfortunately those bits are actually used by the base code for tracking available base block remainders, so we need a union for ```e_size_esn``` and ```e_bsize```.  It's not very pretty, and a bit more brittle than I'd like, but the approach seems sound.  Ideally we'd get some idea as to whether the extent structure reuse policy is important, but it may be hard to get a clear signal, and additionally this optimization may help more once we explicitly use huge pages for base …
> extent_avail

- src/prof.c
This was an attempt to avoid triggering slow path in libunwind, however turns
out to be ineffective.
> Remove the function alignment of prof_backtrace.

- src/extent.c
- src/extent_mmap.c
This avoids creating clean committed pages as a side effect of aligned
allocation.  For configurations that decommit memory, purged pages are
decommitted, and decommitted extents cannot be coalesced with committed
extents.  Unless the clean committed pages happen to be selected during
allocation, they cause unnecessary permanent extent fragmentation.
This resolves #766.
> Trim before commit in extent_recycle().

- include/jemalloc/internal/jemalloc_internal_inlines_a.h
- include/jemalloc/internal/jemalloc_internal_inlines_b.h
- include/jemalloc/internal/jemalloc_internal_inlines_c.h
- src/arena.c
- src/ctl.c
- src/large.c
Tracking extents is required by arena_reset.  To support this, the extent
linkage was used for tracking 1) large allocations, and 2) full slabs.  However
modifying the extent linkage could be an expensive operation as it likely incurs
cache misses.  Since we forbid arena_reset on auto arenas, let's bypass the
linkage operations for auto arenas.
> Bypass extent tracking for auto arenas.

- .travis.yml
- INSTALL
- configure.ac
- doc/jemalloc.xml.in
- include/jemalloc/internal/arena_inlines_a.h
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/jemalloc_internal_inlines_a.h
- include/jemalloc/internal/jemalloc_internal_inlines_b.h
- include/jemalloc/internal/jemalloc_preamble.h.in
- include/jemalloc/internal/tcache_inlines.h
- include/jemalloc/internal/tcache_structs.h
- scripts/gen_run_tests.py
- scripts/gen_travis.py
- src/arena.c
- src/ctl.c
- src/jemalloc.c
- src/stats.c
- src/tcache.c
- test/integration/thread_tcache_enabled.c
- test/test.sh.in
- test/unit/decay.c
- test/unit/decay.sh
- test/unit/mallctl.c
- test/unit/prof_idump.sh
- test/unit/stats.c
Simplify configuration by removing the --disable-tcache option, but
replace the testing for that configuration with
--with-malloc-conf=tcache:false.
Fix the thread.arena and thread.tcache.flush mallctls to work correctly
if tcache is disabled.
> Remove --disable-tcache.

- include/jemalloc/internal/jemalloc_internal_decls.h
- src/pages.c
Some architectures like AArch64 may not have the `open` syscall because it
was superseded by the `openat` syscall, so check and use `SYS_openat` if
`SYS_open` is not available.
Additionally, Android headers for AArch64 define `SYS_open` to `__NR_open`,
even though `__NR_open` is undefined. Undefine `SYS_open` in that case so
`SYS_openat` is used.
> Use openat syscall if available

- INSTALL
- configure.ac
- doc/jemalloc.xml.in
- src/ctl.c
- src/stats.c
- test/unit/mallctl.c
This option is no longer useful, because TLS is correctly configured
automatically on all supported platforms.
> Remove --disable-tls.

- INSTALL
- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/jemalloc_preamble.h.in
- src/jemalloc.c
Continue to use ivsalloc() when --enable-debug is specified (and add
assertions to guard against 0 size), but stop providing a documented
explicit semantics-changing band-aid to dodge undefined behavior in
sallocx() and malloc_usable_size().  ivsalloc() remains compiled in,
unlike when #211 restored --enable-ivsalloc, and if
JEMALLOC_FORCE_IVSALLOC is defined during compilation, sallocx() and
malloc_usable_size() will still use ivsalloc().
> Remove --enable-ivsalloc.

- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/jemalloc_preamble.h.in
- src/jemalloc.c
- src/nstime.c
This can catch bugs in which one header defines a numeric constant, and another
uses it without including the defining header. Undefined preprocessor symbols
expand to '0', so that this will compile fine, silently doing the math wrong.
> Enable -Wundef on platforms where it's supported.

- configure.ac
This fixes a bug/regression introduced by
a01f99307719dcc8ca27cc70f0f0011beff914fa (Only disable munmap(2) by
default on 64-bit Linux.).
> Add missing 'test' to LG_SIZEOF_PTR tests.

- INSTALL
- configure.ac
Four size classes per size doubling has proven to be a universally good
choice for the entire 4.x release series, so there's little point to
preserving this configurability.
> Remove --with-lg-size-class-group.

- INSTALL
- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/jemalloc_internal_macros.h
- include/jemalloc/internal/util.h
The explicit compiler warning suppression controlled by this option is
universally desirable, so remove the ability to disable suppression.
> Remove --disable-cc-silence.

- INSTALL
- configure.ac
- doc/jemalloc.xml.in
- include/jemalloc/internal/arena_structs_b.h
- include/jemalloc/internal/extent_mmap_externs.h
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/jemalloc_preamble.h.in
- src/arena.c
- src/ctl.c
- src/extent.c
- src/extent_mmap.c
- src/jemalloc.c
- src/large.c
- src/stats.c
- test/unit/arena_reset.c
- test/unit/mallctl.c
Control use of munmap(2) via a run-time option rather than a
compile-time option (with the same per platform default).  The old
behavior of --disable-munmap can be achieved with
--with-malloc-conf=munmap:false.
> Replace --disable-munmap with opt.munmap.

- include/jemalloc/internal/tcache_externs.h
- include/jemalloc/internal/tcache_inlines.h
- src/tcache.c
In a production workload, 
```free -> je_tcache_bin_flush_small -> mutex_lock``` and 
```tcache_event_hard -> tcache_bin_flush_small -> mutex_lock``` paths are ranked 2nd and 3rd hottest among all mutex related paths. This change tries to use trylock to make it non-blocking whenever possible, similar to what we did for decay_lock.
> Use trylock in tcache_flush when possible

- include/jemalloc/internal/tcache_inlines.h
This reverts commit b0c2a28280d363fc85aa8b4fdbe7814ef46cb17b.  Production
benchmark shows this caused significant regression in both CPU and memory
consumption.  Will investigate separately later on.
> Revert "Use try_flush first in tcache_dalloc."

- include/jemalloc/internal/tcache_externs.h
- include/jemalloc/internal/tcache_inlines.h
- src/tcache.c
This reverts commit 8584adc451f31adfc4ab8693d9189cf3a7e5d858.  Production
results not favorable.  Will investigate separately.
> Revert "Use trylock in tcache_bin_flush when possible."

- INSTALL
- configure.ac
This simplifies configuration when embedding a jemalloc release into
another project's git repository.
This resolves #811.
> Add --with-version=VERSION .

- include/jemalloc/internal/mutex_prof.h
- include/jemalloc/internal/mutex_types.h
Redeclaration causes compilations failures with e.g. gcc 4.2.1 on
FreeBSD.  This regression was introduced by
89e2d3c12b573310e60b97beaf178007a71d83a3 (Header refactoring: ctl -
unify and remove from catchall.).
> Remove mutex_prof_data_t redeclaration.

- include/jemalloc/internal/jemalloc_internal_decls.h
- src/arena.c
- src/pages.c
This is a backport of PR #779 for the 4.5 branch, so that this change can go into Firefox, which is using jemalloc 4.5.
Some architectures like AArch64 may not have the open syscall because it
was superseded by the openat syscall, so check and use SYS_openat if
SYS_open is not available.
Additionally, Android headers for AArch64 define SYS_open to __NR_open,
even though __NR_open is undefined. Undefine SYS_open in that case so
SYS_openat is used.
> Use openat syscall if available (for 4.5 branch)

- .gitignore
- Makefile.in
Take care not to touch generated namespace mangling headers unless their
contents would change.
This resolves #838.
> Avoid over-rebuilding due to namespace mangling.

- INSTALL.md
- Makefile.in
- doc/jemalloc.xml.in
- include/jemalloc/internal/arena_externs.h
- include/jemalloc/internal/arena_structs_b.h
- include/jemalloc/internal/arena_types.h
- include/jemalloc/internal/ctl.h
- include/jemalloc/internal/jemalloc_internal_decls.h
- src/arena.c
- src/ctl.c
- src/jemalloc.c
- src/stats.c
- test/unit/decay.c
- test/unit/decay.sh
- test/unit/mallctl.c
- test/unit/pack.sh
Support millisecond resolution for decay times.  Among other use cases
this makes it possible to specify a short initial dirty-->muzzy decay
phase, followed by a longer muzzy-->clean decay phase.
This resolves #812.
> Refactor *decay_time into *decay_ms.

- include/jemalloc/internal/arena_structs_b.h
- src/arena.c
When # of dirty pages move below npages_limit (e.g. they are reused), we should
not lower number of unpurged pages because that would cause the reused pages to
be double counted in the backlog (as a result, decay happen slower than it
should).  Instead, set number of unpurged to the greater of current npages and
npages_limit.
Added an assertion: peak # of pages should be greater than npages_limit.
This resolves #813.
> Fix # of unpurged pages in decay algorithm.

- scripts/gen_run_tests.py
Rather than relying on parallel make to build individual configurations
one at a time, use xargs to build multiple configurations in parallel.
This allows the configure scripts to run in parallel.  On a 14-core
system (28 hyperthreads), this increases average CPU utilization from
~20% to ~95%.
> Refactor run_tests to increase parallelism.

- doc/jemalloc.xml.in
- include/jemalloc/internal/stats.h
- src/ctl.c
- src/jemalloc.c
- src/stats.c
The value is passed to atexit(3)-triggered malloc_stats_print() calls.
This resolves #698
> Add opt.stats_print_opts.

- .travis.yml
- include/jemalloc/internal/arena_externs.h
- include/jemalloc/internal/arena_types.h
- include/jemalloc/internal/background_thread_externs.h
- include/jemalloc/internal/background_thread_structs.h
- include/jemalloc/internal/jemalloc_internal_inlines_a.h
- include/jemalloc/internal/jemalloc_internal_inlines_b.h
- scripts/gen_run_tests.py
- scripts/gen_travis.py
- src/arena.c
- src/background_thread.c
- src/ctl.c
- src/jemalloc.c
- src/mutex.c
- test/unit/junk.c
- test/unit/mallctl.c
Add testing for background_thread:true, and condition a xallocx() -->
rallocx() escalation assertion to allow for spurious in-place rallocx()
following xallocx() failure.
> Test with background_thread:true.

- src/extent.c
It's possible to customize the extent_hooks while still using part of the
default implementation.
> Remove assertions on extent_hooks being default.

- include/jemalloc/internal/tsd.h
- src/jemalloc.c
- src/tsd.c
- test/unit/tsd.c
Since tsd cleanup isn't guaranteed when reincarnated, we set up tsd in a way
that needs no cleanup, by making it going through slow path instead.
> Make tsd no-cleanup during tsd reincarnation.

- include/jemalloc/internal/tsd.h
Pre-C11 compilers do not support typedef redefinition.
> Remove redundant typedefs.

- src/extent.c
- test/integration/extent.c
Fix extent_hooks in extent_grow_retained().
This issue caused the default extent alloc function to be incorrectly
used even when ```arena.<i>.extent_hooks``` is set.  This bug was introduced
by 411697adcda2fd75e135cdcdafb95f2bd295dc7f (Use exponential series to
size extents.), which was first released in 5.0.0.
> Fix extent_hooks in extent_grow_retained().

- include/jemalloc/internal/background_thread_externs.h
- src/background_thread.c
- src/ctl.c
If neither background_thread nor lazy_lock is in use, do not abort on dlsym
errors.
Part of the solution to #907.
> Only abort on dlsym when necessary.

- src/arena.c
During purging, we may unlock decay->mtx.  Therefore we should finish logging
decay related counters before attempt to purge.
This resolves #891.
> Log decay->nunpurged before purging.

- include/jemalloc/internal/tcache_externs.h
- include/jemalloc/internal/tsd.h
- src/ctl.c
- src/jemalloc.c
- src/tcache.c
- src/tsd.c
We use the minimal_initilized tsd (which requires no cleanup) for free()
specifically, if tsd hasn't been initialized yet.
Any other activity will transit the state from minimal to normal.  This is to
workaround the case where a thread has no malloc calls in its lifetime until
during thread termination, free() happens after tls destructors.
> Add minimal initialized TSD

- include/jemalloc/internal/jemalloc_internal_decls.h
- src/background_thread.c
This prevents signals from being inadvertently delivered to background
threads.
> Mask signals during background thread creation.

- include/jemalloc/internal/background_thread_inlines.h
- src/arena.c
Passing is_background_thread down the decay path, so that background thread
itself won't attempt inactivity_check.  This fixes an issue with background
thread doing trylock on a mutex it already owns.
> Avoid inactivity_check within background threads.

- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- src/background_thread.c
Since there are a few variants of pthread_setname_np (w/ different # of arguments), I used a compilable check for it.
This resolves #922
> Add thread name for background threads.

- include/jemalloc/internal/base_externs.h
- include/jemalloc/internal/ctl.h
- include/jemalloc/internal/jemalloc_internal_inlines_a.h
- src/arena.c
- src/background_thread.c
- src/base.c
- src/ctl.c
- src/extent.c
- src/jemalloc.c
- src/prof.c
- test/unit/base.c
Customized extent hooks may malloc / free thus trigger reentry.  Support this
behavior by adding reentrancy on hook functions.
This resolves #923.
> Set reentrancy when invoking customized extent hooks.

- configure.ac
> Enforce minimum autoconf version (currently 2.68).

- include/jemalloc/internal/arena_externs.h
- src/arena.c
- src/jemalloc.c
This fixed the issue that could cause the child process to stuck after fork.
> Add extent_grow_mtx in pre_ / post_fork handlers.

- src/pages.c
- src/prof.c
We should check the fd before calling `fcntl` on it
> Validates fd before calling fcntl

- configure.ac
- include/jemalloc/internal/jemalloc_internal_macros.h
- include/jemalloc/internal/log.h
- include/jemalloc/internal/malloc_io.h
- src/jemalloc.c
- src/log.c
- test/unit/log.c
Currently, the log macro requires at least one argument after the format string,
because of the way the preprocessor handles varargs macros.  I realized that we
can eliminate this requirement by splitting up some of our formatting calls.
> Logging: allow logging with empty varargs.

- include/jemalloc/internal/log.h
- src/jemalloc.c
- test/unit/log.c
Currently we have to log by writing something like:
static log_var_t log_a_b_c = LOG_VAR_INIT("a.b.c");
log (log_a_b_c, "msg");
This is sort of annoying.  Let's just write:
log("a.b.c", "msg");
> Logging: log using the log var names directly.

- test/integration/sdallocx.c
This is a temporary workaround until we add some beefier CI machines.  Right
now, we're seeing too many OOMs for this to be useful.
> Only run test/integration/sdallocx non-reentrantly.

- src/extent.c
When retain is enabled, we should not attempt mmap for in-place expansion
(large_ralloc_no_move), because it's virtually impossible to succeed, and causes
unnecessary syscalls (which can cause lock contention under load).
> Bypass extent_alloc_wrapper_hard for no_move_expand.

- Makefile.in
- include/jemalloc/internal/spin.h
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
- src/spin.c
The external linkage for spin_adaptive was not used, and the inline
declaration of spin_adaptive that was used caused a probem on FreeBSD
where CPU_SPINWAIT is implemented as a call to a static procedure for
x86 architectures.
A little more explanation:
On FreeBSD, CPU_SPINWAIT is defined as cpu_spinwait(), which for amd64
and i386 is in turn defined as ia32_pause, which is declared as static
inline.
The problem is, the C standard says that inline non-static procedures
(e.g. spin_adaptive) are not allowed to call static procedures (e.g.
ia32_pause) (ISO/IEC 9899:201x 6.7.4,
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf).
At some point gcc started emitting a warning for this.  FreeBSD is now
using clang by default but I have been trying to get the amd64/gcc build
functional …
> Remove external linkage for spin_adaptive

- configure.ac
- doc/jemalloc.xml.in
- include/jemalloc/internal/base_externs.h
- include/jemalloc/internal/base_types.h
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/pages.h
- src/base.c
- src/ctl.c
- src/jemalloc.c
- src/pages.c
- src/stats.c
- test/unit/mallctl.c
This option enables transparent huge page for base allocators (require
MADV_HUGEPAGE support).
> Implement opt.metadata_thp

- include/jemalloc/internal/jemalloc_preamble.h.in
- src/pages.c
- test/unit/pages.c
As part of the metadata_thp support, We now have a separate swtich
(JEMALLOC_HAVE_MADVISE_HUGE) for MADV_HUGEPAGE availability.  Use that instead
of JEMALLOC_THP (which doesn't guard pages_huge anymore) in tests.
> Fix test/unit/pages

- configure.ac
- include/jemalloc/internal/jemalloc_internal_types.h
- GNU/kFreeBSD support is broken as far as I can tell, by assuming that because the system runs glibc, it also has some features that are Linux-only. Workaround that by creating a new kFreeBSD entry, that enables the combination of features that glibc + kFreeBSD have. The right fix would probably be to split the `$host` case to two, one of which matching the kernel, and another one the libc, but that's way over my head :)
- A few Debian porters have submitted bug reports for (still unofficial) ports they're building, with the lg quantum size that is required for their architecture, and this just incorporates them upstream.
> Couple of portability fixes

- test/unit/mallctl.c
The abort_conf option was missed from test/unit/mallctl.
> Add missing mallctl unit test for abort_conf.

- doc/jemalloc.xml.in
- include/jemalloc/internal/base_externs.h
- include/jemalloc/internal/base_inlines.h
- include/jemalloc/internal/base_structs.h
- include/jemalloc/internal/base_types.h
- include/jemalloc/internal/ctl.h
- include/jemalloc/internal/stats.h
- src/arena.c
- src/base.c
- src/ctl.c
- src/jemalloc.c
- src/pages.c
- src/stats.c
- test/unit/base.c
- test/unit/mallctl.c
To avoid the high RSS caused by THP + low usage arena (i.e. THP becomes a
significant percentage), added a new "auto" option which will only start using
THP after a base allocator used up the first THP region.  Starting from the
second hugepage (in a single arena), "auto" behaves the same as "always",
i.e. madvise hugepage right away.
> Change opt.metadata_thp to [disabled,auto,always].

- include/jemalloc/internal/jemalloc_internal_inlines_a.h
- src/extent.c
If we guarantee no malloc activity in extent hooks, it's possible to make
customized hooks working on arena 0.  Remove the non-a0 assertion to enable such
use cases.
> Relax constraints on reentrancy for extent hooks.

- test/unit/pages.c
Huge pages could be disabled even if the kernel header has MAD_HUGEPAGE
defined.  Guard the huge pagetest with runtime detection.
> Fix huge page test in test/unit/pages.

- .travis.yml
We've been seeing strange errors in jemalloc_cpp.cpp since Travis upgraded from
precise to trusty as their default CI environment (seeming to stem from some
the new clang version finding the headers for an old version of libstdc++.  In
the long run we'll have to deal with this "for real", but at that point we may
have a better C++ story in general, making it a moot point.
> Force Ubuntu "precise" for Travis CI builds.

- include/jemalloc/internal/log.h
- src/jemalloc.c
- test/unit/log.c
Dodge a name-conflict with the math.h logarithm function. D'oh.
> Logging: capitalize log macro.

- include/jemalloc/internal/extent_externs.h
- include/jemalloc/internal/extent_structs.h
- src/extent.c
As far as I can tell, there does not seem to be any overlap between usage of
extent_avail and extent_heap, so we can use the same hook.
The only remaining usage of rb trees is in the profiling code,
which has some 'interesting' iteration constraints.
Fixes #888
> Use ph instead of rb tree for extents_avail_

- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/spin.h
- src/mutex.c
Quoting from https://github.com/jemalloc/jemalloc/issues/761 :
[...] reading the Power ISA documentation[1], the assembly in [the CPU_SPINWAIT
macro] isn't correct anyway (as @marxin points out): the setting of the
program-priority register is "sticky", and we never undo the lowering.
We could do something similar, but given that we don't have testing here in the
first place, I'm inclined to simply not try. I'll put something up reverting the
problematic commit tomorrow.
[1] Book II, chapter 3 of the 2.07B or 3.0B ISA documents.
> Power: disable the CPU_SPINWAIT macro.

- src/background_thread.c
- src/jemalloc.c
This makes background thread init making more progress, or avoids potential problems.
> Fix a couple of background thread init related issues

- configure.ac
- include/jemalloc/internal/extent_inlines.h
- include/jemalloc/internal/extent_structs.h
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/pages.h
- src/extent.c
- src/extent_dss.c
- src/pages.c
- test/unit/rtree.c
- test/unit/slab.c
These commits add support for setting regions of the address space undumpable (on supported platforms).
Currently, this isn't "plugged-in" anywhere; nothing makes pages undumpable. However, this support is required in order to implement some of the subsequent large-address-space ideas we have.
Along the way, I added some extent refactoring / documentation.
> Extent refactoring and dumpability metadata

- src/stats.c
The saved space is not worth the trouble of missing counters.
> Output all counters for bin mutex stats.

- include/jemalloc/internal/base_types.h
- src/base.c
We observed that arena 0 can have much more metadata allocated comparing to
other arenas.  Tune the auto mode to only switch to huge page on the 5th block
(instead of 3 previously) for a0.
> metadata_thp: auto mode adjustment for a0.

- src/pages.c
The purpose of those commits is to do one sysctl(2) syscall during binary startup instead of current three.
> FreeBSD binary startup improvements

- doc/jemalloc.xml.in
- include/jemalloc/internal/arena_externs.h
- include/jemalloc/internal/arena_structs_b.h
- include/jemalloc/internal/extent_types.h
- src/arena.c
- src/ctl.c
- src/extent.c
- test/unit/mallctl.c
This option controls the max size when grow_retained.  This is useful when we
have customized extent hooks reserving physical memory (e.g. 1G huge pages).
Without this feature, the default increasing sequence could result in fragmented
and wasted physical memory.
> Add arena.i.retain_grow_limit

- src/base.c
This gives us an easier way to tell if the allocation is for metadata in the
extent hooks.
> Use hugepage alignment for base allocator.

- include/jemalloc/internal/extent_externs.h
- src/arena.c
- src/extent.c
Added an upper bound on how many pages we can decay during the current run.
Without this, decay could have unbounded increase in stashed, since other
threads could add new pages into the extents.
> Fix unbounded increase in stash_decayed.

- doc/jemalloc.xml.in
- include/jemalloc/internal/extent_externs.h
- include/jemalloc/internal/extent_inlines.h
- include/jemalloc/internal/extent_types.h
- src/ctl.c
- src/extent.c
- src/jemalloc.c
- test/unit/mallctl.c
When allocating from dirty extents (which we always prefer if available), large
active extents can get split even if the new allocation is much smaller, in
which case the introduced fragmentation causes high long term damage.  This new
option controls the threshold to reuse and split an existing active extent.  We
avoid using a large extent for much smaller sizes, in order to reduce
fragmentation.  In some workload, adding the threshold improves virtual memory
usage by >10x.
> Add opt.lg_extent_max_active_fit

- src/extent.c
This fixes an regression introduced by 211b1f3 (refactor extent split).
> Add missing deregister before extents_leak.

- src/extent.c
- test/include/test/extent_hooks.h
- test/integration/extent.c
Added test case for 26a8f8. The test only succeeds after that diff.
> Add more tests for extent hooks failure paths.

- src/extent.c
- test/integration/extent.c
Should only run the hook tests without background threads.  This was introduced
in 6e841f6.
> Fix test/integration/extent.

- include/jemalloc/internal/jemalloc_internal_types.h
According to the RISC-V toolchain conventions, `__riscv__` is the old spelling of this definition. `__riscv` should be used going forward.
https://github.com/riscv/riscv-toolchain-conventions#cc-preprocessor-definitions
> Correct the spelling of __riscv.

- include/jemalloc/jemalloc_mangle.sh
Set sh in "strict mode" in `jemalloc_mangle.sh`.
I've had a [TensorFlow](https://github.com/tensorflow/tensorflow/blob/master/third_party/jemalloc.BUILD) build fail in weird ways because the sysroot did not have `awk` installed. It would have been nice if the script failed right away instead of producing a malformed header.
> jemalloc_mangle.sh: set sh in strict mode

- test/unit/pack.c
The test assumes no sampled allocations.
> Skip test/unit/pack when profiling is enabled.

- include/jemalloc/internal/extent_externs.h
- src/arena.c
- src/extent.c
When purging, large allocations are usually the ones that cross the npages_limit
threshold, simply because they are "large".  This means we often leave the large
extent around for a while, which has the downsides of: 1) high RSS and 2) more
chance of them getting fragmented.  Given that they are not likely to be reused
very soon (LRU), let's over purge by 1 extent (which is often large and not
reused frequently).
> Over purge by 1 extent always.

- Makefile.in
- include/jemalloc/internal/div.h
- src/arena.c
- src/div.c
- src/sz.c
- test/unit/div.c
These commits implement a dynamic version of the fast division-by-constants trick. Thanks to some knowledge we have that the compiler doesn't, we can actually get a slightly faster implementation (no dynamic shifting, no subtractions, and only ever one shift), avoiding an indirect jump and a couple of arithmetic operations, and cutting down the size of `arena_slab_regind` from around 860 bytes to around 31 (on x86).
A slow path test of running test/unit/stress with MALLOC_CONF=tcache:false showed about a 2% improvement on my machine.
> Don't hardcode regind divisors.

- include/jemalloc/internal/mutex_prof.h
- src/stats.c
This fixes #1063 , where we are separating 64 bit and 32 bit mutex stats counters.  During read, we read them in their respective types.
> handle 32 bit mutex counters

- configure.ac
As mentioned in #1045, the macro should be disabled for arm*.
Unfortunately the patch as is can't be backported to 5.0.x release.
> Disable JEMALLOC_HAVE_MADVISE_HUGE for arm* CPUs.

- include/jemalloc/internal/jemalloc_internal_inlines_c.h
Commit 323b346 fixes an reentrancy case: arena N (manually created) hold retained_grow_mtx => calling user defined alloc_hook => in the user hook, calling malloc() => using arena0 to fulfill the allocation. This works fine but the assertion in the last step is triggered. Since we are holding other arena's mutex, it won't cause issues.
Commit 268bb39 fixes #1078. @davidtgoldblatt I'll leave the adding API tests part to you.
> Fix two assertions

- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- src/malloc_io.c
On glibc and Android's bionic, strerror_r returns char* when
_GNU_SOURCE is defined.
Add a configure check for this rather than assume glibc is the
only libc that behaves this way.
(This resolves #1028. Sorry @cferris1000 for the long delay).
> Modify configure to determine return value of strerror_r.

- include/jemalloc/internal/ticker.h
GCC on its own isn't quite able to turn the ticker subtract into a memory
operation followed by a js.
It's hard to reliably measure things that small, but it looks to be about a 0.2% end-to-end improvement.
> Tweak the ticker paths to help GCC generate better code.

- Makefile.in
- src/background_thread.c
- test/unit/background_thread_enable.c
We have a buffer overrun that manifests in the case where arena indices higher
than the number of CPUs are accessed before arena indices lower than the number
of CPUs.  This fixes the bug and adds a test.
> Background threads: fix an indexing bug.

- test/integration/mallocx.c
- test/integration/thread_tcache_enabled.c
test_alignment_and_size needs a lot of memory.  When percpu_arena is enabled,
multiple arenas may cause the test to OOM.
This resolves #1105.
> Skip test_alignment_and_size if percpu_arena is enabled.

- configure.ac
- doc/jemalloc.xml.in
- include/jemalloc/internal/jemalloc_preamble.h.in
- include/jemalloc/internal/pages.h
- src/base.c
- src/ctl.c
- src/extent.c
- src/jemalloc.c
- src/pages.c
- src/stats.c
- test/unit/mallctl.c
- test/unit/pages.c
"always" marks all user mappings as MADV_HUGEPAGE; while "never" marks all
mappings as MADV_NOHUGEPAGE. The default setting "default" does not change any
settings.  Note that all the madvise calls are part of the default extent hooks
by design, so that customized extent hooks have complete control over the
mappings including hugepage settings.
This resolves #1127
> Add opt.thp which allows explicit hugepage usage.

- Makefile.in
- include/jemalloc/internal/emitter.h
- include/jemalloc/internal/mutex_prof.h
- src/stats.c
- test/unit/emitter.c
We introduce the emitter module, which mostly transparently handles the differences of the human-readable and json output modes. Gone are the days of manually indenting every json field, or manually aligning table rows with their fields, or any of the other reasons why it's super annoying to deal with the stats code.
The actual LOC-level savings in stats.c understate the improvement, since many of the newly added lines are much easier to read than their pre-conversion equivalents. The emitter itself is tested as well, so that it's harder to accidentally introduce incorrect json or misaligned tables.
> Convert stats printing to use a structured text emitter

- include/jemalloc/internal/malloc_io.h
- src/malloc_io.c
- src/pages.c
- src/prof.c
- test/integration/mallocx.c
- test/unit/mallctl.c
- test/unit/stats_print.c
Fix ```warning C4267: 'function': conversion from 'size_t' to 'unsigned int'``` and ```warning C4090: 'function': different 'const' qualifiers```.
This resolves #1142.
> Fix some warnings on Windows.

- src/mutex.c
> Stack address should not be used for ordering mutexes

- include/jemalloc/internal/rtree.h
@davidtgoldblatt noticed that two memory loads of the same location was generated on the free() fast path. Let's do a bit of manual work to avoid that (u-benchmark shows ~1% improvement).
Commit message:
szind and slab bits are read on fast path, where compiler generated two memory
loads separately for them before this diff.  Manually operate on the bits to
avoid the extra memory load.
> Consolidate the two memory loads in rtree_szind_slab_read().

- doc/jemalloc.xml.in
- include/jemalloc/internal/background_thread_externs.h
- include/jemalloc/internal/background_thread_structs.h
- src/background_thread.c
- src/ctl.c
- src/jemalloc.c
- test/unit/background_thread_enable.c
Looking at the thread counts in our services, jemalloc's background thread is useful, but mostly idle.  Add a config option to tune down the number of threads.
> background_thread: add max thread count config

- doc/jemalloc.xml.in
> Document liveness requirements for extent_hooks_t structures.

- include/jemalloc/internal/emitter.h
This dodges a warning emitted by the FreeBSD system gcc when compiling
libc for architectures which don't use clang as the system compiler.
> Avoid a printf format specifier warning.

- src/background_thread.c
Background threads are created without holding the global background_thread
lock, which mean paused state is possible (and fine).
This resolves #1183.
> Remove an incorrect assertion.

- configure.ac
Instead of setting a fix value of 48 allowed VA bits,
we distiguish between LP64 and ILP32.
Testsuite result with LP64:
Test suite summary: pass: 13/13, skip: 0/13, fail: 0/13
Testsuit result with ILP32:
Test suite summary: pass: 13/13, skip: 0/13, fail: 0/13
Signed-off-by: Christoph Muellner <christoph.muellner@theobroma-systems.com>
Reviewed-by: Philipp Tomsich <philipp.tomsich@theobroma-systems.com>
> aarch64: Add ILP32 support.

- doc/jemalloc.xml.in
- src/ctl.c
- test/unit/mallctl.c
I am working on a project that uses arenas (and custom extent hooks) to support multiple memory types (for example High Bandwidth Memory, GPU memory, etc.). For some of the operations required, I need a way to find out which arena a given pointer belongs to. This patch implements the functionality.
> New mallctl operation that allows looking up the arena for a pointer.

- INSTALL.md
- configure.ac
This patch allows to override the lg-vaddr values, which
are defined by the build machine's CPUID information (x86_64)
or default values (other architectures like aarch64).
Signed-off-by: Christoph Muellner <christoph.muellner@theobroma-systems.com>
> configure: Add --with-lg-vaddr configure option.

- Makefile.in
When configuring out-of-tree (source directory is not build directory),
the generated include files from the build directory should have higher
priority than those in the source dir.
This is especially helpful when cross-compiling.
Signed-off-by: Christoph Muellner <christoph.muellner@theobroma-systems.com>
> Fix include path order for out-of-tree builds.

- src/pages.c
When configured with --with-lg-page, it's possible for the configured page size to be
greater than the system page size, in which case the page address may only be
aligned with the system page size.
> Fix an incorrect assertion.

- test/unit/background_thread_enable.c
We may set number of background threads separately, e.g. through
--with-malloc-conf, so avoid assuming the default number.
> Fix the max_background_thread test.

- src/stats.c
Apparently lg_extent_max_active_fit was missing in the stats.
> Fix stats output for opt.lg_extent_max_active_fit.

- src/large.c
- src/tcache.c
On tcache flush path, we can avoid touching the large_mtx for auto arenas, since
it was only needed for manual arenas where arena_reset is allowed.
> Avoid taking large_mtx for auto arenas.

- include/jemalloc/internal/tcache_structs.h
- include/jemalloc/internal/tsd.h
- src/hook.c
- src/tsd.c
This can lead to better cache utilization down the common paths where we don't
touch the link.
> Move tsd link and in_hook after tcache.

- include/jemalloc/internal/background_thread_externs.h
- src/background_thread.c
- src/ctl.c
This should solve the link order issue as reported in #907.
> Fall back to the default pthread_create if RTLD_NEXT fails.

- Makefile.in
- doc/jemalloc.xml.in
- include/jemalloc/internal/arena_externs.h
- include/jemalloc/internal/arena_inlines_b.h
- include/jemalloc/internal/arena_types.h
- include/jemalloc/internal/jemalloc_internal_externs.h
- include/jemalloc/internal/jemalloc_internal_inlines_b.h
- src/arena.c
- src/ctl.c
- src/jemalloc.c
- src/large.c
- src/stats.c
- test/unit/huge.c
- test/unit/mallctl.c
The feature allows using a dedicated arena for huge allocations.  We want the
addtional arena to separate huge allocation because: 1) mixing small extents
with huge ones causes fragmentation over the long run (this feature reduces VM
size significantly); 2) with many arenas, huge extents rarely get reused across
threads; and 3) huge allocations happen way less frequently, therefore no
concerns for lock contention.
> Implement huge arena: opt.huge_threshold. 

- include/jemalloc/internal/jemalloc_internal_macros.h
The `-Wmissing-field-initializer` warning is buggy for GCC < 5.1 and all clang versions (up to clang 7 trunk). This PR suppresses the warning only for the affected compilers, instead of for all GCC versions.
> Suppress -Wmissing-field-initializer warning for buggy compilers only

- src/jemalloc.c
Not aborting with unrecognized experimental options.  This helps us testing
experimental features with abort_conf enabled.
> Tolerate experimental features for abort_conf.

- include/jemalloc/internal/arena_externs.h
- include/jemalloc/internal/extent_structs.h
- include/jemalloc/internal/sc.h
- include/jemalloc/internal/sz.h
- src/arena.c
- src/base.c
- src/extent.c
- src/jemalloc.c
- src/sc.c
- src/sz.c
- test/unit/junk.c
- test/unit/mallctl.c
- test/unit/prof_gdump.c
- test/unit/size_classes.c
- test/unit/stats.c
- test/unit/zero.c
The global data is mostly only used at initialization, or for easy access to
values we could compute statically.  Instead of consuming that space (and
risking TLB misses), we can just pass around a pointer to stack data during
bootstrapping.
> SC: Remove global data.

- include/jemalloc/internal/tsd.h
- src/jemalloc.c
- src/tsd.c
Technically this is disallowed, but it's not difficult for us to work around.
> Fix TSD breakage after multithreaded fork

- doc/jemalloc.xml.in
- include/jemalloc/internal/arena_externs.h
- include/jemalloc/internal/arena_stats.h
- include/jemalloc/internal/arena_structs_b.h
- include/jemalloc/internal/ctl.h
- include/jemalloc/internal/extent_externs.h
- include/jemalloc/internal/extent_structs.h
- include/jemalloc/internal/sc.h
- include/jemalloc/internal/stats.h
- src/arena.c
- src/ctl.c
- src/extent.c
- src/stats.c
Outputs a rough breakdown of sizes for each type of extent (dirty, muzzy, retained). Also add a counter for the `extent_avail` heap in each arena.
Here's an example output:
```
extents:        size ind       ndirty        dirty       nmuzzy        muzzy    nretained     retained       ntotal        total
4096   0         3769     15437824            4        16384            0            0         3773     15454208
8192   1          164      1343488            0            0            0            0          164      1343488
12288   2          106      1302528            0            0            1        12288          107      1314816
16384   3            3        49152            0            0            0            0            3        49152
20480   4            8       163840 …
```
> Add extents stats to malloc stats output

- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- src/jemalloc.c
This can be useful in situations where readlink is disallowed.
> Allow the use of readlinkat over readlink.

- Makefile.in
- test/stress/hookbench.c
On my machine, it shows around a 40ns overhead to execute a hook.
> Add hook microbenchmark.

- .travis.yml
- scripts/gen_travis.py
This commit adds two build-bots to CI that test the release builds
of jemalloc on linux and macOS under valgrind.
The macOS build bot is allowed to fail because valgrind reports
errors about reads of uninitialized memory, and in some cases,
segfaults.
> Add valgrind build bots to CI

- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj.filters
This fixes the MSVC build error due to the missing source file sc.c.
> Add sc.c to the MSVC project

- src/pages.c
The "O_FIXED | MAP_EXCL" combination works just like MAP_FIXED_NOREPLACE
recently introduced in Linux - except it's for FreeBSD and was added
some four years ago.
> Make use of MAP_EXCL on FreeBSD.

- include/jemalloc/internal/tsd_malloc_thread_cleanup.h
- include/jemalloc/internal/tsd_tls.h
- src/jemalloc.c
- src/tsd.c
Move malloc_init() off of the fast path in imalloc(). If tsd can't allocate, then it is safe to check the tsd_state (which will be uninitialized the first time), and then only do the malloc_init() check on the slowpath.   
This appears to pass our internal testing, but I'm not sure this is enough for freebsd libc.
> Remove malloc_init() off the fastpath

- Makefile.in
- include/jemalloc/internal/arena_inlines_b.h
- include/jemalloc/internal/jemalloc_internal_inlines_c.h
- include/jemalloc/internal/sz.h
- src/jemalloc.c
- src/sz.c
- test/integration/aligned_alloc.c
- test/integration/malloc.c
Roll the size-0 check in to the size class lookup table (or slower compute path).  This removes a branch from the fastpath if we are using the table (and has the same number of branches if using _compute()).
> Zero size class

- include/jemalloc/internal/ticker.h
- src/jemalloc.c
This diff adds a fastpath that assumes size <= SC_LOOKUP_MAXCLASS, and that we hit tcache.  If either of these is false, we fall back to the previous codepath (renamed 'malloc_default').
Crucially, we only tail call malloc_default, and with the same kind and number of arguments, so that both clang and gcc tail-calling will kick in - therefore malloc() gets treated as a leaf function, and there are *no* caller-saved registers.   Previously malloc() contained 5 caller saved registers on x64, resulting in at least 10 extra memory-movement instructions.
In microbenchmarks this results in up to ~10% improvement in malloc() fastpath.  In real programs, this is a ~1% CPU and latency improvement overall.
Fastpath now looks like this:
https://gist.github.com/djwatson/f2d8d9993f5736c74c280941bb67c0c …
> malloc: Add a fastpath

- include/jemalloc/internal/atomic_gcc_sync.h
Nearly all 32-bit powerpc hardware treats lwsync as sync, and some cores
(Freescale e500) trap lwsync as an illegal instruction, which then gets
emulated in the kernel.  To avoid unnecessary traps on the e500, use
sync on all 32-bit powerpc.  This pessimizes 32-bit software running on
64-bit hardware, but those numbers should be slim.
> Restrict lwsync to powerpc64 only

- src/pages.c
When overcommit is enabled, commit needs to be set when doing mmap().  The
regression was introduced in f80c97e.
This solves #1350
> Set commit properly for FreeBSD w/ overcommit.

- src/pages.c
It was removed in 0771ff2cea6dc18fcd3f6bf452b4224a4e17ae38.
Add a comment explaining its purpose.
> Restore a FreeBSD-specific getpagesize(3) optimization.

- include/jemalloc/internal/cache_bin.h
- include/jemalloc/internal/rtree.h
- include/jemalloc/internal/tcache_inlines.h
- src/jemalloc.c
Add unsized and sized deallocation fastpaths.  Similar to the malloc() fastpath, this removes all frame manipulation for the majority of free() calls.  The fastpath must hit the rtree cache, or be a sized dalloc.  Profiled objects go to the slowpath.
> Add a fastpath for free and sdallocx

- src/extent.c
We may have a large number of pages with *zero set (since they are populated on
demand).  Only check the first page to avoid paging in all of them.
> Avoid touching all pages in extent_recycle for debug build.

- configure.ac
- include/jemalloc/internal/bit_util.h
- include/jemalloc/internal/extent_inlines.h
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- src/arena.c
This patchset optimizes arena_tcache_fill_small(), for the cases where more than one item is requested from the same slab.  This should be fairly common.  The case of only a single item fill should be fairly neutral.
The batch fill portion is refactored to a separate function, and the linear scan of the bitmap_t's is merged with the fill itself (it's unclear to me if this might better fit in bitmap.h instead, since it needs parts of both arena and bitmap logic).  We use popcount() and bmi (bit manipulation instruction set) when available.
In a microbenchmark, this diff changes the perf overhead of arena_tcache_fill_small from a high of 12% down to 3-4%.   In real world canaries, this shows up as a 1% latency improvement.
> Optimize arena_tcache_fill_small

- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/jemalloc_preamble.h.in
- include/jemalloc/internal/mutex.h
- src/mutex.c
- test/include/test/jemalloc_test.h.in
- test/include/test/mtx.h
- test/src/mtx.c
OSSpinLock is deprecated and we have os_unfair_lock support for Mac.
This solves #843
> Deprecate OSSpinLock

- include/jemalloc/internal/mutex.h
- src/mutex.c
If there are 3 or more threads spin-waiting on the same mutex,
there will be excessive exclusive cacheline contention because
pthread_trylock() immediately tries to CAS in a new value, instead
of first checking if the lock is locked.
This diff adds a 'locked' hint flag, and we will only spin wait
without trylock()ing while set.  I don't know of any other portable
way to get the same behavior as pthread_mutex_lock().
This is pretty easy to test via ttest, e.g.
./ttest1 500 3 10000 1 100
Throughput is nearly 3x as fast.
This blames to the mutex profiling changes, however, we almost never
have 3 or more threads contending in properly configured production
workloads, but still worth fixing.
> mutex: fix trylock spin wait contention

- src/tcache.c
With sharded bins, we may not flush all items from the same arena in one run.
Adjust the stats merging logic accordingly.
The regression was introduced in #1378.
> Fix incorrect stats mreging with sharded bins.

- include/jemalloc/internal/extent_inlines.h
- src/tcache.c
Add exten_arena_ind_get() to avoid loading the actual arena ptr in case we just
need to check arena matching.
> Only read arena index from extent on the tcache flush path.

- Makefile.in
- configure.ac
My distro (NixOS) offers a custom toolchain where it's not possible to make static libs, so it's insufficient to just delete the libs I don't want. I actually need to avoid building them in the first place.
CC @vaibhavsagar @matthewbauer
> Add --{enable,disable}-{static,shared} to configure script

- include/jemalloc/internal/jemalloc_internal_inlines_a.h
- include/jemalloc/internal/jemalloc_preamble.h.in
The only note is that this doesn't support multiple processor groups, but so does the ncpu on windows (will do another PR for it)
> implement malloc_getcpu for windows

- Makefile.in
- configure.ac
This automatically adds -latomic if and when needed, e.g. on riscv64
systems.
Fixes #1401.
> Replace -lpthread with -pthread

- .cirrus.yml
This configures Cirrus CI's test runner (original at https://github.com/lwhsu/jemalloc/commit/e10935ffd2047eb1e23c13a1586990dcfc6ad9f0) to test on FreeBSD.  I've already enabled Cirrus CI on  https://github.com/jemalloc/jemalloc, so this pull request should trigger test runs.
> Add Cirrus-CI config for FreeBSD builds

- .cirrus.yml
The --branch parameter is unnecessary, and may avoid problems when
testing directly on the dev branch.
> Remove --branch=${CIRRUS_BASE_BRANCH} in git clone command.

- src/tcache.c
We can rely on bg thds instead of force purging everything on thread exit.
> Force purge on thread death only when w/o bg thds.

- include/jemalloc/internal/arena_inlines_b.h
- src/extent.c
When custom extent_hooks or transparent huge pages are in use, the purging
semantics may change, which means we may not get zeroed pages on repopulating.
Fixing the issue by manually memset for such cases.
> Avoid potential issues on extent zero-out.

- include/jemalloc/internal/arena_externs.h
- src/arena.c
- src/background_thread.c
- src/ctl.c
- src/jemalloc.c
For low arena count settings, the huge threshold feature may trigger an unwanted
bg thd creation.  Given that the huge arena does eager purging by default,
bypass bg thd creation when initializing the huge arena.
> Avoid creating bg thds for huge arena lone.

- src/stats.c
The rate calculation for the total row was missing.
First introduced in 36de518.
> Fix stats output (rate for total # of requests).

- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- src/tcache.c
This adds some overhead to the tcache flush path (which is one of the
popular paths).  Guard it behind a config option.
> Sanity check szind on tcache flush.

- include/jemalloc/internal/arena_types.h
I'm going to do more validation here. So far the consensus seem to say that the 10s muzzy decay is on the aggressive side. We do have a few use cases enabling it explicitly got desired tradeoffs, but given that we don't have a good story on getting accurate RSS accounting with MADV_FREE, and being able to track memory regression is also very valuable, we may want it to be turned off by default in the next release.
> Disable muzzy decay by default.

- Makefile.in
- configure.ac
However, skip building the docs (and output warnings) if XML support is missing.
This allows `make install` to succeed w/o `xsltproc` and `make dist`.
I made sure this works for both release tarballs and git clones; when missing `xsltproc` -- for tarballs with prebuilt docs, output warnings; for git checkout w/o prebuilt doc, print warnings and output the msg into the doc files, and allow make install to succeed.
This should save some trouble for users w/ no `xsltproc` installed.
This replaces #1212.
> Add build_doc by default.

- include/jemalloc/internal/tcache_structs.h
This fixes a build failure when integrating with FreeBSD's libc.  This
regression was introduced by d1e11d48d4c706e17ef3508e2ddb910f109b779f
(Move tsd link and in_hook after tcache.).
> Avoid redefining tsd_t.

- src/prof.c
Only triggers libgcc unwind init when prof is enabled.  This helps workaround
some bootstrapping issues.
> Guard libgcc unwind init with opt_prof.

- src/tsd.c
Proposed fix for #1444 - ensure that `tls_callback` in the `#pragma comment(linker)`directive gets the same prefix added as it does i the C declaration.
> Stringify tls_callback linker directive

- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
These macros have been unused since
d4ac7582f32f506d5203bea2f0115076202add38 (Introduce a backport of C11
atomics).
> Remove JE_FORCE_SYNC_COMPARE_AND_SWAP_[48].

- configure.ac
Introduced in e13400c919e6b6730284ff011875bbcdd6821f1c.
> Fix a syntax error in configure.ac

- include/jemalloc/internal/jemalloc_internal_macros.h
This regression was introduced by
3d29d11ac2c1583b9959f73c0548545018d31c8a (Clean compilation -Wextra).
The functional change is at line 60 (cleaning up while I'm here).
> Do not use #pragma GCC diagnostic with gcc < 4.6.

- configure.ac
- include/jemalloc/internal/atomic.h
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/tsd.h
- src/tsd.c
Detect if 8-bit atomics are available.  In some rare cases (older compiler, e.g. gcc 4.2 w/ MIPS), 8-bit atomics might be unavailable.  Detect such cases and fallback to 32bit instead.
> Workaround when  8-bit atomics are unavailable

- include/jemalloc/internal/arena_inlines_b.h
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- src/extent.c
- test/unit/decay.c
This change improves memory usage slightly, at virtually no CPU cost.
Also resolves the issue in #1454
> Eagerly purge oversized extents.

- src/jemalloc.c
- src/tcache.c
We should allow a way to easily disable the feature (e.g. not reserving the
arena id at all).
>  Allow low values of oversize_threshold to disable the feature.

- doc/jemalloc.xml.in
Generated text:
`opt.oversize_threshold (size_t) r-`
`The threshold in bytes of which requests are considered oversize. Allocation requests with greater sizes are fulfilled from a dedicated arena (automatically managed, however not within narenas), in order to reduce fragmentation by not mixing huge allocations with small ones. In addition, the reserved special arena may have its own default decay settings. Note that requests with arena index specified via MALLOCX_ARENA, or threads associated with explicit arenas will not be considered. The default threshold is 8MiB. Values not within large size classes disables this feature.`
> Document opt.oversize_threshold.

- include/jemalloc/internal/extent_externs.h
- include/jemalloc/internal/extent_structs.h
- include/jemalloc/internal/extent_types.h
- src/ctl.c
- src/extent.c
- test/unit/mallctl.c
The analytics tool is put under experimental.utilization namespace in
mallctl.  Input is one pointer or an array of pointers and the output
is a list of memory utilization statistics.
> Add memory utilization analytics to mallctl

- src/extent.c
- src/extent_dss.c
- src/extent_mmap.c
This is discovered and suggested by @jasone in #1468.  When custom extent hooks
are in use, we should ensure page alignment on the extent alloc path, instead of
relying on the user hooks to do so.
This resolves #1468
> Ensure page alignment on extent_alloc.

- test/unit/prof_log.c
The unwinder may produce traces more than expected.  Instead verify the lower
bound only.
Corresponding to #1477
> Fix test/unit/prof_log

- bin/jeprof.in
- include/jemalloc/internal/jemalloc_internal_externs.h
- src/jemalloc.c
- src/jemalloc_cpp.cpp
Summary: sdallocx is checking a flag that will never be set (at least in the provided C++ destructor implementation).  Object deletion is a substantial part of the HHVM profile.  This branch will probably only rarely be mispredicted but it's still two instructions that don't need to be there.
> remove compare and branch in fast path for c++ operator delete[]

- configure.ac
- include/jemalloc/internal/emitter.h
- include/jemalloc/internal/extent_externs.h
- include/jemalloc/jemalloc_defs.h.in
- include/jemalloc/jemalloc_macros.h.in
Convert the format generator function to an annotated format function,
so that the generated formats can be checked by the compiler.
> Add format annotation to the format generator function

- include/jemalloc/internal/tsd_malloc_thread_cleanup.h
- include/jemalloc/internal/tsd_tls.h
- src/tsd.c
Caught by @zoulasc in #1460.  The attribute needs to be added in the headers as
well.
> Enforce TLS_MODEL attribute.

- doc/jemalloc.xml.in
- include/jemalloc/internal/bin.h
- include/jemalloc/internal/bin_stats.h
- src/arena.c
- src/ctl.c
- src/stats.c
- test/unit/stats.c
When config_stats is enabled track the size of bin->slabs_nonfull in
the new nonfull_slabs counter in bin_stats_t. This metric should be
useful for establishing an upper ceiling on the savings possible by
meshing.
> Add nonfull_slabs to bin_stats_t.

- src/jemalloc.c
rtree_szind_slab_read_fast() may have not initialized
alloc_ctx.szind, unless after confirming the return is true.
> Fix assert in free fastpath

- doc/jemalloc.xml.in
- include/jemalloc/internal/arena_stats.h
- include/jemalloc/internal/ctl.h
- src/arena.c
- src/ctl.c
- src/stats.c
- src/tcache.c
Small is added purely for convenience.  Large flushes wasn't tracked before and
can be useful in analysis.  Large fill simply reports nmalloc, since there is no
batch fill for large currently.
> Track nfills and nflushes for arenas.i.small / large

- src/malloc_io.c
GCC-9.1 reports following error when trying to compile file
src/malloc_io.c and with CFLAGS='-Werror' :
src/malloc_io.c: In function ‘malloc_vsnprintf’:
src/malloc_io.c:369:2: error: case label value exceeds maximum value for type [-Werror]
369 |  case '?' | 0x80:      \
|  ^~~~
src/malloc_io.c:581:5: note: in expansion of macro ‘GET_ARG_NUMERIC’
581 |     GET_ARG_NUMERIC(val, 'p');
|     ^~~~~~~~~~~~~~~
...
<snip>
cc1: all warnings being treated as errors
make: *** [Makefile:388: src/malloc_io.sym.o] Error 1
The warning is reported as by default the type 'char' is 'signed char'
and or-ing 0x80 will turn the case label char negative which will be
beyond the printable ascii range (0 - 127).
The patch fixes this by explicitly casting the 'len' variable as
unsigned char' inside the 'switch' …
> Fix GCC-9.1 warning with macro GET_ARG_NUMERIC

- doc/jemalloc.xml.in
- include/jemalloc/internal/jemalloc_internal_externs.h
- src/ctl.c
- src/jemalloc.c
- src/stats.c
- test/unit/mallctl.c
If the confirm_conf option is set, when the program starts, each of
the four malloc_conf strings will be printed, and each option will
be printed when being set.
> Add confirm_conf option

- src/background_thread.c
Background threads may run for a long time, especially when the # of dirty pages
is high.  Avoid blocking stats calls because of this (which may cause latency
spikes).
Resolves #1502.
> Avoid blocking on background thread lock for stats.

- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj.filters
The file is included in the list of source files in Makefile.in,
but it is missing from the project files. This causes the
build to fail due to unresolved symbols.
> Add missing safety_check.c to MSBuild projects

- .appveyor.yml
Enable-debug and 64-bit runs tend to be more relevant. Run them first.
> Reorder the configs for AppVeyor.

- doc/jemalloc.xml.in
- include/jemalloc/internal/malloc_io.h
- src/malloc_io.c
`cbopaque` can now be overriden without overriding `write_cb` in
the first place.  (Otherwise there would be no need to have the
`cbopaque` parameter in `malloc_message`.)
> Fix logic in printing

- src/prof.c
The original logic can be disastrous if `PROF_DUMP_BUFSIZE` is less
than `slen` -- `prof_dump_buf_end + slen <= PROF_DUMP_BUFSIZE` would
always be `false`, so `memcpy` would always try to copy
`PROF_DUMP_BUFSIZE - prof_dump_buf_end` chars, which can be
dangerous: in the last round of the `while` loop it would not only
illegally read the memory beyond `s` (which might not always be
disastrous), but it would also illegally overwrite the memory beyond
`prof_dump_buf` (which can be pretty disastrous).  `slen` probably
has never gone beyond `PROF_DUMP_BUFSIZE` so we were just lucky.
> Fix a bug in prof_dump_write

- include/jemalloc/internal/arena_structs_b.h
`prof_accumbytes` was supposed to be replaced by `prof_accum` in
https://github.com/jemalloc/jemalloc/pull/623.
> Remove prof_accumbytes in arena

- src/jemalloc.c
- test/integration/posix_memalign.c
Return a valid pointer instead of failed assertion.
Size 0 fails at https://github.com/jemalloc/jemalloc/blob/ac34afb4037d7e9e87efde2b8e913d87aae131da/include/jemalloc/internal/jemalloc_internal_inlines_c.h#L72 before this patch.
> Fix posix_memalign with input size 0.

- src/extent.c
extent_register may only fail if the underlying extent and region got stolen /
coalesced before we lock.  Avoid doing extent_leak (which purges the region)
since we don't really own the region.
> extent_dalloc instead of leak when register fails.

- include/jemalloc/internal/arena_stats.h
- src/arena.c
- src/ctl.c
- src/extent.c
- src/stats.c
The counter is 0 unless metadata allocation failed (indicates OOM), and is
mainly for sanity checking.
Tested with local code path emulation and verified that the counter reported properly.
Based on #1552.
> Track the leaked VM space via the dropped_vm counter.

- src/extent.c
Stop scanning once reached the first max_active_fit size.
max_active_fit was moved from best fit to first fit in b62d126df894dac00772eb5f3d170a1c1d3d1614
> Optimize max_active_fit in first_fit.

- include/jemalloc/internal/arena_inlines_b.h
- src/arena.c
When tcache was disabled, the dalloc promoted case was missing.
> Invoke arena_dalloc_promoted() properly w/o tcache.

- doc/jemalloc.xml.in
Generated text:
If true, retain unused virtual memory for later reuse rather than discarding it by calling munmap(2) or equivalent (see stats.retained for related details). It also makes jemalloc use mmap(2) or equivalent in a more greedy way, mapping larger chunks in one go. This option is disabled by default unless discarding virtual memory is known to trigger platform-specific performance problems, namely 1) for [64-bit] Linux, which has a quirk in its virtual memory allocation algorithm that causes semi-permanent VM map holes under normal jemalloc operation; and 2) for [64-bit] Windows, which disallows split / merged regions with MEM_RELEASE. Although the same issues may present on 32-bit platforms as well, retaining virtual memory for 32-bit Linux and Windows is disabled by default …
> Update manual for opt.retain (new default on Windows).

- src/jemalloc.c
Should make the output from `confirm_conf` a bit clearer, e.g. 
<jemalloc>: malloc_conf #1 (string specified via --with-malloc-conf): "narenas:10"
<jemalloc>: -- Set conf value: narenas:10
<jemalloc>: malloc_conf #2 (string pointed to by the global variable malloc_conf): "narenas:20"
<jemalloc>: -- Set conf value: narenas:20
> Add indent to individual options for confirm_conf.

- Makefile.in
- include/jemalloc/internal/prof_externs.h
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj.filters
- src/prof.c
- src/prof_data.c
- src/prof_log.c
Refactored core profiling codebase into two logical parts:
(a) `prof_data.c`: core internal data structure managing & dumping;
(b) `prof.c`: mutexes & outward-facing APIs.
Some internal functions had to be exposed out, but there are not
that many of them if the modularization is (hopefully) clean enough.
> Refactor profiling

- src/extent.c
W/o retain, split and merge are disallowed on Windows.  Avoid doing first-fit
which needs splitting almost always.  Instead, try exact fit only and bail out
early.
>  Limit to exact fit on Windows with retain off

- include/jemalloc/internal/atomic_gcc_atomic.h
g++ complained about set but unused variable (though it's in fact
used).  This is a workaround.
> Workaround g++ unused variable warnings on compare_exchange

- src/prof.c
The emitter APIs used were incorrect, a side effect of which was
extra lines being printed.
> Quick fix for prof log printing

- include/jemalloc/internal/tsd.h
Augmented the tsd layout graph so that the two recently added fields,
`offset_state` and `bytes_until_sample`, are properly reflected.
As is shown, the cache footprint is 16 bytes larger than before.
> Correct tsd layout graph

- src/tcache.c
`tcaches_mtx` isn't really related to config_prof or opt_tcache. It's all about explicit tcaches in fact.
Unconditionally does pre / post fork mutex handling.
> Fix tcaches mutex pre- / post-fork handling.

- Makefile.in
- include/jemalloc/internal/malloc_io.h
- src/malloc_io.c
- test/unit/buf_writer.c
The buffered writer adopts a signature identical to `write_cb`,
so that it can be plugged into anywhere `write_cb` appears.
Currently it's only used in `malloc_stats_print` when both the
`write_cb` parameter and `je_malloc_message` are not set - without
buffering (as is the case before this change) it would invoke
`malloc_write_fd` for every single line in the stats output.
> Add buffered writer

- include/jemalloc/internal/emitter.h
- test/unit/emitter.c
JSON format is largely meant for machine-machine communication, so
adding the option to the emitter.  According to local testing, the
savings in terms of bytes outputted is around 50% for stats printing
and around 25% for prof log printing.
> Add compact json option for emitter

- src/prof_log.c
The prof_alloc_node is allocated through ialloc as internal.  Switch to
idalloctm with tcache and is_internal properly set.
> Properly dalloc prof nodes with idalloctm.

- src/tcache.c
`tcache->prof_accumbytes` should always be cleared after being
transferred to arena; otherwise the allocations would be double
counted, leading to excessive prof dumps.
> Clear tcache prof_accumbytes in tcache_flush_cache

- src/prof_log.c
- src/stats.c
Saves 20-50% of the output size.
> Make compact json format as default

- Makefile.in
- include/jemalloc/internal/cache_bin.h
- include/jemalloc/internal/jemalloc_internal_inlines_a.h
- include/jemalloc/internal/tcache_externs.h
- include/jemalloc/internal/tcache_inlines.h
- src/arena.c
- src/jemalloc.c
- src/tcache.c
- test/unit/cache_bin.c
Implement the pointer-based metadata for tcache bins --
- 3 pointers are maintained to represent each bin;
- 2 of the pointers are compressed on 64-bit;
- is_full / is_empty done through pointer comparison;
Comparing to the previous counter based design --
- fast-path speed up ~15% in benchmarks
- direct pointer comparison and de-reference
- no need to access tcache_bin_info in common case
Fast path micro-benchmark results improved from 15ns to 13ns. Production A/B testing shows fast path malloc cost reduction 5-7%, free cost reduction 15-17% (likely from not accessing tcache_bin_info).
> Redesign the cache bin metadata for fast path.

- include/jemalloc/internal/cache_bin.h
- include/jemalloc/internal/tcache_inlines.h
- src/arena.c
- src/tcache.c
- test/unit/cache_bin.c
With the cache bin metadata switched to pointers, ncached_max is usually
accessed and timed by sizeof(ptr). Store the results in tcache_bin_info for
direct access, and add a helper function for the ncached_max value.
On top of #1592
> Store stack_size in tcache_bin_info.

- include/jemalloc/internal/cache_bin.h
- include/jemalloc/internal/tcache_structs.h
- src/arena.c
- src/tcache.c
- test/unit/cache_bin.c
The -1 value of low_water indicates if the cache has been depleted and
refilled.  Track the status explicitly in the tcache struct.
This allows the fast path to check if (cur_ptr > low_water), instead of >=,
which avoids reaching slow path when the last item is allocated.
> Track low_water == -1 case explicitly.

- src/jemalloc.c
The bug is subtle but critical: if application performs the following
three actions in sequence: (a) turn `prof_active` off, (b) make at
least one allocation that triggers the malloc slow path via the
`if (unlikely(bytes_until_sample < 0))` path, and (c) turn
`prof_active` back on, then the application would never get another
sample (until a very very long time later).
The fix is to properly reset `bytes_until_sample` rather than
throwing it all the way to `SSIZE_MAX`.
A side minor change is to call `prof_active_get_unlocked()` rather
than directly grabbing the `prof_active` variable - it is the very
reason why we defined the `prof_active_get_unlocked()` function.
> Bug fix for prof_active switch

- src/ctl.c
Verified that now the merged stats section show the correct number of large.nflushes (i.e. the sum from all arenas).
> Fix large.nflushes in the merged stats.

- include/jemalloc/internal/cache_bin.h
- src/tcache.c
The bin size type was made signed only because the low_water could go -1, which
was already removed.
> Make cache_bin_sz_t unsigned.

- include/jemalloc/internal/prof_externs.h
- include/jemalloc/internal/prof_inlines_b.h
- src/prof.c
- src/prof_log.c
`_Unwind_Backtrace` is most likely not calling `malloc()`/`free()`, but from correctness aspect we should have a guard rather than relying only on trust. From behavior aspect `reentrancy_level` is also important: for example, profiling is turned off when `reentrancy_level > 0`.
> Fix libc reentrancy level

- include/jemalloc/internal/background_thread_structs.h
- include/jemalloc/internal/mutex.h
- include/jemalloc/internal/mutex_prof.h
- src/background_thread.c
- src/ctl.c
Added a new stats row to aggregate the maximum value of mutex counters for each
background threads.  Given that the per bg thd mutex is not expected to be
contended, this counter is mainly for sanity check / debugging.
Resolves #1511.
Takes over #1597. Thanks for working on this @zhxchen17!
> Add max_per_bg_thd stats for per background thread mutexes.

- msvc/test_threads/test_threads.cpp
I have a packaging procedure which runs tests. Unfortunaly at the moment the msvc tests are sensitive to the prefix being exactly `je_`.
> Fix je_ prefix issue in test

- include/jemalloc/internal/prof_inlines_a.h
- src/ctl.c
- src/prof.c
- test/unit/mallctl.c
Set `prof_active` to read-only when `opt_prof` is turned off.
> Guard prof_active reset by opt_prof

- include/jemalloc/internal/prof_inlines_b.h
- src/prof.c
- src/prof_data.c
This change suppresses tdata initialization and prof sample threshold
update in interrupting malloc calls.  Interrupting calls have no need
for tdata. Delaying tdata creation aligns better with our lazy tdata
creation principle, and it also helps us gain control back from
interrupting calls more quickly and reduces any risk of delegating
tdata creation to an interrupting call.
> Suppress tdata creation in reentrancy

- test/unit/bitmap.c
Otherwise the test is too slow for higher page sizes such as 64k.
> Limit # of iters of test_bitmap_xfu.

- include/jemalloc/internal/cache_bin.h
- include/jemalloc/internal/safety_check.h
- src/prof_log.c
- src/stats.c
Get rid of `warning C4267: 'initializing': conversion from 'size_t' to 'cache_bin_sz_t', possible loss of data` when compiled in an environment like `MSYSTEM=MINGW64, CPU=x86_64, MSVC=amd64`.
(Not sure if we'd better have some additional asserts as guards.)
> Fix amd64 MSVC warning

- include/jemalloc/internal/cache_bin.h
- src/jemalloc.c
`tcache_bin_info` is not accessed on malloc fast path but the
compiler reserves a register for it, as well as an additional
register for `tcache_bin_info[ind].stack_size`.  The new optimization
gets rid of the need for the two registers.
> Optimize cache_bin_alloc_easy for malloc fast path

- src/stats.c
The rates can easily reach 8-digit numbers in large services and therefore touch the `namlloc`/`nfree` total counts on the left.
> Increase column width for global malloc/free rate

- src/ctl.c
- src/extent.c
- test/unit/extent_util.c
`slabcur` can be `NULL`, and in such cases, the extent utilization querying logic should fetch the first extent from the non-full extents, because it will become `slabcur` next. If this fails, then the logic returns `NULL`.
> Guard slabcur fetching in extent_util

- src/pages.c
some architectures like AArch64 may not have the open syscall, but have
openat syscall. so check and use SYS_openat if SYS_openat available if
SYS_open is not supported at init_thp_state.
> use SYS_openat when available

- Makefile.in
- include/jemalloc/internal/prof_inlines_b.h
- include/jemalloc/internal/thread_event.h
- include/jemalloc/internal/tsd.h
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj.filters
- src/jemalloc.c
- src/prof.c
- src/thread_event.c
- test/unit/thread_event.c
- test/unit/thread_event.sh
I haven't added unit tests. Will add later. I want to seek some early feedback on the design first.
A few remarks:
- I turned off the accumulation of allocation bytes on `thread_allocated` when `reentrancy_level > 0`.  Otherwise the implementation would become very tricky, because when `reentrancy_level > 0`, profiling should be turned off by jemalloc design - see https://github.com/jemalloc/jemalloc/blob/785b84e60382515f1bf1a63457da7a7ab5d0a96b/include/jemalloc/internal/prof_inlines_b.h#L135 but if `thread_allocated` keeps increasing, the wait time till the next sampling event would be incorrect, unless we keep some internal state so that when `reentrancy_level` drops back to `0`, we can adjust the wait time; this would require that the store and fetch for the internal state should have …
> Build a general purpose thread event handler

- include/jemalloc/internal/tcache_inlines.h
- include/jemalloc/internal/tcache_types.h
- include/jemalloc/internal/thread_event.h
- include/jemalloc/internal/tsd.h
- src/jemalloc.c
- src/thread_event.c
- src/tsd.c
- test/unit/thread_event.c
Currently only the tcache GC events along the allocation path are pulled into the thread event handler. Once the deallocation path also gets a thread event handler, the GC events there can be consolidated (with `thread.deallocated`).
The interval in terms of bytes are temporarily set to be 32768: given that `TCACHE_GC_INCR` is right now 228, 32768 bytes would be an equivalent interval if we assume the average allocation size is around 140-150 bytes.
> Pull tcache GC events into thread event handler

- configure.ac
- include/jemalloc/internal/hash.h
- include/jemalloc/internal/jemalloc_internal_macros.h
- include/jemalloc/jemalloc_defs.h.in
- include/jemalloc/jemalloc_macros.h.in
- src/arena.c
- src/malloc_io.c
- src/tsd.c
Clang since r369414 (clang-10) can now check -Wimplicit-fallthrough for
C code, and use the GNU C style attribute to denote fallthrough.
Move the test from header only to autoconf. The previous test used
brittle version detection which did not work for newer clang that
supported this feature.
The attribute has to be its own statement, hence the added `;`. It also
can only precede case statements, so the final cases should be
explicitly terminated with break statements.
Fixes commit 3d29d11ac2c1 ("Clean compilation -Wextra")
Link: https://github.com/llvm/llvm-project/commit/1e0affb6e564b7361b0aadb38805f26deff4ecfc
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
> Add -Wimplicit-fallthrough checks if supported

- include/jemalloc/internal/arena_structs.h
- include/jemalloc/internal/prof_externs.h
- include/jemalloc/internal/prof_inlines_b.h
- include/jemalloc/internal/prof_structs.h
- include/jemalloc/internal/tsd.h
- src/arena.c
- src/extent.c
- src/prof.c
- src/prof_data.c
- src/thread_event.c
- src/tsd.c
- Get rid of the arena and tdata prng state; always make use of the tsd prng.
- Refactor the sample interval / tdata initialization, so that the event interval is properly set w/o creating tdata.
- As a results, tdata will only be created when a thread actually reaches the sample interval, which should help the short lived threads (and my sanity around `prof_sample_accum_update`).
> Refactor the prng usage

- src/jemalloc.c
Larger sizes are not that uncommon comparing to !tsd_fast.
> Check for large size first in the uncommon case of malloc.

- include/jemalloc/internal/prof_inlines_b.h
We should pass in `old_ptr` rather than the new `ptr` to
`prof_free_sampled_object()` when `old_ptr` points to a sampled
allocation.
> Fix bug in prof_realloc

- include/jemalloc/internal/prof_inlines_b.h
Reverts jemalloc/jemalloc#1683
The fix was a wrong fix: the logic in `prof_free_sampled_object()` may try to access the extent `old_ptr` resides in, which could be gone at this moment. The correct fix would be more complicated to implement. Having the wrong fix may lead to a crash whereas reverting it back only causes a logical error, so revert.
> Revert "Fix bug in prof_realloc"

- src/arena.c
This avoids taking the muzzy decay mutex with the default setting.
Apparently the muzzy decay mutex is taken often, e.g. ~18k / sec:
```
n_lock_ops (#/sec)       n_waiting (#/sec)      n_spin_acq (#/sec)  n_owner_switch (#/sec)   total_wait_ns   (#/sec)     max_wait_ns  max_n_thds
decay_dirty                  86828893    9611               0       0              56       0        26608711    2945               0         0               0           0
decay_muzzy                 161508733   17877               0       0             366       0        26308543    2912               0         0               0           0
```
even busier than the dirty decay mutex, due to `arena_decay_to_limit` triggered at [arena.c:L720](https://github.com/jemalloc/jemalloc/pull/1672/files#diff-2010398b2a21c1 …
> Bail out early for muzzy decay.

- src/jemalloc.c
The `getaffinity` approach should be preferred than `sysconf(_SC_NPROCESSORS_ONLN)`, because with affinity binding the number of usable cores could be fewer.
Also prefer `sched_getaffinity` when available.
> Prefer getaffinity() to detect number of CPUs.

- include/jemalloc/internal/arena_externs.h
- include/jemalloc/internal/bin.h
- include/jemalloc/internal/bin_stats.h
- include/jemalloc/internal/ctl.h
- src/arena.c
- src/ctl.c
Avoid storing mutex_prof_data_t in bin_t.  Added bin_stats_data_t which is used
for reporting bin stats.
With 64bit opt build, `sizeof(bin_t)` reduced by `sizeof(mutex_prof_data_t) == 64B` (from 280 to 216).
> Reduce footprint of bin_t.

- configure.ac
- include/jemalloc/internal/jemalloc_internal_decls.h
- m4/ax_cxx_compile_stdcxx.m4
- src/jemalloc_cpp.cpp
Summary:
Add support for C++17 over-aligned allocation:
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0035r4.html
Supporting all 10 operators means we avoid thunking thru libstdc++-v3/libsupc++ and just call jemalloc directly.
It's also worth noting that there is now an aligned *and sized* operator delete:
```
void operator delete(void* ptr, std::size_t size, std::align_val_t al) noexcept;
```
If JeMalloc did not provide this, the default implementation would ignore the size parameter entirely:
https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/libsupc%2B%2B/del_opsa.cc#L30-L33
(I must also update ax_cxx_compile_stdcxx.m4 to a newer version with C++17 support.)
Test Plan:
Wrote a simple test that allocates and then deletes an over-aligned type:
```
struct …
```
> Support C++17 over-aligned allocation

- include/jemalloc/internal/arena_inlines_b.h
- include/jemalloc/internal/extent.h
- include/jemalloc/internal/large_externs.h
- include/jemalloc/internal/prof_externs.h
- include/jemalloc/internal/prof_inlines_b.h
- include/jemalloc/internal/prof_structs.h
- include/jemalloc/internal/prof_types.h
- src/jemalloc.c
- src/large.c
- src/prof.c
- src/prof_log.c
- test/unit/prof_tctx.c
Develop new data structure and code logic for holding profiling
related information stored in the extent that may be needed after the
extent is released, which in particular is the case for the
reallocation code path (e.g. in `rallocx()` and `xallocx()`).  The
data structure is a generalization of `prof_tctx_t`: we previously
only copy out the `prof_tctx` before the extent is released, but we
may be in need of additional fields. Currently the only additional
field is the allocation time field, but there may be more fields in
the future.
The restructuring also resolved a bug: `prof_realloc()` mistakenly
passed the new `ptr` to `prof_free_sampled_object()`, but passing in
the `old_ptr` would crash because it's already been released.  Now
the essential profiling information is collectively …
> Restructure profiling

- configure.ac
- include/jemalloc/internal/tcache_types.h
- src/prof.c
With recent versions of GCC, run_tests.sh will fail due to warnings. Disable them.
> Disable some spuriously-triggering warnings

- src/tcache.c
- src/thread_event.c
- test/unit/cache_bin.c
I thought cassert was for static assert. Apparently it's intended for config assertion instead.
> Fix incorrect usage of cassert.

- include/jemalloc/internal/thread_event.h
- include/jemalloc/internal/tsd.h
- src/jemalloc.c
- src/thread_event.c
- src/tsd.c
- test/unit/thread_event.c
Fold the tsd_state branch onto the event threshold check. After this change, we have only 3 branches on the fast-path: 1) size threshold, 2) event threshold and 3) tcache is empty.
> Optimize away the tsd_fast() check on fastpath.

- include/jemalloc/internal/arena_inlines_b.h
- include/jemalloc/internal/large_externs.h
- include/jemalloc/internal/prof_inlines_b.h
- src/large.c
- src/prof.c
Explicitly define three setters:
- `prof_tctx_set_not_sampled()`: set `prof_tctx` to `1U`, if we don't know in advance whether the allocation is large or not;
- `prof_tctx_reset()`: set `prof_tctx` to `1U`, if we already know in advance that the allocation is large;
- `prof_info_set()`: set a real `prof_tctx`, and also set other profiling info e.g. the allocation time.
Code structure wise, the prof level is kept as a thin wrapper, the large level only provides low level setter APIs, and the arena level carries out the main logic.
> Restructure setters for profiling info

- include/jemalloc/internal/tsd.h
- src/jemalloc.c
After a thread turns into purgatory / reincarnated state, still allow dallocx
and sdallocx to function normally.
> Allow dallocx and sdallocx after tsd destruction.

- src/base.c
I found with `export MALLOC_CONF=thp:never` & `/sys/kernel/mm/transparent_hugepage/enabled`'s value: `always`, there's still `AnonHugePages` usage in /proc/`pidof xxx`/smaps.  After tracing, I found all viraddrs which toggle anon huge page fault handler is from base_new, such as:
```
tid: 38746	viraddr: 0xfffba0000000	mmap_start: 0xfffba0000000	AnonHugeFaultHandlerRet: 0	madvised: False 
os_pages_map+0x0 [xxx]
_rjem_je_extent_alloc_mmap+0x28 [xxx]
_rjem_je_base_new+0x308 [xxx]
_rjem_je_arena_new+0x9c [xxx]
_rjem_je_arena_choose_hard+0x25c [xxx]
_rjem_je_tsd_tcache_data_init+0x44c [xxx]
_rjem_je_tsd_tcache_enabled_data_init+0x40 [xxx]
_rjem_je_tsd_fetch_slow+0x158 [xxx]
malloc+0x188 [xxx]
pthread_getattr_np+0xec [libpthread-2.28.so]
```
So I add `pages_set_thp_state` in `base_map` like …
> fix opt.thp:never still use THP with base_map

- include/jemalloc/internal/prof_data_externs.h
- include/jemalloc/internal/prof_externs.h
- include/jemalloc/internal/prof_log_externs.h
- src/prof.c
- src/prof_data.c
- src/prof_log.c
- test/unit/prof_log.c
The goal is to denoise `prof_externs.h`, so that prof internal functions are only tied to places defining / using them without being exposed externally.
> Refactor profiling headers

- include/jemalloc/internal/malloc_io.h
- src/jemalloc.c
- src/malloc_io.c
- src/prof_log.c
- src/prof_recent.c
- test/unit/buf_writer.c
Unify the "namespace" of the buffered writer utility to `buf_write_*`.
> Unify buffered writer naming

- src/ehooks.c
Caught by the CI in https://github.com/jemalloc/jemalloc/pull/1717. The tests pass after rebasing on top of this.
> Fix an assertion on extent head state with dss.

- include/jemalloc/internal/sz.h
- src/jemalloc.c
The first half of the malloc fastpath may execute before malloc_init.  Make the
assertions work in that case.
The regression was introduced in https://github.com/jemalloc/jemalloc/commit/dd649c94859e2cdbe7b527cfb743b549c8d8bf50
> Rework and fix the assertions on malloc fastpath.

- src/prof_data.c
The allocation record in the last-N list will still be reset, but there's no deallocation time / `tctx` recorded.
> No tdata creation for backtracing on dying thread

- include/jemalloc/internal/extent.h
- src/arena.c
- src/extent.c
- src/large.c
No caller ever wants uncommitted memory.
> Remove commit parameter to ecache functions.

- Makefile.in
- src/prof_data.c
- src/prof_recent.c
- test/include/test/jemalloc_test.h.in
- test/include/test/mq.h
- test/include/test/sleep.h
- test/src/sleep.c
- test/unit/prof_recent.c
The `decrement_recent_count()` call is made to be async, and there's no concurrent lock holdings at any time.
The issue was detected in a stress test I was writing. I'm also appending the stress test to this PR.
> Get rid of lock overlap in prof_recent_alloc_reset

- doc/jemalloc.xml.in
- src/ctl.c
- test/unit/mallctl.c
This can encapsulate various internal cleaning logic, and can be used to free up
resources before a long sleep.
> Add "thread.idle" mallctl.

- include/jemalloc/internal/tsd.h
- src/tsd.c
Reentrancy is already set for other non-nominal tsd states (reincarnated and
minimal_initialized).  Add purgatory to be safe and consistent.
> Set reentrancy to 1 for tsd_state_purgatory.

- include/jemalloc/internal/prof_inlines_b.h
- include/jemalloc/internal/safety_check.h
- src/jemalloc.c
- src/safety_check.c
- src/tcache.c
- test/integration/extent.c
This allows sampled allocations to be checked through alignment, therefore enable sized deallocation regardless of cache_oblivious.
Enables the speed up of sized deallocation, in `test/integration/stress`:
before:
100000000 iterations, dallocx=1254009us, sdallocx=1222009us, ratio=1:1.026
with this PR:
100000000 iterations, dallocx=1259009us, sdallocx=759005us, ratio=1:1.659
Resolves #1697
>  Enforce page alignment for sampled allocations

- include/jemalloc/internal/tcache_inlines.h
- include/jemalloc/internal/tcache_structs.h
- include/jemalloc/internal/thread_event.h
- include/jemalloc/internal/tsd.h
- src/jemalloc.c
- src/tcache.c
- src/thread_event.c
- src/tsd.c
- test/unit/thread_event.c
Make the event module to accept two event types, and pass around the event context.  Use bytes-based events to trigger tcache GC on deallocation, and get rid of the tcache ticker.
> Implement deallocation events

- include/jemalloc/internal/buf_writer.h
- src/buf_writer.c
- src/jemalloc.c
- src/prof_log.c
- src/prof_recent.c
- test/unit/buf_writer.c
This change tries to achieve the following goals:
- Encapsulate buffer allocation within the buffered writer module. I found this to be very useful in simplifying the caller side logic, as well as in supporting additions of more functionalities to the buffered writer module in the future. The buffered writer module is also made to be flexible in accepting a caller supplied buffer.
- Test OOM. This is another main advantage of the encapsulation: now OOM testing can be a unit test for the buffered writer module, rather than multiple tests each for one caller, which are not only redundant but also hard. I'll see later if I can further generalize the OOM testing so that other jemalloc components can benefit.
> Encapsulate buffer allocation in buffered writer

- src/ctl.c
There are cases where we require the `mallctl()` caller to provide an input. The current `WRITE()` treats caller input as optional, so when an input is required, we'd have to artificially do some initialization ahead and some check afterwards. The new `MUST_WRITE` tries to make such scenarios less painful.
Currently I'm only migrating `tcache.flush` and `tcache.destroy` to the new `MUST_WRITE`. Let me know if any other `mallctl()` calls can be changed.
> Add ASSURED_WRITE in mallctl

- include/jemalloc/internal/arena_externs.h
- src/arena.c
- src/tcache.c
Previously, tcache fill/flush (as well as small alloc/dalloc on the arena) may
potentially drop the bin lock for slab_alloc and slab_dalloc.  This commit
refactors the logic so that the slab calls happen in the same function / level
as the bin lock / unlock.  The main purpose is to be able to use flat combining
without having to keep track of stack state.
In the meantime, this change reduces the locking, especially for slab_dalloc
calls, where nothing happens after the call.
> Rework the bin locking around tcache refill / flush.

- src/ctl.c
- test/include/test/test.h
- test/unit/prof_recent.c
I'm currently defining a `write_cb_packet_t` construct in `ctl.c` to represent the `[write_cb, cbopaque]` tuple passed in as input to the `mallctl()`.
Also added extensive unit tests.
> Add mallctl for dumping last-N profiling records

- include/jemalloc/internal/ehooks.h
- include/jemalloc/internal/jemalloc_internal_decls.h
- src/tcache.c
The small and large pathways share most of their big-picture logic, even if some of the specifics are different (e.g. both have a trick to merge the stats locking with object locking if possible, even though the specific stats kept for small and large allocations are different). Unifying them makes the similarities and differences clearer.
While we're here, beef up the comments.
> Tcache: Unify bin flush logic.

- test/unit/thread_event.c
The `test_next_event_fast_resume` test has an issue even though it didn't fail. Its setup was directly against the thread event design: the wait time plus the allocation exceeded `UINT64_MAX`, causing an overflow here:
https://github.com/jemalloc/jemalloc/blob/305b1f6d962c5b5a76b7ddb4b55b14d88bada9ba/src/thread_event.c#L309
which ended up having `te_event_trigger()` triggering no event. There was no critical harm, but we were not testing what we wanted to test, and the logic did not follow the plan of the code.
The fix is to simply carry out `test_next_event_fast_resume` directly after `test_next_event_fast_roll_back`.
> Correct thread event unit test

- Makefile.in
- configure.ac
- include/jemalloc/internal/arena_externs.h
- include/jemalloc/internal/arena_inlines_a.h
- include/jemalloc/internal/cache_bin.h
- include/jemalloc/internal/jemalloc_internal_externs.h
- include/jemalloc/internal/jemalloc_internal_inlines_a.h
- include/jemalloc/internal/jemalloc_internal_inlines_b.h
- include/jemalloc/internal/large_externs.h
- include/jemalloc/internal/tcache_externs.h
- include/jemalloc/internal/tcache_inlines.h
- include/jemalloc/internal/tcache_structs.h
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj.filters
- src/arena.c
- src/cache_bin.c
- src/extent.c
- src/jemalloc.c
- src/large.c
- src/tcache.c
- test/unit/cache_bin.c
- test/unit/junk.c
This rewrites the cache bin module to track more of its low water, full, and empty states in the bin itself. This has a few advantages
- It makes the logic easier to reason about
- It unifies the 32-bit and 64-bit implementations
- It makes it easy for the fast paths to change the low-water mark if necessary. This results in around a 4% improvement in cycles-spent-in-malloc in prod workloads (for around a .1% end-to-end improvement).
This also pulls the maintenance logic out of the tcache and arena modules and into the cache_bin module, and documents it; the resulting code is a lot easier to read and maintain.
> Rewrite cache bin module

- Makefile.in
- include/jemalloc/internal/edata_cache.h
- src/edata_cache.c
- test/unit/edata_cache.c
- test/unit/inspect.c
This adds:
- Unit tests for the edata_cache_t (which was previously tested only via the extent tests).
- A slight performance improvement to it (an atomic fetch-add which can just be a load-then-store).
- An unsynchronized edata_cache_small_t, which can amortize locking and allocations. (This is not actually used anywhere yet, but I've got several branches that all could use this and an early merge would be helpful from a workflow perspective).
- A minor fix to the inspect unit test (some of its assumptions stop being correct if profiling is enabled).
> Edata cache and inspect fixes

- include/jemalloc/internal/prof_externs.h
- include/jemalloc/internal/prof_inlines_b.h
- include/jemalloc/internal/thread_event.h
- src/jemalloc.c
- src/prof.c
- src/thread_event.c
- test/unit/thread_event.c
There are a few subtle things here:
- The main change is to always reset the sampling threshold in `prof_alloc_rollback()`. Previously, we only reset when `updated == true`. I think we should also reset when `updated == false`, which is actually more important - otherwise the next allocation would always be sampled because the threshold would still be observed as having been hit. If my reasoning is correct, I feel that the `updated` flag is redundant (in the entire profiling logic), and I'll try to add another commit to remove it.
- A related fix in `xallocx()`. The issue is revealed in `test_xallocx_overflow` in `test/unit/safety_check`. The issue was hidden before my main change in `prof_alloc_rollback()`: when an `xallocx()` does not resize, the next `malloc()` is always sampled, which …
> Rewrite profiling thread event

- src/arena.c
- test/unit/stats.c
Previously, large allocations in tcaches would have their sizes reduced during
stats estimation.  Added a test, which fails before this change but passes now.
This fixes a bug introduced in 593484661261c20f75557279931eb2d9ca165185, which
was itself fixing a bug introduced in 9c0549007dcb64f4ff35d37390a9a6a8d3cea880.
> Stats: Fix tcache_bytes reporting.

- test/include/test/test.h
- test/src/test.c
This bug was introduced in https://github.com/jemalloc/jemalloc/commit/fa615793821219f8ad62e40aa23c848e5136aa5c: if an `expect_*()` failed previously, an `assert_*()` would abort regardless of whether the condition being asserted holds or not.
It was BTW one of my trickiest debugging experiences: when I was working on another project, I spent a long time trying to investigate into why the condition being asserted would fail without ever questioning the validity of the assertion macro itself, until I realized this bug at the very end. :)
> Fix: assertion could abort on past failures

- Makefile.in
- include/jemalloc/internal/prof_externs.h
- src/ctl.c
- src/jemalloc.c
- src/prof.c
- test/unit/mallctl.c
- test/unit/prof_use_sys_thread_name.c
- test/unit/prof_use_sys_thread_name.sh
This is solution to #1797.
The implementation is different from my comment on the issue: the system call is always invoked at sampling time. The purpose is to guarantee that we don't miss any thread name update set by the caller via system calls.
This would overwrite any thread name set via `mallctl`, so I'm explicitly disallowing the `mallctl` setter call when the new option is turned on. Logically the new option means: use the system thread name *instead of* the `mallctl` thread name.
Also added platform independent unit tests.
> Add option to fetch system thread name on each prof sample

- include/jemalloc/jemalloc_macros.h.in
- include/jemalloc/jemalloc_protos.h.in
This contradicts the system headers, which can lead to breakages.
> Mac: don't declare system functions as nothrow.

- Makefile.in
- configure.ac
- src/jemalloc.c
- test/unit/malloc_conf_2.c
- test/unit/malloc_conf_2.sh
This comes in handy when you're just a user of a canary system who wants to change settings set by the configuration system itself (and so you control the binary but not the environment variables, which can override your settings).
The silly name is deliberate -- it's a hint that this shouldn't really be present in "serious" code.
> Add malloc_conf_2_conf_harder

- src/large.c
This is more of a question than a PR. I don't quite get the reason why we need the strong `ATOMIC_RELEASE` and `ATOMIC_ACQUIRE` for the `prof_tctx_t` pointer on `edata`. I might have missed something important, and I want to better understand it. Otherwise we shouldn't impose stronger than necessary requirements.
> Make prof_tctx_t pointer a true prof atomic fence

- include/jemalloc/internal/buf_writer.h
- src/buf_writer.c
- src/jemalloc.c
- src/prof_log.c
- src/prof_recent.c
- test/unit/buf_writer.c
The first commit cleans up the current buffered writer API -
- Previously, buffered writer has two getter functions respectively for the callback function and for the callback argument: if the buffer allocation failed, the getter functions just return the callback function and argument the buffered writer was originally given; otherwise, the getter functions return the buffered writer's internal write callback function and the buffered writer object itself.
- Now, regardless of whether the buffer allocation failed or not, the caller always calls buffered writer's internal write callback function with the buffered writer object itself, and the internal callback function decides to whether route the write call directly to the original callback function or buffer the write. There is thus no …
> Add piping API to buffered writer

- include/jemalloc/internal/prof_recent.h
- include/jemalloc/internal/prof_structs.h
- src/prof_recent.c
- test/unit/prof_recent.c
This PR relies on the new `ql` functionalities introduced in #1807. Only the final two commits authentically belong to this PR.
Thanks to the migration to `ql`, I observed that the `test_prof_recent_stress` test is now much faster, as a nice by-product. My guess is: before this change, the custom iterator was not inline in the test environment, and so the `prof_recent_alloc_assert_count()` function, which repeatedly called the custom iterator and was itself frequently invoked for checking pre- and post- conditions, would likely have been a main contributor to the extra computation cost.
> Use ql for prof last-N list

- src/sc.c
This magic constant introduces inconsistencies.  We should be able to change its
value solely by adjusting the definition in the header.
> SC: use SC_LG_NGROUP instead of its value.

- include/jemalloc/internal/arena_externs.h
- include/jemalloc/internal/arena_structs.h
- include/jemalloc/internal/cache_bin.h
- include/jemalloc/internal/jemalloc_internal_inlines_a.h
- include/jemalloc/internal/jemalloc_internal_inlines_b.h
- include/jemalloc/internal/tcache_externs.h
- include/jemalloc/internal/tcache_inlines.h
- include/jemalloc/internal/tcache_structs.h
- include/jemalloc/internal/tcache_types.h
- include/jemalloc/internal/tsd.h
- src/arena.c
- src/ctl.c
- src/hook.c
- src/jemalloc.c
- src/tcache.c
- src/thread_event.c
- src/tsd.c
The primary motivation of this change is to make the cache bins contiguous, which will allow for a subsequent change making the slab sizes more truly dynamic (and the small/large distinction no longer static).
Historically, we've been hesitant about this, since we use the space in between them in the tcache to stick data that sort of lives in between hot and cold. Putting it before the tcache would split up the hot early fields from the tcache itself, and putting it after means we risk touching an extra page after all the (mostly untouched tcache bins).
The trick here is to stick all the medium-warmth data before the first hot-path piece of TSD data. This is an obvious-enough solution that I don't know why we didn't think of it before.
We also move the rtree_ctx to be the last slow-path …
> Rearrange TSD, make cache bins contiguous

- Makefile.in
- src/jemalloc.c
- src/large.c
- test/include/test/bench.h
- test/stress/large_microbench.c
- test/stress/microbench.c
This is both cleaner (it makes it so that the core internals don't know about opt.zero; they only know about the specific requests made of them), and makes the opt.zero case faster (since the extent-level allocator can madvise-zero the pages, avoiding having to memset them).
Tested the opt.zero improvement using the new benchmark with opt.zero on and off.
We take an extra branch now on realloc pathways, but it should mostly be correctly predicted (and those aren't hot paths to begin with).
> Move opt.zero zeroing decisions earlier in the allocation life-cycle

- src/witness.c
Before this change, I got the following error message while working on another project:
```
<jemalloc>: Lock rank order reversal: ctl(1) tcaches(2) arenas(3) background_thread_global(4) prof_dump(5) prof_bt2gctx(6) prof_tdatas(7) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) prof_tdata(8) …
```
> Deduplicate entries in witness error message

- include/jemalloc/internal/buf_writer.h
- include/jemalloc/internal/emitter.h
- include/jemalloc/internal/jemalloc_internal_types.h
- include/jemalloc/internal/malloc_io.h
- include/jemalloc/internal/prof_externs.h
- include/jemalloc/internal/stats.h
- src/ctl.c
- src/malloc_io.c
- src/prof_recent.c
- src/stats.c
The write callback signature is relocated from buffered writer to `malloc_io`, which it more naturally belongs to. Unified the write callback declarations in the code base, so that they become more simplified and less error prone.
This is also a step needed for rewriting prof dumping.
> Unify write callback signature

- include/jemalloc/internal/prof_data.h
- include/jemalloc/internal/prof_externs.h
- include/jemalloc/internal/stats.h
- include/jemalloc/internal/tcache_externs.h
- include/jemalloc/internal/thread_event.h
- include/jemalloc/internal/tsd.h
- src/prof.c
- src/prof_data.c
- src/stats.c
- src/tcache.c
- src/thread_event.c
- src/tsd.c
On a logical level, the sample wait time belongs to the thread event module, and should not be determined according to the state of the prof `tdata`. It is a "prof -> thread event" dependency that we should remove. The `tdata` holds the temporary storage space for the backtracing result, so we have to have a valid `tdata` when we determine that we should sample. This is their only relationship, and it's an "allocation caller -> thread event lookahead" dependency followed by an "allocation caller -> `tdata`" dependency, and does not involve any "prof -> thread event" dependency.
However, this dependency was present before the refactoring of #1779, so it could either be truly unnecessary, or it tried to solve some edge cases I failed to consider. Let's see if any tests fail...
> Restructure thread event handling

- src/jemalloc.c
This can be useful when you know you want to override some lower-priority
configuration setting with its default value, but don't know what that value
would be.
> Allow narenas:default.

- include/jemalloc/internal/edata.h
- src/emap.c
- src/extent_dss.c
- test/unit/rtree.c
This avoids some UB. No compilers take advantage of it for now, but no sense in
tempting fate.
> Edata: zero stack edatas before initializing.

- include/jemalloc/internal/quantum.h
This matches the ABI stack alignment requirements.
> LQ_QUANTUM should be 4 on mips64 hardware.

- configure.ac
- src/tcache.c
For some reason, travis runs stopped showing up in the CI pane for a week or two, and so the build looked green despite growing some build errors (none "real" -- integer conversion and initializer syntax ones). This fixes the issues.
> Fix broken CI builds.

- Makefile.in
- doc/jemalloc.xml.in
- include/jemalloc/internal/peak.h
- include/jemalloc/internal/peak_event.h
- include/jemalloc/internal/thread_event.h
- include/jemalloc/internal/tsd.h
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj.filters
- src/ctl.c
- src/peak_event.c
- src/thread_event.c
- test/unit/mallctl.c
- test/unit/peak.c
This resolves https://github.com/jemalloc/jemalloc/issues/1850 and https://github.com/jemalloc/jemalloc/pull/1176 .
Note that this doesn't (or at least, shouldn't) change fast paths at all -- we share the thread-event counter except during updates.
> Add (approximate) per-thread peak memory tracking

- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/jemalloc_internal_externs.h
- include/jemalloc/internal/jemalloc_preamble.h.in
- include/jemalloc/internal/nstime.h
- src/ctl.c
- src/jemalloc.c
- src/large.c
- src/nstime.c
- src/prof_log.c
- src/prof_recent.c
- test/unit/arena_decay.c
- test/unit/nstime.c
The approach taken is to provide a distinct nstime_update() for profiling code which can provide a high or coarse (normal) resolution resolution timestamp. The choice to provide a new and distinct nstime_update()  Which timestamp is provided depends upon the setting of the new profiling parameter, 'prof_time_resolution', which currently has two settings:
prof_time_resolution: default
prof_time_resolution: high
A setting of 'high' gives a high resolution timestamp which on modern Linux platforms has a nonosecond resolution. The default setting is currently 1 millisecond.
Note that this feature is currently only enabled for the Linux platform. The current implementation will allow a non-Linux platform to specify 'prof_time_resolution:default' as a parameter but
'prof_time_resolution:high' …
> Add a high resolution timestamp option for profiling

- src/jemalloc.c
This PR aims at removing redundant logic for flag reading and processing, and making the resulting code more readable and less error prone. It's also a preparation for #1828.
Also fixed a few issues along the way.
> Simplify flag reading and processing

- include/jemalloc/internal/witness.h
This lets us avoid having to increment a bunch of values manually every time we
add a new sort of lock.
> Witness: Make ranks an enum.

- include/jemalloc/internal/arena_structs.h
- include/jemalloc/internal/bin.h
- include/jemalloc/internal/edata.h
- include/jemalloc/internal/edata_cache.h
- include/jemalloc/internal/eset.h
- include/jemalloc/internal/typed_list.h
- src/arena.c
- src/bin.c
- src/edata_cache.c
- src/eset.c
- src/extent.c
- src/large.c
- src/pa.c
Inactive edatas have lots of spare space, while active ones never simultaneously need both their ql and ph linkages. So have the former edatas use the spare space for their linkage, have the latter ones share the linkages.
This space will go towards hugepages shortly.
> Edata: Squeeze out some spare space

- src/tcache.c
In making these settings configurable, 634afc4124100b5ff11e892481d912d56099be1a
unintentially changed a tuning parameter (reducing the "goal" max by a factor of
4).  This commit undoes that change.
> Tcache: Tweak nslots_max tuning parameter.

- Makefile.in
- include/jemalloc/internal/arena_externs.h
- include/jemalloc/internal/arena_inlines_b.h
- include/jemalloc/internal/atomic.h
- include/jemalloc/internal/background_thread_inlines.h
- include/jemalloc/internal/ctl.h
- include/jemalloc/internal/extent.h
- include/jemalloc/internal/pa.h
- include/jemalloc/internal/pac.h
- include/jemalloc/internal/pai.h
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj.filters
- src/arena.c
- src/background_thread.c
- src/ctl.c
- src/extent.c
- src/extent_dss.c
- src/pa.c
- src/pa_extra.c
- src/pac.c
- test/unit/pa.c
- test/unit/retained.c
This introduces, PAI "page allocator interface", which abstracts over the underlying page-level operations that interest us. It then pulls out the extent selection functionality in PA into PAC, "page allocator classic".
Right now neither of these is terribly well motivated; they're part of a larger-scale plan:
The PAI interface will allow adding a cache of small extents, that can be used to take pressure off the central extent allocator's lock; the interface allows testing the cache independently of all the underlying allocator functionality.
Pulling out the PA logic into PAC will make it easier to shim in a hugepage-allocator.
> Introduce a couple more PA-named modules.

- doc/jemalloc.xml.in
- src/ctl.c
Added the `VERIFY_READ()` utility in `ctl.c` to verify that the output space is enough, and use it in a few places where the work is heavy and is not read-only, e.g. creating tcache / arena.
> Verify output space before doing heavy work in mallctl

- Makefile.in
- test/stress/batch_alloc.c
We care about the performance of the batch allocation API, so I added some stress tests. I designed two tests:
- Allocations + frees: the real usage.
- Allocations only: the raw performance of the batch allocation API. (It's hard to repeat so the test runs only once but the size is made to be huge.)
Test result:
```
=== test/stress/batch_alloc ===
100 iterations, batch allocation=1571046us, item allocation=2022060us, ratio=1:0.777
test_small_batch_with_free (non-reentrant): pass
1 iterations, batch allocation=765022us, item allocation=1214036us, ratio=1:0.630
test_huge_batch_without_free (non-reentrant): pass
```
This is when profiling is on. Turning off profiling doesn't affect the result in any significant way.
> Add a stress test for batch allocation

- Makefile.in
- include/jemalloc/internal/prof_externs.h
- include/jemalloc/internal/prof_structs.h
- src/jemalloc.c
- src/prof.c
- src/prof_data.c
- src/prof_sys.c
- test/analyze/prof_bias.c
This fixes a longstanding issue: the combination of jemalloc and jeprof should be unbiasing-then-summing, but instead we were summing-then-unbiasing. This could lead to incorrect heap usage and object counts to stacks when those stacks are responsible for a wide range of allocation sizes. Included in this PR is a fairly primitive test program to demonstrate the issue.
When running the program on the first commit alone:
```
[~/jemalloc]$ MALLOC_CONF="prof:true,prof_final:true" test/analyze/prof_bias
[~/jemalloc]$ jeprof --text test/analyze/prof_bias --inuse_space jeprof.*
Using local file test/analyze/prof_bias.
Using local file jeprof.2343139.0.f.heap.
Total: 828.5 MB
828.5 100.0% 100.0%    828.5 100.0% jet_tsd_tls
[~/jemalloc]$ jeprof --text test/analyze/prof_bias --inuse_objects …
```
> Profiling: work around a biasing issue.

- Makefile.in
- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/jemalloc_preamble.h.in
- src/jemalloc.c
- src/safety_check.c
- test/unit/size_check.c
This is fairly expensive on the sized deallocation pathways, so it can't be part of the regular opt safety checks. But it's handy to have around in cases where those checks have found that a bug exists but haven't pinpointed it.
> Add a debug mode: sized-deallocation checking

- src/arena.c
- test/integration/rallocx.c
Before this change, the snippet
```
tsdn_t *tsdn = tsdn_fetch();
void *p = mallocx(7, MALLOCX_ALIGN(64));
malloc_printf("isalloc(tsdn, p) = %zu\n", isalloc(tsdn, p));
p = rallocx(p, 57, MALLOCX_ALIGN(128));
malloc_printf("isalloc(tsdn, p) = %zu\n", isalloc(tsdn, p));
free(p);
```
yields
```
isalloc(tsdn, p) = 64
isalloc(tsdn, p) = 64
```
After this change, it yields
```
isalloc(tsdn, p) = 64
isalloc(tsdn, p) = 128
```
> Fix size miscalculation bug in reallocation

- include/jemalloc/internal/jemalloc_preamble.h.in
The commit introducing size checks accidentally enabled them whenever any safety
checks were on.  This ends up causing the regression that splitting up the
features was intended to avoid.  Fix the issue.
> Config: safety checks don't imply size checks.

- src/jemalloc.c
This allows setting arenas per cpu dynamically, rather than forcing the user to
know the number of CPUs in advance if they want a particular CPU/space tradeoff.
Practically, I want this mostly for running my own tuning experiments, rather than because I think end-users should be tweaking it on their own. Leaving it undocumented for now; we can always declare it to be supported later.
The way this sets things up, an explicit narenas setting (of a value other than "default") will still override an narenas_ratio setting (basically saying that the more specific attempt to set wins). This feels right to me; narenas_ratio is setting the default ratio. You can still get the equivalent behavior by setting "narenas:default" at the same time you set the ratio if you don't want this behavior.
> Add narenas_ratio.

- Makefile.in
- src/malloc_io.c
- test/include/test/bench.h
- test/stress/mallctl.c
- test/unit/malloc_io.c
The backstory here is that I was curious of how fast mallctl interfaces were. I wrote a little stress test to determine how fast it was. Then I got frustrated that I couldn't easily read that speed, so I added the ns/iter functionality. Doing that requires the ability to 0-pad.
> Stress tests: cleanups, and a mallctl test.

- test/stress/mallctl.c
The mallctlbymib_long helper was copy-pasted from mallctlbymib_short, and
incorrectly used its output variable (a char *) rather than the output variable
of the mallctl call it was using (a uint64_t), causing breakages when
sizeof(char *) differed from sizeof(uint64_t).
> Mallctl stress test: fix a type.

- Makefile.in
- include/jemalloc/internal/ecache.h
- include/jemalloc/internal/geom_grow.h
- include/jemalloc/internal/pac.h
- src/ecache.c
- src/extent.c
- src/geom_grow.c
- src/pa_extra.c
- src/pac.c
- test/unit/retained.c
We'll need the same functionality soon for a hugepage allocator elsewhere.
> Move the grow_retained helpers out of PAC

- include/jemalloc/internal/prof_data.h
- include/jemalloc/internal/prof_externs.h
- include/jemalloc/internal/prof_types.h
- src/prof.c
- src/prof_data.c
Save a few KB for non-prof builds. I'm planning to add some more size class related tables for internal fragmentation tracking, so the saving can be more.
> Do not create size class tables for non-prof builds

- include/jemalloc/internal/prof_inlines.h
The saving is tiny; more for correctness, since reentrancy is handled in the thread event module.
> Do not repeat reentrancy test in profiling

- src/prof.c
The `szind` being computed earlier might have been smaller if the request was a small size plus a large alignment.
> Fix szind computation in profiling

- INSTALL.md
- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/sc.h
We may get better performance from larger slab sizes. Currently, there is a malloc_conf `slab_sizes` to set the default slab sizes. But it is limited by `lg-slab-maxregs`, which means the maximum number of regions in a slab.
This patch adds a new configure `--with-lg-slab-maxregs`, which allows to override the default `lg-slab-maxregs`, which is `<lg-page> - <lg-tiny-min>`. The value should not be less than the default value. The max value of this option is related to `LG_BITMAP_MAXBITS` (see more in bitmap.h).
For example, on a 4k page size system, if we:
1) configure jemalloc with with `--with-lg-slab-maxregs=12`.
2) `export MALLOC_CONF="slab_sizes:9-16:4"`
The slab size of 16 bytes is set to 4 pages. Previously, the default lg-slab-maxregs is `9 (i.e. 12 - 3)`. The max slab size of 16 …
> RFC: allow to specify larger slab sizes

- INSTALL.md
- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/sc.h
The variable slab sizes feature is still experimental; we don't want people to
start using it willy-nilly, or document its existence as a guarantee.
For some reason, the rebased version triggered some failures that the original PR didn't. Work around a triggered -Wundef issue.
> Remove --with-slab-maxregs options from INSTALL.md

- Makefile.in
- include/jemalloc/internal/edata.h
- include/jemalloc/internal/flat_bitmap.h
- include/jemalloc/internal/psset.h
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj.filters
- src/emap.c
- src/extent.c
- src/extent_dss.c
- src/psset.c
- test/unit/flat_bitmap.c
- test/unit/psset.c
- test/unit/rtree.c
- test/unit/slab.c
A page-slab is a new type of edata (using a bitset to hold pages rather than objects within a page). A page-slab set (psset for short) maintains a set of pageslabs that can be used to satisfy allocation requests. This has no external uses yet; rather, it's a component of a forthcoming hugepage-centric allocator (HPA for short; another implementation of PAI). I'm trying to avoid a huge stack of commits later on, by adding components piecemeal and allowing in-parallel review.
What the eset is to the PAC, the psset is to the HPA.
> Introduce a new abstraction; a page slab set

- .clang-format
- scripts/check-formatting.sh
This will let us opt-in files incrementally, as we transition over. My plan is to merge this (currently testing nothing), add a CI test asserting that the script passes, and then clang-format most of the rest of the repository, adding the reformatted files to 
I manually reflowed comments in a couple of files yesterday, but I'll definitely get some sort of RSI if I continue; instead my thought is that we can leave comments as-is for now, and reflow as we touch surrounding code. I also figure we can hold off on clang-formatting any files someone has big changes to that will trigger merge-conflicts (but please let me know if so).
I picked clang-format version 8 as the version we use, as suggested in the previous iteration of this PR. This is available on our CI hosts, and is the system …
> Add a clang-format file, and a script to check for formattedness

- .appveyor.yml
This is no longer required, and the step now fails.
> Appveyor: don't update msys2 keyring.

- Makefile.in
- include/jemalloc/internal/emap.h
- include/jemalloc/internal/hpa_central.h
- include/jemalloc/internal/prng.h
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj.filters
- src/emap.c
- src/extent.c
- src/hpa_central.c
- test/unit/hpa_central.c
- test/unit/prng.c
This is another step towards the implementation of a design for a hugepage allocator. It introduces the hpa_central_t; a global extent allocator intended to work in tandem with the psset allocator in https://github.com/jemalloc/jemalloc/pull/1904.
That allocator can serve requests of up to a few hundred pages. Another source of pages is still necessary, though, both to supply the psset allocator as well as to serve larger allocations. This serves that purpose.
This is not a complete implementation of the page allocation interface yet; it can't handle aligned allocations, return zeroed memory, or shrink or expand allocations. These may come with time, or we may simply rely on the PAC for those use cases. I'd rather be able to iterate more quickly than try to be feature-complete in an …
> Add a component for a hugepage-centric allocator

- src/jemalloc.c
- src/sc.c
This comes in handy when overriding earlier settings to test alternate ones.  We
don't really include tests for this, but I claim that's OK here:
- It's fairly straightforward
- It's fairly hard to test well
- This entire code path is undocumented and mostly for our internal
experimentation in the first place.
- I tested manually.
> Add "default" option to slab sizes.

- doc/jemalloc.xml.in
- include/jemalloc/internal/tcache_structs.h
- include/jemalloc/internal/tcache_types.h
- src/tcache.c
For locality reasons, tcache bins are integrated in TSD.  Allowing all size
classes to be cached has little benefit, but takes up much thread local storage.
In addition, it complicates the layout which we try hard to optimize.
> Add a hard limit on tcache max size class.

- src/prof_recent.c
What I have for now may or may not work: it depends on the integrity of the `tdata` the `tctx` points to. I saw some cautioning comments:
https://github.com/jemalloc/jemalloc/blob/be9548f2bef30b75294fdd0eb6721d1bf6e6a56a/include/jemalloc/internal/prof_structs.h#L47-L52
I think the `tdata` should be living nicely as long as it has a positive number of associated `tctx`s? Does the "teardown" in that comment mean program exit, e.g. mainly for the `prof_final` case? Let me also see if any tests may fail...
> Add thread name in prof last-N records

- Makefile.in
- doc/jemalloc.xml.in
- include/jemalloc/internal/cache_bin.h
- include/jemalloc/internal/tcache_inlines.h
- src/cache_bin.c
- src/tcache.c
- test/unit/arena_decay.c
- test/unit/arena_decay.sh
- test/unit/tcache_max.c
- test/unit/tcache_max.sh
Previously all the small size classes were cached.  However this has downsides
-- particularly when page size is greater than 4K (e.g. iOS), which will result
in much higher SMALL_MAXCLASS.
This change allows tcache_max to be set to lower values, to better control
resources taken by tcache.
> Allow opt.tcache_max to accept small size classes

- .appveyor.yml
It looks like the mirrors we were using no longer carry this package, but that
it is installed by default and so no longer needs a remote mirror.
> Appveyor: fix 404 errors.

- configure.ac
These are detected at configure time while they are glibc
specifics. the bionic equivalent is not api compatible
and dlopen is restricted in this platform.
> Android build fix proposal.

- include/jemalloc/internal/activity_callback.h
- include/jemalloc/internal/tsd.h
- src/ctl.c
- src/peak_event.c
- test/unit/mallctl.c
This (experimental, undocumented) functionality can be used by users to track various statistics of interest at a finer level of granularity than the thread.
The intended use case is things like peak tracking, but on a per-request basis.
> Add experimental.thread.activity_callback.

- include/jemalloc/internal/edata_cache.h
- include/jemalloc/internal/hpa.h
- include/jemalloc/internal/hpa_central.h
- src/edata_cache.c
- src/hpa.c
- src/hpa_central.c
- src/pa.c
- test/unit/edata_cache.c
The intent with the HPA is to run with fewer arenas, to the point that contention on the edata_cache_ts becomes observable. This PR rewrites the edata_cache_small_t in response to the design evolution that's happened since it was introduced, sprinkles usages into the HPA.
> Cache edatas in the HPA

- Makefile.in
- include/jemalloc/internal/exp_grow.h
- include/jemalloc/internal/hpa.h
- include/jemalloc/internal/pac.h
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj.filters
- src/exp_grow.c
- src/extent.c
- src/geom_grow.c
- src/hpa.c
- src/pac.c
- test/unit/retained.c
This was promised in the review of the introduction of geom_grow, but would have
been painful to do there because of the series that introduced it.  Now that
those are comitted, renaming is easier.
> Rename geom_grow -> exp_grow.

- Makefile.in
- include/jemalloc/internal/pa.h
- include/jemalloc/internal/pac.h
- src/arena.c
- src/ctl.c
- src/extent.c
- src/pa.c
- src/pac.c
- test/unit/oversize_threshold.c
- test/unit/pa.c
This can let manual arenas trade off memory and CPU the way auto arenas do.
> Add a per-arena oversize_threshold.

- src/prof_recent.c
- test/unit/prof_recent.c
This is a request from our collaborator team. Also, in itself, the sample interval is a crucial piece of information for any user to properly interpret the last-N records.
> Add sample interval to prof last-N dump

- include/jemalloc/internal/cache_bin.h
- src/cache_bin.c
- src/jemalloc.c
- test/unit/batch_alloc.c
- test/unit/cache_bin.c
For batch allocation requests of small sizes, instead of going to the page allocator for a fresh new slab, follow the ordinary hierarchy i.e. tcache -> arena -> page allocator, to improve performance. The downside is of course memory locality; however, locality was originally a best effort anyway.
A few remarks on the current version:
- I don't yet have a great way to determine the size threshold for deciding which route ("tcache route" / "page allocator route") the request should go through. Right now I just put an arbitrary number as a placeholder. I think there are a few aspects we need to consider here:
- Improvement on performance. If we plot the difference in performance between the two routes against the batch size, then I imagine there are two big jumps: one is around the point at …
> Route batch allocation of small batch size to tcache

- bin/jeprof.in
This patch backports the `--collapsed` flag that was added to pprof ([source](https://github.com/gperftools/gperftools/blob/master/src/pprof)) for generating [flamegraphs](https://github.com/brendangregg/FlameGraph).
See https://github.com/gperftools/gperftools/commit/6ce10a2a05f13803061538d5c77e89695de59be4 for the original commit by @matt-cross.
Usage:
```
jeprof <binary> <profile> --collapsed | flamegraph.pl > flamegraph.svg
```
Sample flamegraph (generated with `flamegraph.pl --reverse --invert --minwidth 3`):
[flamegraph.reverse.svg.gz](https://github.com/jemalloc/jemalloc/files/5575179/flamegraph.reverse.svg.gz)
This is a nice way of visualizing stacks that can be a bit more straight-forward to parse when compared to callgraphs.
> Backport jeprof --collapsed for flamegraph generation

- Makefile.in
- include/jemalloc/internal/fxp.h
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj.filters
- src/fxp.c
- src/jemalloc.c
- test/unit/fxp.c
There's no fundamental reason this ratio ought to be an integer. With the HPA allowing (and benefitting from) much lower arena counts, this has become a day-to-day pain. Setting the number of arenas to (say) half the number of CPUs is hard to do without knowing the environment you'll run on.
> Allow fractional settings for narenas_ratio.

- src/background_thread.c
Reported in:
https://github.com/jemalloc/jemalloc/issues/1334
>> CID 17475 (#1 of 1): Side effect in assertion (ASSERT_SIDE_EFFECT)
>> assert_side_effect: Argument n_search++ of assert() has a side effect. The containing function might work differently in a non-debug build.
191                assert(n_search++ < lg_floor(SMOOTHSTEP_NSTEPS) + 1);
> Move n_search outside of assert as reported by static analyzer

- test/stress/batch_alloc.c
There are several changes:
- Added a tiny batch size, since the batch allocation API is not only intended for huge batch size.
- Removed the very huge batch size, since there isn't any major insight we can get from that.
- Wrote two versions for both the tiny and huge batch size: one with free and one without free. The benchmark results from both versions can be useful.
- Added a "memory warmup" phase before every test. In contrast to the "CPU warmup" phase that's already in our benchmark system, this "memory warmup" phase ensures that there is enough dirty pages before every test run. Without such a "memory warmup" phase, I observed that the benchmark results could vary significantly depending on the amount of dirty pages available before the test run; for example, the result would be …
> Improve batch allocation stress test

- include/jemalloc/internal/ctl.h
- src/ctl.c
- src/stats.c
- test/unit/mallctl.c
My original goal was to facilitate `malloc_stats_print()`, which needs to iterate through a giant `mallctl` command tree. Currently everything is done via an inefficient `mallctl()` call. The `mallctlbymib()` handle was designed to improve efficiency, but it's unfortunately difficult to use in `malloc_stats_print()`. This stack of commits makes it possible for `malloc_stats_print()` to easily enjoy the performance close to `mallctlbymib()`. I'm somewhat lazy to work on the actual change for `malloc_stats_print()` right now; will try to do it at a later time.
> Some optimizations for mallctl

- src/stats.c
The output for bin stats does not have rows with no data any more; before this change, such rows exist in the output and there would be `---` lines after them whenever the next row was not empty. The output for large sizes stays the same; this change just serves to short-circuit early.
> Omit stats rows with no data

- include/jemalloc/internal/mutex_prof.h
- src/ctl.c
(Did not add the entries to the documentation because the last-N profiling mode itself is not yet documented.)
> Add last-N mutex stats

- include/jemalloc/internal/sz.h
- src/arena.c
I started this change with a much greater ambition, to make some significant improvement to the `sz_sa2u()` computations, but through some trials and errors, I came to better understand how things work and ended up with this tiny change.
> Do not bump to large size for page aligned request

- configure.ac
- include/jemalloc/jemalloc_defs.h.in
- include/jemalloc/jemalloc_macros.h.in
- src/jemalloc.c
- src/malloc_io.c
- src/prof_log.c
- src/prof_recent.c
- src/stats.c
- test/unit/prof_log.c
This change implements a few binary size reductions:
- Even when stats and profiling are disabled, some of those functions still get included. Adding a cassert tells the compiler they're unreachable, and lets them be optimized into no-ops.
- Marking cold functions as cold treats them as such, including some space-saving optimizations. For now, the definition of cold is fairly conservative (basically, things that are manually-triggered, or can only happen once; things like prof_lookup aren't counted as cold, even though they arguably are).
- Allowing code reuse between realloc and rallocx (by removing the force inline) saves nontrivial space overhead. This does cost slightly more CPU (since we have to parse a constant 0 flag), but that's quite cheap in practice, especially given that the …
> Binary space optimizations

- include/jemalloc/internal/cache_bin.h
- src/arena.c
- src/cache_bin.c
- src/tcache.c
- test/unit/cache_bin.c
This fixes an incorrect debug-mode assert:
- T1 starts an arena stats update and reads stack_head from another thread's
cache bin, when that cache bin has 1 item in it.
- T2 allocates from that cache bin.  The cache_bin's stack_head now points to a
NULL pointer, since the cache bin is empty.
- T1 Re-reads the cache_bin's stack_head to perform an assertion check (since it
previously saw that the bin was empty, whatever stack_head points to should be
non-NULL).
> cache_bin: Separate out local and remote accesses.

- build-aux/config.guess
- build-aux/config.sub
Fixes #2010 
This is intentionally against master to allow for a 5.2.2 release to simply add support for building there without patching. I can do the same PR against `dev` to also update the files there to the same revision.
> Update config.{sub,guess} to support support-aarch64-apple-darwin as a target

- doc/jemalloc.xml.in
- include/jemalloc/internal/jemalloc_internal_externs.h
- src/ctl.c
- src/jemalloc.c
- src/pages.c
- test/unit/mallctl.c
qemu does not support this, yet [1], and you can get very tricky assert
if you will run program with jemalloc in use under qemu:
<jemalloc>: ../contrib/jemalloc/src/extent.c:1195: Failed assertion: "p[i] == 0"
[1]: https://patchwork.kernel.org/patch/10576637/
Here is a simple example that shows the problem [2]:
// Gist to check possible issues with MADV_DONTNEED
// For example it does not supported by qemu user
// There is a patch for this [1], but it hasn't been applied.
//   [1]: https://lists.gnu.org/archive/html/qemu-devel/2018-08/msg05422.html
#include <sys/mman.h>
#include <stdio.h>
#include <stddef.h>
#include <assert.h>
#include <string.h>
int main(int argc, char **argv)
{
void *addr = mmap(NULL, 1<<16, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0);
if (addr == …
> [RFC] Add runtime detection for MADV_DONTNEED zeroes pages (mostly for qemu)

- include/jemalloc/internal/jemalloc_internal_externs.h
- include/jemalloc/internal/jemalloc_internal_inlines_c.h
- include/jemalloc/internal/jemalloc_internal_types.h
- src/jemalloc.c
- src/jemalloc_cpp.cpp
This saves a small but non-negligible amount of CPU in C++ programs.
> Inline malloc fastpath into operator new.

- src/stats.c
Seems like this option was changed here: c8209150f9d219a137412b06431c9d52839c7272
And maybe this got missed.
> Fix stats for "tcache_max" (was "lg_tcache_max")

- INSTALL.md
- doc/jemalloc.xml.in
- include/jemalloc/internal/jemalloc_internal_externs.h
- include/jemalloc/internal/prof_inlines.h
- include/jemalloc/internal/sz.h
- src/ctl.c
- src/jemalloc.c
- src/large.c
- src/stats.c
- src/sz.c
- test/unit/extent_quantize.c
- test/unit/mallctl.c
Add `opt.cache_oblivious` to make the option runtime configurable. Keep `config.cache_oblivious` for now to remain backward-compatible.
> Implement opt.cache_oblivious.

- INSTALL.md
'autoconf' needs to be installed for './autogen.sh' to work.
> Update INSTALL.md to mention 'autoconf'

- include/jemalloc/internal/extent.h
- src/extent.c
When retain is on, when extent_grow_retained failed (e.g. due to split hook
failures), we'll try extent_alloc_wrapper as the last resort.  Set the is_head
bit in that case to be consistent.  The allocated extent in that case will be
retained properly, but not merged with other extents.
> Set is_head in extent_alloc_wrapper w/ retain.

- src/extent_dss.c
Specifically, the extent_dalloc_gap relies on the correct head state to
coalesce.
> Mark head state during dss alloc.

- src/ctl.c
The ctl_mtx should be held to protect against concurrent arenas.create.
> Fix locking on arena_i_destroy_ctl().

- doc/jemalloc.xml.in
Hi,
Fix the doc error of `54 KiB` to `56 KiB` cause the spacing is 8 KiB.
Thanks.
> Fix doc large size 54 KiB error

- include/jemalloc/internal/pac.h
Remove redundant declaration, pac_retain_grow_limit_get_set was declared twice in pac.h.
> duplicated declare pac_retain_grow_limit_get_set

- test/unit/prof_recent.c
- test/unit/prof_thread_name.c
When both of these are enabled, the output format changes slightly.  Teach the
unit test about the interaction.
> Fix a prof_recent/prof_sys_thread_name interaction

- bin/jeprof.in
Improved jeprof's ability to find installed debug symbol packages based on https://stackoverflow.com/a/64038064/370707
```
apt install -y openjdk-8-jdk
$ cat HelloWorld.java 
public class HelloWorld {
public static void main(String[] args) {
// Prints "Hello, World" to the terminal window.
System.out.println("Hello, World");
}
}
$ javac HelloWorld.java
$ export LD_PRELOAD=/usr/lib/libjemalloc.so
 $ export MALLOC_CONF=prof:true,lg_prof_interval:20,prof_prefix:/tmp/jemalloc-java
$ java HelloWorld 
$ export LD_PRELOAD=
$ apt install -y openjdk-8-dbg
$ dpkg -L openjdk-8-dbg
...
/usr/lib/debug/.build-id/03/17f517a518dee47febb310f62e609737e1dc63.debug
...
/usr/lib/debug/.build-id/05/73a57ddc18e75eecd35598cc9bbb68d0110a80.debug
...
$ jeprof |& grep debug-syms
--debug-syms-by-id  (Linux only) …
```
> Added --debug-syms-by-id option

- .gitignore
- Makefile.in
- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/jemalloc_internal_externs.h
- include/jemalloc/internal/jemalloc_preamble.h.in
- src/jemalloc.c
- src/jemalloc_cpp.cpp
- src/stats.c
- test/integration/cpp/basic.cpp
- test/integration/cpp/infallible_new_false.cpp
- test/integration/cpp/infallible_new_false.sh
- test/integration/cpp/infallible_new_true.cpp
- test/integration/cpp/infallible_new_true.sh
This allows a guarantee that operator new never throws, without the heavyweight option of turning on xmalloc.
Fix the .gitignore rules to include test/integration/cpp while we're here.
> Add opt.experimental_infallible_new.

- Makefile.in
- include/jemalloc/internal/mpsc_queue.h
- test/unit/mpsc_queue.c
This is a simple multi-producer, single-consumer queue.  The intended use case
is in the HPA, as we begin supporting hpdatas that move between hpa_shards.  We
take just a single CAS as the cost to send a message (or a batch of messages) in
the low-contention case, and lock-freedom lets us avoid some lock-ordering
issues.
> mpsc_queue: Add module.

- src/hpa.c
- src/jemalloc.c
This fixes two simple but significant typos in the HPA batch_alloc_extra settings:
- The conf string parsing accidentally set a min value of PAGE for
hpa_sec_batch_fill_extra; i.e. allocating 4096 extra pages every time we
attempted to allocate a single page.  This puts us over the SEC flush limit,
so we then immediately flush all but one of them (probably triggering
purging).
- The HPA was using the default PAI batch alloc implementation, which meant it
did not actually get any locking advantages.
This snuck by because I did all the performance testing without using the PAI
interface or config settings.  When I cleaned it up and put everything behind
nice interfaces, I only did correctness checks, and didn't try any performance
ones.
> HPA: Fix typos with big performance implications.

- .travis.yml
- scripts/gen_travis.py
On OS X, "gcc" is really just clang anyways, so this combination gets tested by
the gcc test.  This is purely redundant, and (since it runs early in the output)
increases time to signal for real breakages further down in the list.
> Travis: Don't test "clang" on OS X.

- Makefile.in
- include/jemalloc/internal/arena_externs.h
- include/jemalloc/internal/background_thread_externs.h
- include/jemalloc/internal/background_thread_structs.h
- include/jemalloc/internal/hpa.h
- include/jemalloc/internal/hpa_hooks.h
- include/jemalloc/internal/hpa_opts.h
- include/jemalloc/internal/hpdata.h
- include/jemalloc/internal/pa.h
- include/jemalloc/internal/psset.h
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj.filters
- src/arena.c
- src/background_thread.c
- src/ctl.c
- src/hpa.c
- src/hpa_hooks.c
- src/hpdata.c
- src/jemalloc.c
- src/pa.c
- src/psset.c
- src/stats.c
- test/unit/hpa.c
- test/unit/hpa_background_thread.c
- test/unit/hpa_background_thread.sh
- test/unit/hpdata.c
- test/unit/psset.c
This makes the HPA's interactions with the OS more efficient, both in terms of tail-latency hit on application threads and on the absolute number of system calls performed:
- Moves deferred operations onto background threads where possible. Since the time until purging is necessary is fuzzier with the HPA than with the PAC, we just check for deferred operations whenever the background thread touches the PA shard, and impose a max time interval between background thread wakeups when the HPA is active.
- Allow "re-purging" retained extents if it lets us do two purge operations in a single call.
- Purge empty extents first (these will never be chosen for a new allocation unless we have no other choice, so they're less likely to be reused).
- Delay hugification until we're reasonably …
> HPA system interaction scalability improvements

- include/jemalloc/internal/edata_cache.h
- include/jemalloc/internal/hpa.h
- src/edata_cache.c
- src/hpa.c
- test/unit/edata_cache.c
The edata_cache_small had a fill/flush heuristic.  In retrospect, this was a
premature optimization; more testing indicates that an unbounded cache is
effectively fine here, and moreover we spend a nontrivial amount of time doing
unnecessary filling/flushing.
As the HPA takes on a larger and larger fraction of all allocations, any
theoretical differences in allocation patterns should shrink.  The HPA is more
efficient with its metadata in general, so it still comes out ahead on metadata
usage anyways.
> edata_cache: Allow unbounded fast caching.

- include/jemalloc/internal/edata.h
- include/jemalloc/internal/eset.h
- include/jemalloc/internal/hpdata.h
- include/jemalloc/internal/ph.h
- src/edata.c
- src/eset.c
- src/hpdata.c
- test/unit/ph.c
Some of our hottest operations are in the edata heaps, and some of our hottest locks guard those operations. This PR optimizes various of those pathways.
Most of these are fairly straightforward. The most significant one is in the ph aux-list counting diff, which is fairly straightforward even though the reasoning and investigation work going into it is fairly subtle.
The perf situation here is complicated; these changes improve CPU consumption by a modest amount in canary testing. But since these functions tend to get hotter over time, it's hard to find the exact improvement. So the true benefit could be anything from "a negligible amount" to something quite large.
> Pairing heap optimizations

- include/jemalloc/internal/mutex.h
- src/ctl.c
- src/jemalloc.c
- src/mutex.c
- src/stats.c
Don't document it since we don't want to support this as a "real" setting, but
it's handy for testing.
> Mutex: Make spin count configurable.

- src/mutex.c
The recent pairing heap optimizations flattened the lock hold time profile.
This was a win for raw cycle counts, but ended up causing us to "just miss"
acquiring the mutex before sleeping more often.  Bump those counts.
> Mutex: Tweak internal spin count.

- src/hpa.c
- src/pa.c
This change eliminates the possibility of PA calling functions of uninitialized
HPA.
> Verify that HPA is used before calling its functions

- .cirrus.yml
Contains 16 testing configs -- a mix of debug, prof, -m32 plus a few uncommon options.
This helps our FreeBSD coverage.
> Add Cirrus CI testing matrix

- doc/jemalloc.xml.in
- include/jemalloc/internal/prof_sys.h
- src/ctl.c
- src/prof_sys.c
- test/unit/prof_idump.c
This better aligns with our naming convention.  The option has not been included
in any upstream release yet.
> Rename prof.dump_prefix to prof.prefix

- configure.ac
When clang sees an unknown warning option, unlike gcc it doesn't fail the build
with error. It issues a warning. Hence JE_CFLAGS_ADD with warning options that
didnt't exist in clang would still mark those options as available. This led to
several warnings when built with clang or "gcc" on OSX. This change fixes those
warnings by simply making clang fail builds with non-existent warning options.
> Fix warnings when compiled with clang

- include/jemalloc/internal/hpdata.h
Retained pages are those which haven't been touched and are unbacked from OS
perspective. For a pageslab their number should equal "total pages in slab"
minus "touched pages".
> HPA: Correctly calculate retained pages

- src/ctl.c
- src/prof.c
- test/unit/mallctl.c
The prof initialization is done only when opt_prof is true.  This change makes
sure the prof_* mallctls only have limited read access (i.e. no access to prof
internals) when opt_prof is false.
In addition, initialize the global prof mutexes even if opt_prof is false.  This
makes sure the mutex stats are set properly.
> Guard prof related mallctl with opt_prof.

- Makefile.in
- include/jemalloc/internal/prof_externs.h
- include/jemalloc/internal/prof_hook.h
- include/jemalloc/internal/prof_structs.h
- include/jemalloc/internal/prof_sys.h
- src/ctl.c
- src/prof.c
- src/prof_sys.c
- test/analyze/prof_bias.c
- test/unit/prof_hook.c
- test/unit/prof_hook.sh
Existing backtrace implementations skip native stack frames from runtimes like
Python. Backtrace hook allows to augment the backtraces to attribute allocations to
native functions in heap profiles.
Dump hook allows users to dump their symbol mappings to resolve addresses they added to backtraces.
> Implement prof hooks

- include/jemalloc/internal/arena_externs.h
- include/jemalloc/internal/arena_types.h
- include/jemalloc/internal/base.h
- include/jemalloc/internal/base_structs.h
- include/jemalloc/internal/jemalloc_internal_externs.h
- include/jemalloc/internal/jemalloc_internal_inlines_a.h
- src/arena.c
- src/base.c
- src/ctl.c
- src/jemalloc.c
- test/integration/extent.c
- test/unit/base.c
- test/unit/edata_cache.c
- test/unit/hpa.c
- test/unit/pa.c
- test/unit/rtree.c
- test/unit/sec.c
This mallctl accepts an arena_config_t structure which
can be used to customize the behavior of the arena.
Right now it contains extent_hooks and a new option,
metadata_use_hooks, which controls whether the extent
hooks are also used for metadata allocation.
The medata_use_hooks option has two main use cases:
1. In heterogeneous memory systems, to avoid metadata
being placed on potentially slower memory.
2. Avoiding virtual memory from being leaked as a result
of metadata allocation failure originating in an extent hook.
Closes #2095 
---
This is more of an RFC than anything else. I'm not entirely sure if adding this option is the right thing to do to solve the underlying problem. We want to use jemalloc extent hooks to allocate from a file-based DAX* mapping, which initially appeared to …
> add experimental.arenas_create_ext mallctl

- src/arena.c
- src/hpa.c
- src/large.c
- src/pa.c
- src/pac.c
- src/sec.c
- test/unit/hpa.c
- test/unit/pa.c
- test/unit/sec.c
As the code evolves, some code paths that have previously assigned
`deferred_work_generated` may cease being reached. This would leave the value
uninitialized. This change initializes the value for safety.
> Initialize deferred_work_generated

- include/jemalloc/internal/test_hooks.h
- src/prof_sys.c
- test/unit/test_hooks.c
Android build has issues with these defines, this will allow the build to
succeed if it doesn't need to build the tests.
> Redefine functions with test hooks only for tests

- include/jemalloc/internal/guard.h
- src/extent.c
- src/guard.c
When opt_retain is on, slab extents remain guarded in all states, even
retained. This works well if arena is never destroyed, because we
anticipate those slabs will be eventually reused. But if the arena is
destroyed, the slabs must be unguarded to prevent leaking guard pages.
> San: Unguard guarded slabs during arena destruction

- src/ctl.c
W/o the ctl interface, the stats isn't output the option -- the below mallctl is failing:
https://github.com/jemalloc/jemalloc/blob/dev/src/stats.c#L1509
> Add ctl interface for experimental_infallible_new.

- include/jemalloc/internal/hpa_hooks.h
- src/hpa.c
- src/hpa_hooks.c
- test/unit/hpa.c
In order for nstime_update to handle non-monotonic clocks, it requires the input
nstime to be initialized -- when reading for the first time, zero init has to be
done.  Otherwise random stack value may be seen as clocks and returned.
> Fix uninitialized nstime reading / updating on the stack in hpa.

- include/jemalloc/internal/nstime.h
- src/hpa.c
- src/nstime.c
Some nstime_t operations require and assume the input nstime is initialized
(e.g. nstime_update) -- uninitialized input may cause silent failures which is
difficult to reproduce / debug.  Add an explicit flag to track the state
(limited to debug build only).
Also fixed an use case in hpa (time of last_purge).
> Track the initialized state of nstime_t on debug build.

- doc/jemalloc.xml.in
The option has been misleading, because it stays disabled unless
prof_final is also specified. In practice, it's impossible to detect that
the option is silently disabled, because it just doesn't provide any output
as if there are no memory leaks detected.
> Correct opt.prof_leak documentation

- configure.ac
- include/jemalloc/internal/jemalloc_internal_decls.h
seems to have introduced finally more linux api cpu affinity (sched_* family)
compatibility detected at configure time thus adjusting accordingly.
> freebsd 14 build fix proposal.

- src/jemalloc.c
Ensures the malloc_conf "ends with key", "ends with comma" and "malform conf
string" cases abort under abort_conf:true.
> Enforce abort_conf:true when malloc_conf is not fully recognized.

- include/jemalloc/internal/sc.h
- src/jemalloc.c
For sized dealloc, fastpath only handles lookup-able sizes, which must be slabs.
> Mark slab as true on sized dealloc fast path.

- include/jemalloc/internal/base.h
- src/base.c
- test/unit/base.c
Since #2118, jemalloc has the experimental mallctl `experimental.arenas_create_ext`, which allows passing an `arena_config_t` structure, which can be used to customize the behavior of the arena. With this addition, `base_ehooks_get_for_metadata` was also added, which is intended to return the corresponding extend hook functions:
- (1) the user-specified extend hook functions when `metadata_use_hooks` is `true`
- (2) the default extend hook functions when `metadata_use_hooks` is `false`.
However, in case (2), accessing the return value leads to a segmentation fault due to the static cast `(struct ehooks_s *)&ehooks_default_extent_hooks`. Note that `&ehooks_default_extent_hooks` is of type `const extent_hooks_t *`. I'm new to the jemalloc code base, but from my current understanding, this …
> Fix `base_ehooks_get_for_metadata`

- src/jemalloc.c
Determinitic number of CPUs is important for percpu arena to work
correctly, since it uses cpu index - sched_getcpu(), and if it will
greater then number of CPUs bad thing will happen, or assertion will be
failed in debug build:
<jemalloc>: ../contrib/jemalloc/src/jemalloc.c:321: Failed assertion: "ind <= narenas_total_get()"
Aborted (core dumped)
Number of CPUs can be obtained from the following places:
- sched_getaffinity()
- sysconf(_SC_NPROCESSORS_ONLN)
- sysconf(_SC_NPROCESSORS_CONF)
For the sched_getaffinity() you may simply use taskset(1) to run program
on a different cpu, and in case it will be not first, percpu will work
incorrectly, i.e.:
$ taskset --cpu-list $(( $(getconf _NPROCESSORS_ONLN)-1 )) <your_program>
_SC_NPROCESSORS_ONLN uses /sys/devices/system/cpu/online, LXD/LXC …
> [RFC] Disable percpu arena in case of non deterministic CPU count

- include/jemalloc/internal/hpa_hooks.h
- include/jemalloc/internal/nstime.h
- src/hpa.c
- src/hpa_hooks.c
- src/nstime.c
- test/unit/hpa.c
- test/unit/nstime.c
nstime module guarantees monotonic clock update within a single nstime_t.  This
means, if two separate nstime_t variables are read and updated separately,
nstime_subtract between them may result in underflow.  Fixed by switching to the
time since utility provided by nstime.
> Fix the time-since computation in HPA.

- test/unit/hpa_background_thread.c
- test/unit/inspect.sh
- test/unit/mallctl.c
- test/unit/prof_active.sh
- test/unit/prof_hook.sh
- test/unit/prof_log.sh
- test/unit/prof_recent.sh
- test/unit/prof_stats.sh
- test/unit/prof_sys_thread_name.sh
- test/unit/prof_tctx.sh
- test/unit/safety_check.sh
- test/unit/size_check.sh
- test/unit/tcache_max.c
Many profiling related tests make assumptions on the profiling settings,
e.g. opt_prof is off by default, and prof_active is default on when opt_prof is
on.  However the default settings can be changed via --with-malloc-conf at build
time.  Fixing the tests by adding the assumed settings explicitly.
Locally tested with both `prof:true,prof_active:true` and `prof_true,prof_active:false`
> Add the profiling settings for tests explicit.

- Makefile.in
- configure.ac
- include/jemalloc/internal/arena_stats.h
- include/jemalloc/internal/cache_bin.h
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/jemalloc_internal_externs.h
- include/jemalloc/internal/jemalloc_preamble.h.in
- include/jemalloc/internal/san.h
- include/jemalloc/internal/tcache_externs.h
- include/jemalloc/internal/tcache_inlines.h
- src/arena.c
- src/cache_bin.c
- src/ctl.c
- src/jemalloc.c
- src/san.c
- src/stats.c
- src/tcache.c
- test/include/test/arena_util.h
- test/unit/cache_bin.c
- test/unit/hpa_background_thread.c
- test/unit/mallctl.c
- test/unit/retained.c
- test/unit/stats.c
- test/unit/tcache_max.c
- test/unit/tcache_max.sh
- test/unit/uaf.c
- test/unit/uaf.sh
On deallocation, sampled pointers (specially aligned) get junked and stashed
into tcache (to prevent immediate reuse).  The expected behavior is to have
read-after-free corrupted and stopped by the junk-filling, while
write-after-free is checked when flushing the stashed pointers.
> Implement use-after-free detection using junk and stash

- test/include/test/san.h
- test/unit/tcache_max.c
- test/unit/tcache_max.sh
- test/unit/uaf.c
- test/unit/uaf.sh
The option may be configure-disabled, which resulted in the invalid options
output from the tests.
> Fix test config of lg_san_uaf_align.

- src/jemalloc.c
Realized this is needed when testing the new release (caught by `test/unit/hpa_background_thread`).
> Purge all if the last thread migrated away from an arena.

- include/jemalloc/jemalloc_macros.h.in
... since it also has jemalloc in the base system
> FreeBSD also needs the OS-X "don't declare system functions as nothrow" fix

- test/unit/prof_recent.c
This takes a fair amount of resources.  Under high concurrency it was causing
resource exhaustion such as pthread_create and mmap failures.
The other direction would be, to limit the concurrency of `run_tests.sh`. However the current high concurrency gives us more contention / context switches which are valuable to all tests.
> Lower the num_threads in the stress test of test/unit/prof_recent

- include/jemalloc/internal/jemalloc_internal_externs.h
- include/jemalloc/internal/jemalloc_internal_inlines_b.h
- src/ctl.c
- src/jemalloc.c
This makes debugging slightly easier and avoids the confusion of "should we
create new arenas" here.
> Simplify arena_migrate() to take arena_t* instead of indices.

- Makefile.in
- configure.ac
Based on https://github.com/jemalloc/jemalloc/pull/2075, but with some tweaks:
* Avoid duplication of filenames in variables (no more `UNINSTALL_BINS` and `UNINSTALL_HDRS`)
* Use make syntax to iterate over removed files instead of for loops
* Do not use globs to remove docs and libs. Unlikely, but someone can still store extra `jemalloc*` files unrelated to those that need to be removed
* Stop `echo`ing commands, instead use `-v`
* Forbid spaces in `install_suffix` to partially address David's concern. They didn't work with gmake anyway, but who knows, maybe some other make implementation compatible with gnu make syntax could work. Or gmake would start supporting spaces.
This doesn't address spaces in `prefix` though, but `make install` doesn't work in this case either ¯\\\_(ツ)_/¯
> Support 'make uninstall' - reiterated

- src/jemalloc.c
- src/prof.c
Otherwise, prof_leak may get set after prof_leak_error, and disagree with each
other.
> Initialize prof_leak during prof init.

- test/unit/safety_check.c
Warning by `-Wstringop-overflow`.
> Avoid overflow warnings in test/unit/safety_check.

- configure.ac
When cross-compile, the host type / abi should be checked to determine
background thread compatibility.
> Properly detect background thread support on Darwin.

- src/arena.c
It is possible that ndalloc will be updated before nmalloc, in
arena_large_ralloc_stats_update(), fix this by reorder those calls.
It was found by ClickHouse CI, that periodically hits this assertion [1].
[1]: https://github.com/ClickHouse/ClickHouse/issues/31531
That issue contains lots of examples, with core dump and some gdb output [2].
[2]: https://s3.amazonaws.com/clickhouse-test-reports/34951/96390a9263cb5af3d6e42a84988239c9ae87ce32/stress_test__debug__actions_.html
Here you can find binaries for that particular report [3] you need
clickhouse debug build [4].
[3]: https://s3.amazonaws.com/clickhouse-builds/34951/96390a9263cb5af3d6e42a84988239c9ae87ce32/clickhouse_build_check_(actions)/report.html
[4]: https://s3.amazonaws.com/clickhouse-builds/34951/96390a9263cb5af3d6e42a84988239c9ae …
> [RFC] Fix possible "nmalloc >= ndalloc" assertion.

- configure.ac
- include/jemalloc/internal/tsd.h
- include/jemalloc/internal/tsd_malloc_thread_cleanup.h
- include/jemalloc/internal/tsd_types.h
- include/jemalloc/internal/tsd_win.h
- src/tsd.c
Before this commit, in case FreeBSD libc jemalloc was overridden by another
jemalloc, proper thread shutdown callback was involved only for the overriding
jemalloc. A call to _malloc_thread_cleanup from libthr would be redirected to
user jemalloc, leaving data about dead threads hanging in system jemalloc. This
change tackles the issue in two ways. First, for current and old system
jemallocs, which we can not modify, the overriding jemalloc would locate and
invoke system cleanup routine. For upcoming jemalloc integrations, the cleanup
registering function will also be redirected to user jemalloc, which means that
system jemalloc's cleanup routine will be registered in user's jemalloc and a
single call to _malloc_thread_cleanup will be sufficient to invoke both
callbacks.
> Fix FreeBSD system jemalloc TSD cleanup

- configure.ac
When cross-compile for M1 and no page size specified, use the default 16K and
skip detecting the page size (which is likely incorrect).
> Add a default page size when cross-compile for Apple M1.

- include/jemalloc/internal/pages.h
- src/sec.c
- test/unit/sec.c
Due to a bug in sec initialization, the number of cached size classes
was equal to 198. The bug caused the creation of more than a hundred of
unused bins, although it didn't affect the caching logic.
> Fix size class calculation for sec

- include/jemalloc/internal/sec_opts.h
- src/sec.c
Default SEC max_alloc option value was 32k, disabling SEC for platforms with
lg-page=16. This change enables SEC for all platforms, making minimum max_alloc
value equal to PAGE.
> Do not disable SEC by default for 64k pages platforms

- .travis.yml
- scripts/freebsd/before_install.sh
- scripts/freebsd/before_script.sh
- scripts/freebsd/script.sh
- scripts/gen_travis.py
This PR finalizes the consolidation of all OS we want to run CI on within TravisCI. With the usage based plan, it now takes as long as the slowest Windows job (26 min) to complete the CI. As discussed, the other systems we use (AppVeyor and CirrusCI) will be kept for redundancy purposes.
> Add FreeBSD and enable Windows in TravisCI

- test/integration/rallocx.c
In test/integration/rallocx, full usable size is checked which may confuse
overflow detection.
re: #2238
> Use volatile to workaround buffer overflow false positives.

- .cirrus.yml
Cirrus CI stopped working in #2253 because the 12.2 wasn't supported anymore.
> Update FreeBSD image to 12.3 for cirrus ci.

- Makefile.in
- doc/jemalloc.xml.in
- include/jemalloc/internal/jemalloc_internal_types.h
- src/jemalloc.c
- test/unit/zero_realloc_alloc.c
- test/unit/zero_realloc_alloc.sh
- test/unit/zero_realloc_strict.sh
With realloc(ptr, 0) being UB per C23, the option name "strict" makes less sense
now.  Rename to "alloc" which describes the behavior.
re: #2223
> Rename zero_realloc option "strict" to "alloc".

- include/jemalloc/internal/safety_check.h
- src/ctl.c
- src/safety_check.c
- test/integration/cpp/infallible_new_true.cpp
Allow setting the safety check abort hook through mallctl, which avoids abort()
and core dumps.
> Avoid abort() in test/integration/cpp/infallible_new_true.

- configure.ac
- doc/jemalloc.xml.in
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- src/jemalloc.c
> Make the default option of zero realloc match the system allocator.
