- src/stats.c
Got an error when compiling the code on devserver.
> Fix a compile error caused by mixed declarations and code.

- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
- msvc/projects/vc2015/test_threads/test_threads.cpp
New source files need to be added to the MSVC project manually.
> Minor fixes for MSVC

- include/msvc_compat/windows_extra.h
Addresses issue https://github.com/jemalloc/jemalloc/issues/343
> Remove errno overrides in Windows build

- src/zone.c
This should probably go to master too.
> Fix for issue #420

- src/jemalloc_cpp.cpp
- test/integration/cpp/basic.cpp
This fixes a C++ standards conformance issue.
> Support nullptr in delete operators

- configure.ac
- include/jemalloc/internal/jemalloc_internal.h.in
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- src/zone.c
See, most notably, the commit message on 9baebb39285ea42c429451012034935fe28ed109 wrt what's up on OSX 10.12.
> Fix issues on OSX 10.12

- configure.ac
- include/jemalloc/internal/jemalloc_internal.h.in
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- src/zone.c
This is #561 rebased onto dev, to be committed if CI tests pass.
> Zone allocator fixes

- include/jemalloc/internal/stats_structs.h
- src/arena.c
- src/ctl.c
- src/stats.c
Originally discussion in https://github.com/jemalloc/jemalloc/pull/380.
> Added stats about number of bytes cached in tcache currently.

- Makefile.in
- src/stats.c
- test/unit/stats_print.c
Unsurprisingly, there were bugs in the stats printing code that this uncovered.
> Test JSON output of malloc_stats_print() and fix bugs.

- src/jemalloc.c
This unifies the allocation paths for malloc, posix_memalign, aligned_alloc,
calloc, memalign, valloc, and mallocx, so that they all share common code where
they can.
There's more work that could be done here, but I think this is the smallest
discrete change in this direction.
This shows up as a net increase in total LOC, but there's two mitigating factors:
- This will allow us to straightforwardly remove many of the inline functions in jemalloc_internal.h; I'm just saving that for a later diff.
- Many of the added lines are far simpler than many of the removed lines (the allocation functions are now wrappers that do lots of straightforward parameter setting before forwarding to imalloc; the parameter setting costs many lines, but is trivial to understand).
> Unify the allocation paths

- .appveyor.yml
This will hopefully catch some windows-specific bugs.
> CI: Run --enable-debug builds on windows

- src/extent.c
Set extent as active prior to registration so that other threads can't
modify it in the absence of locking.
> Fix a race in extent_grow_retained().

- src/extent.c
Read adjacent rtree elements while holding element locks, since the
extents mutex only protects against relevant like-state extent mutation.
Fix management of the 'coalesced' loop state variable to merge
forward/backward results, rather than overwriting the result of forward
coalescing if attempting to coalesce backward.  In practice this caused
no correctness issues, but could cause extra iterations in rare cases.
These regressions were introduced by
d27f29b468ae3e9d2b1da4a9880351d76e5a1662 (Disentangle arena and extent
locking.).
> Fix extent_record().

- src/extent_dss.c
Fix extent_alloc_dss() to account for bytes that are not a multiple of
the page size.  This regression was introduced by
577d4572b0821a15e5370f9bf566d884b7cf707c (Make dss operations
lockless.), which was first released in 4.3.0.
> Fix extent_alloc_dss() regression.

- .travis.yml
- scripts/gen_travis.py
This is a cherry-pick (minus the C++ support).
> Beef up travis CI integration testing

- src/chunk_dss.c
Fix chunk_alloc_dss() to account for bytes that are not a multiple of
the chunk size.  This regression was introduced by
e2bcf037d445a84a71c7997670819ebd0a893b4a (Make dss operations
lockless.), which was first released in 4.3.0.
> Fix chunk_alloc_dss() regression.

- include/jemalloc/internal/tsd.h
> Add some missing explicit casts.

- src/stats.c
When multiple threads calling stats_print, race could happen as we read the
counters in separate mallctl calls; and the removed assertion could fail when
other operations happened in between the mallctl calls. For simplicity, output
"race" in the utilization field in this case.
This resolves #616.
> Handle race in stats_arena_bins_print

- ChangeLog
This is based on the dev branch; we will cherry-pick it to the rc-4.5.0 branch as a later step.
> Update ChangeLog for 4.5.0.

- include/jemalloc/internal/arena_externs.h
- include/jemalloc/internal/arena_structs_b.h
- include/jemalloc/internal/private_symbols.txt
- src/arena.c
- src/ctl.c
- src/large.c
- test/unit/decay.c
I verified that the new test_decay_now test fails without the fix in place.
> Fix decay_time:0

- src/tcache.c
Drop tcaches_mtx before calling tcache_destroy().
> Refactor tcaches flush/destroy to reduce lock duration.

- src/jemalloc.c
> Not re-binding iarena when migrate between arenas.

- src/tcache.c
Caching the extents on stack to avoid redundant looking up overhead.
This resolves #598.
> Lookup extent once per time during tcache_flush_small / _large.

- bin/jeprof.in
ref https://github.com/gperftools/gperftools/issues/589
> detect main executable even if PIE is active

- .travis.yml
- scripts/gen_travis.py
> Turn on -Werror for travis CI builds

- include/jemalloc/internal/jemalloc_internal_externs.h
- include/jemalloc/internal/private_symbols.txt
- include/jemalloc/internal/tcache_inlines.h
- include/jemalloc/internal/tsd_externs.h
- include/jemalloc/internal/tsd_inlines.h
- include/jemalloc/internal/tsd_structs.h
- include/jemalloc/internal/tsd_types.h
- src/jemalloc.c
- src/tcache.c
- src/tsd.c
Added tsd_state_nominal_slow, which on fast path malloc() incorporates
tcache_enabled check, and on fast path free() bundles both malloc_slow and
tcache_enabled branches.
> Bundle 3 branches on fast path into tsd_state.

- src/stats.c
Sample output:
```
n_lock_ops       n_waiting      n_spin_acq  n_owner_switch   total_wait_ns     max_wait_ns  max_n_thds
large:                         298797             730           34359          289866      5305023030        50000217         102
extent_freelist:               361572            1478            4671          212569      3740016275        21000091         115
extents_dirty:                 861508           15950          494609          655482    116822507493        98000425         124
extents_muzzy:                 192071               4            8453          190789               0               0           1
extents_retained:              406640           11205          233644          352074     79605345718        93000404         119
decay_dirty: …
```
> Output 4 counters for bin mutexes instead of just 2.

- configure.ac
- doc/jemalloc.xml.in
- include/jemalloc/internal/arena_structs_b.h
- include/jemalloc/internal/extent_externs.h
- include/jemalloc/internal/extent_mmap_externs.h
- include/jemalloc/internal/extent_structs.h
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/private_symbols.txt
- include/jemalloc/internal/stats.h
- include/jemalloc/jemalloc_typedefs.h.in
- src/arena.c
- src/ctl.c
- src/extent.c
- src/extent_mmap.c
- src/jemalloc.c
- src/large.c
- src/stats.c
- test/include/test/extent_hooks.h
- test/unit/arena_reset.c
- test/unit/base.c
- test/unit/mallctl.c
> Add destroy hook to extent_hooks_t

- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
Sync the MSVC project with the latest source file changes (mb.c, util.c, malloc_io.c)
> Make VS2015 project work again

- INSTALL.md
[Render](https://github.com/KindDragon/jemalloc/blob/623233a68f321daeb73d2b3977cea652d682fb9e/INSTALL.md)
> Update and rename INSTALL to INSTALL.md

- include/jemalloc/internal/ctl.h
- include/jemalloc/internal/extent_inlines.h
- include/jemalloc/internal/jemalloc_internal_inlines_a.h
- include/jemalloc/internal/jemalloc_internal_types.h
- src/jemalloc.c
> Refactor (MALLOCX_ARENA_MAX + 1) to be MALLOCX_ARENA_LIMIT.

- .travis.yml
- doc/jemalloc.xml.in
- include/jemalloc/internal/arena_types.h
- scripts/gen_run_tests.py
- scripts/gen_travis.py
This is based on #845; only the last commit is relevant to this pull request.
> Disable percpu_arena by default.

- src/arena.c
This partially solves #857 (the mapped part).
> Fix stats.mapped during deallocation.

- doc/jemalloc.xml.in
- include/jemalloc/internal/jemalloc_internal_externs.h
- src/ctl.c
- src/jemalloc.c
- src/stats.c
> Abort on invalid config options when opt_abort is set.

- src/arena.c
We do not lock extents while advancing epoch.  This change makes sure that we
only read npages from extents once in order to avoid any inconsistency.
This resolves #865.
> Fix npages during arena_decay_epoch_advance().

- INSTALL.md
- configure.ac
- doc/jemalloc.xml.in
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/jemalloc_preamble.h.in
- src/ctl.c
- src/stats.c
- test/unit/pages.c
> Add the --disable-thp option to support cross compiling.

- doc/jemalloc.xml.in
> More thoroughly document the *.{nmalloc,ndalloc,nrequests} mallctls.

- src/background_thread.c
Use a separate boolean to track the enabled status, instead of leaving the
global background thread status inconsistent.
> Track background thread status separately at fork.

- src/pages.c
- src/prof.c
> Pass the O_CLOEXEC flag to open(2).

- src/jemalloc.c
Previously we could still hit these assertions down error paths or in the
extended API.
> Witness assertions: only assert locklessness when non-reentrant.

- src/jemalloc.c
This makes sure we go down slow path w/ a0 in init.
> Set reentrancy level to 1 during init.

- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/jemalloc_preamble.h.in
- src/background_thread.c
Also fix a compilation error #ifndef JEMALLOC_PTHREAD_CREATE_WRAPPER.
> Normalize background thread configuration.

- src/ctl.c
- src/jemalloc.c
> Fix assertion typos.

- configure.ac
> Make sure LG_PAGE <= LG_HUGEPAGE.

- configure.ac
@jasone see https://github.com/jemalloc/jemalloc/pull/818#issuecomment-313485737
> Make symbol listing work when cross-compiling

- src/zone.c
- test/unit/fork.c
> Fix multithreaded fork on OS X and add a test.

- src/pages.c
- src/prof.c
> Compatible with old FD_CLOEXEC

- Makefile.in
- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/jemalloc_preamble.h.in
- include/jemalloc/internal/log.h
- src/jemalloc.c
- src/log.c
- test/unit/log.c
This allows us to enable fine-grained log information, for use in debugging.
> Logging functionality

- src/jemalloc_cpp.cpp
I noticed that the whole newImpl is inlined. Since OOM handling code is
rarely executed, we should only inline the hot path.
> Split out cold code path in newImpl

- scripts/gen_run_tests.py
This is already tested via its inclusion in possible_malloc_conf_opts.
> Remove a redundant '--with-malloc-conf=tcache:false'

- src/jemalloc.c
If ptr is not page aligned, we know the allocation was not sampled. In this case
use the size passed into sdallocx directly w/o accessing rtree.  This improve
sdallocx efficiency in the common case (not sampled && small allocation).
> Only read szind if ptr is not paged aligned in sdallocx.

- src/chunk_dss.c
An sbrk() caller outside jemalloc can decrease the dss, so add a
separate atomic boolean to explicitly track whether jemalloc is
concurrently calling sbrk(), rather than depending on state outside
jemalloc's full control.
Fixes #802 for stable-4
This is a backport of https://github.com/jemalloc/jemalloc/commit/196a53c2aec9fd9fbd17af6803d75c7f631c1ae3g
> Do not assume dss never decreases.

- src/arena.c
This fixes a regression in 9c05490, which introduced the new cache bin ql.  The
list needs to be cleaned up after fork, same as tcache_ql.
> Clear cache bin ql post fork.

- include/jemalloc/internal/rtree_tsd.h
- src/jemalloc.c
Fix warnings discovered in #1019.
> Fix warnings 

- configure.ac
> dev: make symbol listing work when cross-compiling

- include/jemalloc/internal/hash.h
- include/jemalloc/internal/sz.h
Fix warnings by -Wimplicit-fallthrough.
> Add "falls through" comment explicitly.

- src/pages.c
It's possible to build with lazy purge enabled but depoly to systems without
such support.  In this case, rely on the boot time detection instead of keep
making unnecessary madvise calls (which all returns EINVAL).
> Add runtime detection of lazy purging support.

- include/jemalloc/internal/rtree.h
In userspace ARM on Linux, zero-ing the high bits is the correct way to do this.
This doesn't fix the fact that we currently set LG_VADDR to 48 on ARM, when in
fact larger virtual address sizes are coming soon.  We'll cross that bridge when
we come to it.
> ARM: Don't extend bit LG_VADDR to compute high address bits.

- src/base.c
Since we allocate rtree nodes from a0's base, it's pushed to over 1 block on
initialization right away, which makes the auto thp mode less effective on a0.
We change a0 to make the switch on the 3rd block instead.
> Enable a0 metadata thp on the 3rd base block.

- include/jemalloc/internal/base_structs.h
- src/base.c
Added proper synchronization for switching to using THP in auto mode.  Also
fixed stats for number of THPs used.
> Fix base allocator THP auto mode locking and stats.

- src/extent.c
Avoid setting zero and commit in extent_recycle_extract.
> Avoid setting zero and commit if split fails in extent_recycle.

- src/extent.c
We compute the max size required to satisfy an alignment.  However this can be
quite pessimistic, especially with frequent reuse (and combined with state-based
fragmentation).  This commit adds one more fit step specific to aligned
allocations, searching in all potential fit size classes.
w/o this diff, looping ```{ ptr = mallocx(2M, align(2M); free(ptr); }``` results in no reuse of any previously freed memory:
`
0x7f917f000000
0x7f917dc00000
0x7f917d600000
0x7f917ce00000
0x7f917d200000
0x7f917c600000
0x7f917ca00000
0x7f917bc00000
0x7f917c000000
0x7f917b000000
`
with this diff:
`
0x7fa53f600000
0x7fa53f600000
0x7fa53f600000
0x7fa53f600000
0x7fa53f600000
0x7fa53f600000
0x7fa53f600000
0x7fa53f600000
0x7fa53f600000
0x7fa53f600000
`
> Improve the fit for aligned allocation.

- include/jemalloc/internal/jemalloc_internal_decls.h
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
This resolves #1116 and #1099.
> Visual Studio fixes

- .appveyor.yml
This reverts commit ae0f5d5c3f29beb9977148dedb58575757139586.
> Revert "CI: Remove "catgets" dependency on appveyor."

- src/background_thread.c
- test/unit/background_thread_enable.c
1) make sure background thread 0 is always created; and 2) fix synchronization
between thread 0 and the control thread.
> Fix a background_thread shutdown issue.

- src/extent.c
preserve_lru feature adds lots of complication, for little value.
Removing it means merged extents are re-added to the lru list, and may
take longer to madvise away than they otherwise would.
Canaries after removal seem flat for several services (no change).
> extents: Remove preserve_lru feature.

- include/jemalloc/internal/arena_inlines_a.h
- include/jemalloc/internal/prof_inlines_a.h
- include/jemalloc/internal/prof_inlines_b.h
- src/prof.c
> Control idump and gdump with prof_active.

- src/extent.c
> Fix arguments passed to extent_init.

- configure.ac
> Fix a typo.

- INSTALL.md
Related to https://github.com/jemalloc/jemalloc/issues/974
> Adding `install_lib_pc`

- INSTALL.md
- TUNING.md
View in https://github.com/interwq/jemalloc/blob/tuning/TUNING.md
This resolves #1133
>  Add TUNING.md

- jemalloc.pc.in
> Reformat the version number in jemalloc.pc.in.

- src/stats.c
Increase the width to ensure enough space for long running programs.
> Tweak the format of the per arena summary section.

- src/arena.c
When muzzy decay is disabled, no need to allocate from extents_muzzy.  This
saves us a couple of mutex operations down the extents_alloc path.
> Avoid taking extents_muzzy mutex when muzzy is disabled.

- src/tcache.c
- test/integration/mallocx.c
This regression was introduced in c834912 (incorrect arena used).
> Fix arena locking in tcache_bin_flush_large().

- include/jemalloc/internal/bit_util.h
This overrides #1118 and is being used to push changes required to implement #674 
This is being done for clean commit and merge.
> optimize calculation of next power of 2 >= of given number

- include/jemalloc/internal/prof_inlines_b.h
The diff 'refactor prof accum...' moved the bytes_until_sample
subtraction before the load of tdata.  If tdata is null,
tdata_get(true) will overwrite bytes_until_sample, but we
still sample the current allocation.   Instead, do the subtraction
and check logic again, to keep the previous behavior.
blame-rev: 0ac524308d3f636d1a4b5149fa7adf24cf426d9c
> prof: Fix memory regression

- src/extent.c
When retain is enabled, the default dalloc hook does nothing (since we avoid
munmap).  But the overhead preparing the call is high, specifically the extent
de-register and re-register involve locking and extent / rtree modifications.
Bypass the call with retain in this diff.
> Bypass extent_dalloc when retain is enabled.

- src/extent.c
We eagerly coalesce large buffers when deallocating, however the previous logic
around this introduced extra lock overhead -- when coalescing we always lock the
neighbors even if they are active / small, while for active extents nothing can
be done; and the intent was to coalesce only large buffers to reduce
fragmentation.
This commit checks if the neighbor extents are potentially active before
locking, and avoids coalescing small extents if not intended to.  This speeds up
large_dalloc by ~20%.  It also fixes some undesired behavior: we could stop
coalescing because a small buffer was merged, while a large neighbor was ignored
on the other side.
> Optimize large deallocation.

- src/tcache.c
When destroying tcache, decay may not be triggered since tsd is non-nominal.
Explicitly decay to avoid pathological cases.
This resolves #1347.
> Properly trigger decay on tcache destory.

- include/jemalloc/internal/tcache_inlines.h
- include/jemalloc/internal/tcache_types.h
- src/tcache.c
> Fix tcache_flush (follow up cd2931a).

- include/jemalloc/internal/emitter.h
- include/jemalloc/internal/mutex_prof.h
- src/stats.c
> Add rate counters to stats

- test/unit/binshard.c
Verified that this could catch the issue being fixed in #1389.
> Add unit test for producer-consumer pattern.

- .cirrus.yml
Give up on configuring `VERSION`, since there doesn't appear to be a simple way of getting it right in general.
> Cirrus versionless

- doc/jemalloc.xml.in
- include/jemalloc/internal/arena_externs.h
- include/jemalloc/internal/arena_inlines_b.h
- include/jemalloc/internal/arena_types.h
- src/arena.c
- src/ctl.c
- src/jemalloc.c
- src/stats.c
- test/unit/huge.c
- test/unit/mallctl.c
The keyword huge tend to remind people of huge pages which is not relevent to
the feature.
> Rename huge_threshold to oversize_threshold.

- .travis.yml
- INSTALL.md
- configure.ac
- scripts/gen_travis.py
- src/background_thread.c
This makes it possible to build full static binary.
This resolves #907
> Add configure option --disable-libdl

- src/extent.c
- src/jemalloc.c
Both issues were discovered by @zoulasc, in #1460
> By @zoulasc: fix a missing unlock bug and a warning

- bin/jeprof.in
The same pr is submitted into gperftools:
https://github.com/gperftools/gperftools/pull/1105
> Fix typo derived from tcmalloc's pprof

- Makefile.in
- configure.ac
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> configure.ac: Add an option to disable doc

- include/jemalloc/internal/sc.h
Mainly fixing typos.  The only non-trivial change is in the
computation for SC_NPSIZES, though the result wouldn't be any
different when SC_NGROUP = 4 as is always the case at the moment.
> Improve size class header

- src/jemalloc.c
Define more readable macros than yes and no.
> Improve macro readability in malloc_conf_init

- src/ctl.c
- test/unit/extent_util.c
Added tests for large size classes and expanded the tests to
cover wider range of allocation sizes.
> Improve memory utilization tests

- src/ctl.c
The new experimental mallctl exposes the arena pactive counter to applications,
which allows fast read w/o going through the mallctl / epoch steps.  This is
particularly useful when frequent balancing is required, e.g. when having
multiple manual arenas, and threads are multiplexed to them based on usage.
> Add experimental.arenas.i.pactivep.

- src/prof.c
> Sanity check on prof dump buffer size.

- Makefile.in
- include/jemalloc/internal/prof_externs.h
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj.filters
- src/prof.c
- src/prof_log.c
`prof.c` is growing too long, so trying to modularize it.  There are
a few internal functions that had to be exposed but I think it is a
fair trade-off.
> Refactor prof log

- src/prof_log.c
- test/unit/prof_log.c
Make use of the new buffered writer for the output of
`prof_log_stop`.
> Buffer prof log stop

- src/jemalloc.c
The buffered writer is only used in `malloc_stats_print` when both
the `write_cb` parameter and `je_malloc_message` are not set;
without buffering (as is the case before this change)
`malloc_stats_print` would invoke `malloc_write_fd` for every single
`printf` (including printing just the line break in many places).
> Buffer stats printing

- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
> Fix MSVC 2015 build, as proposed by @christianaguilera-foundry.

- test/include/test/test.h
- test/src/test.c
- test/unit/log.c
> Workaround the stringop-overflow check false positives.

- scripts/gen_run_tests.py
Signed-off-by: Giridhar Prasath R <cristianoprasath@gmail.com>
Refers: #957
> check GNU make exists in path

- src/tcache.c
Set the proper alignment when allocating space for the tcache bin stack.
The bug was Introduced in 7599c82. 
Resolves #1606
> Fix tcache bin stack alignment.

- Makefile.in
> Fix a typo in Makefile.

- doc/jemalloc.xml.in
> Emphasize no modification through thread.allocatedp allowed.

- src/jemalloc.c
Explicityly mark the non-slab case unlikely.  Previously there were jumps in the
common case.
> Add branch hints to free_fastpath

- src/arena.c
Clean up some redundant operations (looks to be leftover from previous refactoring).
> Refactor arena_bin_malloc_hard().

- Makefile.in
- include/jemalloc/internal/buf_writer.h
- include/jemalloc/internal/malloc_io.h
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj.filters
- src/buf_writer.c
- src/jemalloc.c
- src/malloc_io.c
- src/prof_log.c
- src/prof_recent.c
- test/unit/buf_writer.c
Preparation for adding more functionalities.
> Restructure buffered writer

- include/jemalloc/internal/buf_writer.h
- src/jemalloc.c
- src/prof_log.c
- src/prof_recent.c
Also added stronger assertions in the buffered writer initializer.
> Fallback to unbuffered printing if OOM

- src/pages.c
- NetBSD overcommits
- When mapping pages, use the maximum of the alignment requested and the
compiled-in PAGE constant which might be greater than the current kernel
pagesize, since we compile binaries with the maximum page size supported
by the architecture (so that they work with all kernels).
> NetBSD specific changes:

- msvc/projects/vc2015/jemalloc/jemalloc.vcxproj.filters
- msvc/projects/vc2017/jemalloc/jemalloc.vcxproj.filters
This is to supplement https://github.com/jemalloc/jemalloc/commit/403f2d1664acfae920e8e6ce51e2695d826a0628 .
> Add inspect.c to MSVC filters

- src/ehooks.c
Check the is_head state before merging two extents.  Disallow the merge if it's
crossing two separate mmap regions.  This enforces first-fit (by not losing the
SN) at a very small cost.
> Disallow merge across mmap regions to preserve SN / first-fit

- src/tcache.c
> Avoid variable length array with length 0.

- src/prof.c
This is a minor correction, mainly for the purpose of being rigorous. The sampling result should mostly be unaffected. The couple of things I'm correcting:
- In the previous logic `u` is in theory in the range of `[0, 1)`. An exact `0` would not be valid for `log(u)` to work. So I'm shifting it to `(0, 1]`, by changing an exact `r = 0` to an exact `u = 1`. (Directly changing `r = 0` to `r = 2^53` would be risky because the floating point computation might result in something slightly above `1`, which would make `log(u)` positive.)
- Changed the comment so that `bytes_until_sample` is computed as 1 plus the floor, rather than the ceiling. This is also what we're actually computing. It is also the correct approach if `u` is in the range of `(0, 1]`; directly taking the ceiling would …
> Correction on geometric sampling

- src/jemalloc_cpp.cpp
Get rid of
```
src/jemalloc_cpp.cpp:116:1: warning: unused function 'sizedDeleteImpl' [-Wunused-function]
sizedDeleteImpl(void* ptr, std::size_t size) noexcept {
^
1 warning generated.
```
And reorganize the APIs so that they follow a more intuitive order.
> Reorganize cpp APIs and suppress unused function warnings

- configure.ac
- include/jemalloc/internal/sc.h
- src/sc.c
These were part of a stack to make quantum and ngroup dynamic. I think that's more than I want to bite off right now, but no sense in throwing away the bits that are a raw cleanup.
> Clean up some SC computations

- test/stress/sizes.c
I've wanted to have these handy before.
Small, mostly theoretical, bug fix while we're here.
> stress/sizes: Add a couple more types and fix a bug.

- include/jemalloc/internal/prof_externs.h
- include/jemalloc/internal/prof_log.h
- include/jemalloc/internal/prof_recent.h
- src/prof.c
- src/prof_data.c
- src/prof_log.c
- src/prof_recent.c
- test/unit/prof_recent.c
This is an answer to https://github.com/jemalloc/jemalloc/pull/1794#discussion_r441208318. The nature of the change goes beyond #1794 so have it as a separate PR.
> Expose prof testing internal functions

- Makefile.in
- include/jemalloc/internal/prof_externs.h
- src/ctl.c
- src/jemalloc.c
- src/prof.c
- test/unit/mallctl.c
- test/unit/prof_sys_thread_name.c
- test/unit/prof_sys_thread_name.sh
- test/unit/prof_use_sys_thread_name.sh
A more thorough answer to https://github.com/jemalloc/jemalloc/pull/1794#discussion_r414054227.
> Improve naming for prof system thread name option

- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/jemalloc_preamble.h.in
- src/jemalloc.c
- src/pages.c
reusing slighty linux configuration as possible, aligning the
address range to HUGEPAGE.
> enabling mpss on solaris/illumos.

- src/prof_log.c
Before this change, the `prof_log_start()` call at init time is before the mutex and the timestamp are initialized. Also, the hash table creation can take place at the first freed sample rather than at init time.
> Corrections for prof_log_start()

- include/jemalloc/internal/prof_recent.h
- include/jemalloc/internal/prof_structs.h
- src/prof.c
- src/prof_recent.c
- test/unit/prof_recent.c
This is the minimal subset of #1899 for bug fixing purpose.
> Correct usize in prof last-N record

- .gitignore
- doc_internal/PROFILING_INTERNALS.md
This documents and explains some of the logic behind the profiling implementation.
> Add PROFILING_INTERNALS.md.

- .travis.yml
- scripts/gen_travis.py
Hi,
I have made changes to gen_travis.py and got different options with gcc enabled for PPC64LE as well, request you to please review.
Thanks 
Old PR can be purged #1912
> Fresh PR for PPC64LE

- src/jemalloc.c
The sanity check requires a functional TSD, which free_fastpath only guarantees
after the threshold branch.  Move the check function to afterwards.
> Fix the alloc_ctx check in free_fastpath.

- src/tcache.c
Without a lock held continuously between checking tcaches_past and incrementing
it, it's possible for two threads to go down manual creation path
simultaneously.  If the number of tcaches is one less than the maximum, it's
possible for both to create a tcache and increment tcaches_past, with the second
thread returning a value larger than TCACHES_MAX.
> Tcaches: Fix a subtle race condition.

- doc/jemalloc.xml.in
- include/jemalloc/internal/tcache_externs.h
- src/ctl.c
- src/jemalloc.c
- src/tcache.c
- test/unit/mallctl.c
- test/unit/stats.c
Though for convenience, keep parsing lg_tcache_max.
> Switch from opt.lg_tcache_max to opt.tcache_max

- build-aux/config.guess
- build-aux/config.sub
https://git.savannah.gnu.org/cgit/config.git/commit/?id=77632d92f25e26b95c64afd3700d51bd03587613
> Update config.{guess,sub} to 2020-11-07@77632d9

- include/jemalloc/internal/edata.h
- include/jemalloc/internal/edata_cache.h
- src/edata.c
This isn't a tree any more, and it mildly irritates me any time I see it.
> Rename edata_tree_t -> edata_avail_t.

- configure.ac
- include/jemalloc/internal/jemalloc_internal_defs.h.in
- include/jemalloc/internal/tsd_generic.h
- src/pages.c
Mainly fix bootstrapping.
Also add autoconf for posix_madvise and alloca.
> fix a few issues running jemalloc on qnx

- src/jemalloc.c
This is a follow-up to a previous [discussion](https://github.com/jemalloc/jemalloc/pull/1899#issuecomment-669487108), and is also another sanity check to see if the usize <-> (size, alignment) mapping contract is violated in any way in any environment.
> Enforce realloc sizing stability

- src/extent.c
The edge case in which pages_map returns (void *)PAGE can trigger an incorrect
assertion failure.  Avoid it.
This was pointed out by @semihalf-gorecki-dawid. It occurs only in debug mode, so I think we don't need to cut a new release right away.
> Extent.c: Avoid an incorrect rtree NULL-check.

- .cirrus.yml
This is a precondition for building.
I'm not actually sure this will fix the CI errors, but we'll see.
> Add m4 to .cirrus.yml.

- src/safety_check.c
> Sized deallocation: fix a typo.

- src/stats.c
Missed a layer of indirection.
> Stats: Fix a printing bug when hpa_dirty_mult = -1

- test/include/test/bgthd.h
- test/include/test/jemalloc_test.h.in
- test/integration/extent.c
- test/unit/arena_decay.c
- test/unit/oversize_threshold.c
- test/unit/stats.c
Also added the shared utility to check if background_thread is enabled.
> Fix an interaction between the oversize_threshold test and bgthds.

- include/jemalloc/internal/quantum.h
Signed-off-by: Vineet Gupta <vgupta@synopsys.com>
> ARC: add Minimum allocation alignment

- include/jemalloc/internal/decay.h
- src/background_thread.c
- src/decay.c
- test/unit/decay.c
Isolate the computation of purge interval from background thread logic and
move into more suitable file.
> Clean up background thread sleep computation

- scripts/gen_run_tests.py
Insignificant changes to make the script runnable on python3.
> Port gen_run_tests.py to python3

- src/prof_log.c
So that atexit() is only done when prof_log is used.
Replaces #1931
> Delay the atexit call to prof_log_start().

- src/jemalloc.c
> Check prof_active in addtion to opt_prof during batch_alloc().

- src/thread_event.c
The event counters maintain a relationship with the current bytes: last_event <=
current < next_event.  When a reinit happens (e.g. reincarnated tsd), the last
event needs progressing because all events start fresh from the current bytes.
In one of our applications' integration test, this assertion was triggered after tsd
re-init triggered by reincarnated tsd:
https://github.com/jemalloc/jemalloc/blob/dev/src/thread_event.c#L123
This PR added the missing last_event initialization, which is needed to maintain
the correct last / next / current state.
> Fix the initialization of last_event in thread event init.

- src/jemalloc.c
Also refactor the handling of the non-deterministic case.  Notably allow the
case with narenas set to proceed w/o warnings, to not affect existing valid use
cases.
> Only invoke malloc_cpu_count_is_deterministic() when necessary.

- include/jemalloc/internal/jemalloc_internal_inlines_b.h
- include/jemalloc/internal/nstime.h
- include/jemalloc/internal/prof_externs.h
- include/jemalloc/internal/prof_inlines.h
- src/bin_info.c
- src/ckh.c
- src/ctl.c
- src/extent.c
- src/jemalloc.c
- src/pa.c
- src/pac.c
- src/prof.c
- src/prof_data.c
- src/prof_sys.c
- src/stats.c
- test/analyze/prof_bias.c
- test/src/test.c
- test/unit/arena_reset.c
- test/unit/atomic.c
- test/unit/batch_alloc.c
- test/unit/pa.c
- test/unit/prof_idump.c
- test/unit/prof_recent.c
- test/unit/prof_reset.c
- test/unit/rb.c
- test/unit/retained.c
Verified with EXTRA_CFLAGS=-Wshadow.
Resolves #1863
> Fix shadowed variable usage.

- test/unit/hpa_background_thread.c
Under high concurrency / heavy test load (e.g. using run_tests.sh), the
background thread may not get scheduled for a longer period of time.  Retry 100
times max before bailing out.
Verified that the fix works with `run_tests.sh` -- it was failing reliably every ~100 runs.
> Fix the background thread sleep in `test/unit/hpa_background_thread`

- src/extent.c
With DSS as primary, the default merge impl will (correctly) decline to merge
when one of the extent is non-dss.  The error path should tolerate the
not-merged extent being in a merging state.
Caught by `CC="gcc -m32" CXX="g++ -m32" ./configure --enable-debug --with-lg-page=16 --with-malloc-conf=dss:primary,background_thread:true` by run_tests.sh
> Fix the extent state checking on the merge error path.

- Makefile.in
- configure.ac
> Fix doc build with install-suffix.

- INSTALL.md
Update INSTALL.md, reflecting the addition of 'uninstall' target.
> Document 'make uninstall'

- test/unit/background_thread_enable.c
To avoid resource exhaustion on 32-bit platforms.
Resolve #2272
> Make test/unit/background_thread_enable more conservative.
